cmd/percona-xtradb-cluster-operator/main.go, deploy/cr.yaml, deploy/operator.yaml, version/server.go
- Automatically defining the platform on OpenShift 3.11+
- Bump Operator version
=> Version updates

pkg/controller/perconaxtradbbackup/perconaxtradbbackup_controller.go, pkg/controller/perconaxtradbcluster/backup.go, pkg/controller/perconaxtradbcluster/perconaxtradbcluster_controller.go, pkg/pxc/backup/job.go, pkg/pxc/backup/scheduled.go
=> Scheduled backup's jobs/pods clean-up

pkg/apis/pxc/v1alpha1/perconaxtradbcluster_types.go, pkg/controller/perconaxtradbcluster/perconaxtradbcluster_controller.go, pkg/controller/perconaxtradbcluster/upgrade.go, pkg/pxc/app/pvc.go, pkg/pxc/statefulset.go
=> Better check of CR options

deploy/cr.yaml, pkg/controller/perconaxtradbcluster/perconaxtradbcluster_controller.go
If finalizers doesn't set - pvcs won't be removed with stateful set
=> Add pvc finalizers for pxc nodes and change the name of proxy's one

e2e-tests/conf/sysbench.yaml
1) Replaced insert.lua script with read_write.lua for OLTP transaction
2) Increased table count to 16
3) Increased sysbench threads to 16
=> Updated sysbench configuration to use latest lua script

deploy/olm-catalog/percona-xtradb-cluster-operator.0.3.0-rc1.clusterserviceversion.yaml, deploy/olm-catalog/percona.package.yaml, deploy/olm-catalog/perconaxtradbbackups.crd.yaml, deploy/olm-catalog/perconaxtradbclusters.crd.yaml
Wasn't sure if you want this in the master branch instead, currently opened against the `openshift-4.0` branch.
Let's merge this when https://github.com/operator-framework/community-operators/pull/96 is merged, in case there are any other suggestions on that one, just opened this so we don't forget to add the files to this repo as well.
=> deploy/olm-catalog/*: Add initial olm files

pkg/controller/perconaxtradbcluster/perconaxtradbcluster_controller.go, pkg/pxc/pdb.go
- The wrong configuration was applied for ProxySQL
- Misspelled functions name
=> Fixes for PodDisruptionBudget

deploy/cr.yaml, pkg/apis/pxc/v1alpha1/perconaxtradbcluster_types.go, pkg/pxc/statefulset.go
=> Add grace-period option to pods spec

source/backups.rst
Updated backup topic to remove punctuation.
=> Cloud 210 backup docs

source/TLS.rst, source/index.rst
TLS document and added TLS to the index.rst.
=> CLOUD-194-TLS updated format to rst, updated index

build/Dockerfile
The `MAINTAINER` option was deprecated long time ago in favor of `LABEL`
Resolves:
Related:
=> fix the Dockerfile deprecation issue

source/backups.rst, source/kubernetes.rst, source/openshift.rst, source/operator.rst, source/users.rst
Some step shall be updated due to typos or incorrect logic.
=> CLOUD-310 PXC documentation update

e2e-tests/affinity/run, e2e-tests/build, e2e-tests/demand-backup/run, e2e-tests/functions, e2e-tests/init-deploy/run, e2e-tests/limits/run, e2e-tests/one-pod/run, e2e-tests/operator-self-healing/run, e2e-tests/recreate/run, e2e-tests/scaling-proxysql/run, e2e-tests/scaling/run, e2e-tests/scheduled-backup/run, e2e-tests/self-healing-advanced/run, e2e-tests/self-healing/compare/proxy-vars.sql, e2e-tests/self-healing/run, e2e-tests/storage/run, e2e-tests/upgrade/run
In order to make tests more stable to kubectl errors
retry mechanism has been implemented
=> CLOUD-323 Kubectl error tolerance

source/users.rst
updated table and text. Changed formatting to RST style
=> CLOUD-283-doc-error 

e2e-tests/monitoring/compare/statefulset_monitoring-proxysql-oc.yml
proxysql pods have to be adjusted
=> CLOUD-481 Openshift monitoring test fix

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/status.go
Inspired by
https://github.com/kubernetes/community/blob/57946ce0aef2e7f3540f37cc598fb8623704f6ed/contributors/devel/sig-architecture/api-conventions.md
https://github.com/kubernetes/community/blob/79748734e6225769eb5186d0496adeb9f64789cf/contributors/design-proposals/apps/statefulset-update.md
https://github.com/kubernetes/community/blob/712590c108bd4533b80e8f2753cadaa617d9bdf2/contributors/devel/sig-api-machinery/controllers.md
https://thenewstack.io/kubernetes-deployments-work/
=> K8SPXC-221 Add observedGeneration field

pkg/apis/pxc/v1/pxc_types.go
=> K8SPXC-231 fix TerminationGracePeriodSeconds for ProxySQL

e2e-tests/init-deploy/compare/statefulset_no-proxysql-pxc-oc.yml, e2e-tests/init-deploy/compare/statefulset_no-proxysql-pxc.yml, e2e-tests/init-deploy/conf/no-proxysql.yml, e2e-tests/storage/compare/statefulset_emptydir-proxysql-oc.yml, e2e-tests/storage/compare/statefulset_emptydir-proxysql.yml, e2e-tests/storage/compare/statefulset_emptydir-pxc.yml, e2e-tests/storage/compare/statefulset_hostpath-proxysql-oc.yml, e2e-tests/storage/compare/statefulset_hostpath-proxysql.yml, e2e-tests/storage/conf/emptydir.yml, e2e-tests/storage/run
after this change, the init-deploy test should work on OpenShift again
=> K8SPXC-262 move ephemeral-storage to storate test

e2e-tests/functions, e2e-tests/self-healing-advanced/run
* try to wait for data synchronization between pxc nodes
* add smart check of 'CrashLoopBackOff' status
=> K8SPXC-264 Improve scaling tests

e2e-tests/functions, e2e-tests/scheduled-backup/run, e2e-tests/security-context/run, e2e-tests/self-healing/run
Since volume allocation on alternative providers works a bit slower than
on GKE, delay extension is needed
=> CLOUD-515 test compliance

.github/pr-badge.yml
[![CLOUD-543](https://badgen.net/badge/JIRA/CLOUD-543/green)](https://jira.company.com/browse/CLOUD-543)
=> CLOUD-543 fix badge URL

pkg/controller/pxc/controller.go, pkg/controller/pxc/users.go, pkg/pxc/users/users.go
[![SPXC-252](https://badgen.net/badge/JIRA/SPXC-252/green)](https://jira.percona.com/browse/SPXC-252)
=> K8SPXC-252 Auto updating system users

pkg/controller/pxc/backup.go, pkg/controller/pxcbackup/controller.go, pkg/controller/pxcrestore/restore.go, pkg/pxc/backup/job.go, pkg/pxc/backup/restore.go, pkg/pxc/backup/scheduled.go
[![CLOUD-474](https://badgen.net/badge/JIRA/CLOUD-474/green)](https://jira.percona.com/browse/CLOUD-474)
Return error instead of logging if failed to process given resources
=> CLOUD-474: error handling for wrong resources

deploy/cr.yaml, pkg/controller/pxc/backup.go, pkg/controller/pxc/users.go
[![K8SPXC-284](https://badgen.net/badge/JIRA/K8SPXC-284/green)](https://jira.percona.com/browse/K8SPXC-284)
=> K8SPXC-284 Linter warnings

deploy/cr.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/pxc/service.go
[![CLOUD-404](https://badgen.net/badge/JIRA/CLOUD-404/green)](https://jira.percona.com/browse/CLOUD-404)
=> CLOUD-404: add LoadBalancerSourceRanges and ServiceAnnotations to proxysql service

source/users.rst
[![K8SPXC-300](https://badgen.net/badge/JIRA/K8SPXC-300/green)](https://jira.percona.com/browse/K8SPXC-300)
=> K8SPXC-300 Mention 32 chars limit for password

Jenkinsfile, e2e-tests/demand-backup-encrypted-with-tls/run, e2e-tests/functions, e2e-tests/monitoring-2-0/run, e2e-tests/monitoring/run, e2e-tests/restore-to-encrypted-cluster/run
[![CLOUD-546](https://badgen.net/badge/JIRA/CLOUD-546/green)](https://jira.percona.com/browse/CLOUD-546)
=> CLOUD-546 Upgrade to Helm v3

source/gke.rst, source/kubernetes.rst, source/minikube.rst, source/openshift.rst
[![K8SPSMDB-213](https://badgen.net/badge/JIRA/K8SPSMDB-213/green)](https://jira.percona.com/browse/K8SPSMDB-213)
=> K8SPSMDB-213 use v symbol in version tag

source/backups.rst
[![K8SPXC-283](https://badgen.net/badge/JIRA/K8SPXC-283/green)](https://jira.percona.com/browse/K8SPXC-283)
=> K8SPXC-283 mention storage size in backup docs

source/backups.rst, source/eks.rst
[![K8SPXC-288](https://badgen.net/badge/JIRA/K8SPXC-288/green)](https://jira.percona.com/browse/K8SPXC-288)
=> K8SPXC-288 eks quickstart - initial doc

source/index.rst
[![CLOUD-532](https://badgen.net/badge/JIRA/CLOUD-532/green)](https://jira.percona.com/browse/CLOUD-532)
=> CLOUD-532 enhance main TOC

source/monitoring.rst
[![CLOUD-403](https://badgen.net/badge/JIRA/CLOUD-403/green)](https://jira.percona.com/browse/CLOUD-403)
=> CLOUD-403 show different commands for OpenShift and Kubernetes

e2e-tests/self-healing/compare/proxy-vars-80.sql
[![CLOUD-556](https://badgen.net/badge/JIRA/CLOUD-556/green)](https://jira.percona.com/browse/CLOUD-556)
=> CLOUD-556 Fix vars after update

pkg/controller/pxc/controller.go, pkg/controller/pxc/users.go
[![K8SPXC-298](https://badgen.net/badge/JIRA/K8SPXC-298/green)](https://jira.percona.com/browse/K8SPXC-298)
=> K8SPXC-298 Add auto sync PXC users with ProxySQL

deploy/backup/README.md, deploy/backup/copy-backup.sh, deploy/backup/restore-backup.sh, deploy/cr.yaml
[![K8SPXC-280](https://badgen.net/badge/JIRA/K8SPXC-280/green)](https://jira.percona.com/browse/K8SPXC-280)
This is adding possibility to enable compressed backups in cr.
Corresponding PR for backup docker images is here: https://github.com/percona/percona-docker/pull/229
=> K8SPXC-280 Add support for compressed backups

source/scaling.rst
[![K8SPXC-320](https://badgen.net/badge/JIRA/K8SPXC-320/green)](https://jira.percona.com/browse/K8SPXC-320)
=> K8SPXC-320 fix broken link to options; try using a single-option link

build/pxc-entrypoint.sh
[![K8SPXC-257](https://badgen.net/badge/JIRA/K8SPXC-257/green)](https://jira.percona.com/browse/K8SPXC-257)
init container runs not in all cases, see https://github.com/kubernetes/kubernetes/issues/66699
in result, after SST, we sometimes have the issue:
```
Error: failed to start container "pxc": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/var/lib/mysql/pxc-entrypoint.sh\": stat /var/lib/mysql/pxc-entrypoint.sh: no such file or directory": unknown
```
joiner during SST runs this line https://github.com/percona/percona-xtradb-cluster/blob/8.0/scripts/wsrep_sst_xtrabackup-v2.sh#L2040
in result `/var/lib/mysql/pxc-entrypoint.sh` file become deleted
but after some things, like failed liveness probe, Kubernetes …
=> K8SPXC-256 fix "no such file issue"

deploy/bundle.yaml, deploy/cr.yaml, deploy/crd.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/controller/pxc/status.go, pkg/controller/pxc/upgrade.go, pkg/pxc/app/statefulset/haproxy.go, pkg/pxc/app/statefulset/node.go, pkg/pxc/app/volumes.go, pkg/pxc/service.go, pkg/pxc/statefulset.go
[![K8SPXC-294](https://badgen.net/badge/JIRA/K8SPXC-294/green)](https://jira.percona.com/browse/K8SPXC-294)
=> K8SPXC-294 : creating layout for haproxy statefulset

source/scaling.rst
[![K8SPXC-332](https://badgen.net/badge/JIRA/K8SPXC-332/green)](https://jira.percona.com/browse/K8SPXC-332)
=> K8SPXC-332 improve scaling command

pkg/controller/pxc/controller.go, pkg/controller/pxc/upgrade.go, pkg/pxc/app/config/configmap.go
[![K8SPXC-294](https://badgen.net/badge/JIRA/K8SPXC-294/green)](https://jira.percona.com/browse/K8SPXC-294)
=> K8SPXC-294 fix HAProxy config map creation

pkg/controller/pxc/controller.go, pkg/pxc/service.go
[![K8SPXC-353](https://badgen.net/badge/JIRA/K8SPXC-353/green)](https://jira.percona.com/browse/K8SPXC-353)
Users can disable and enable HAProxy or ProxySQL anytime.
Corresponding services should be deleted on disable.
=> K8SPXC-353 proxy service should be removed on disable

pkg/controller/pxc/version.go
[![K8SPXC-338](https://badgen.net/badge/JIRA/K8SPXC-338/green)](https://jira.percona.com/browse/K8SPXC-338)
=> K8SPXC-338 Remove confusing log message

pkg/controller/pxc/vs.go
update path, since version service base url path was changed
=> Fix version service URL path

pkg/controller/pxc/version.go
[![K8SPXC-358](https://badgen.net/badge/JIRA/K8SPXC-358/green)](https://jira.percona.com/browse/K8SPXC-358)
=> K8SPXC-358 UpgradeOptions.Apply should be case insensitive

pkg/controller/pxc/vs.go
[![K8SPXC-357](https://badgen.net/badge/JIRA/K8SPXC-357/green)](https://jira.percona.com/browse/K8SPXC-357)
=> K8SPXC-357: Fix version service URL

pkg/controller/pxc/version.go, pkg/controller/pxc/vs.go
[![K8SPXC-359](https://badgen.net/badge/JIRA/K8SPXC-359/green)](https://jira.percona.com/browse/K8SPXC-359)
=> K8SPXC-360: Use HAProxy info from version service

build/pxc-configure-pxc.sh
[![K8SPXC-344](https://badgen.net/badge/JIRA/K8SPXC-344/green)](https://jira.percona.com/browse/K8SPXC-344)
fix self-healing-advanced test. It is important to have non-empty wsrep_cluster_address in case when cluster in broken state
=> K8SPXC-344 add only ready PXC members into the config

e2e-tests/init-deploy/compare/statefulset_no-proxysql-pxc-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-no-limits-pxc-oc.yml, e2e-tests/monitoring/compare/statefulset_monitoring-pxc-oc.yml, e2e-tests/security-context/compare/pod_restore-src-restore-pvc-sec-context-oc.yml
=> K8SPXC-356 Openshift related adjustments

pkg/controller/pxc/upgrade.go
[![K8SPXC-361](https://badgen.net/badge/JIRA/K8SPXC-361/green)](https://jira.percona.com/browse/K8SPXC-361)
=> K8SPXC-361: Prevent panic

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/upgrade.go, pkg/pxc/queries/queries.go
[![K8SPXC-361](https://badgen.net/badge/JIRA/K8SPXC-361/green)](https://jira.percona.com/browse/K8SPXC-361)
=> K8SPXC-361 use ProxySQL defaults only if ProxySQL is enabled

source/backups.rst
[![K8SPXC-348](https://badgen.net/badge/JIRA/K8SPXC-348/green)](https://jira.percona.com/browse/K8SPXC-348)
=> K8SPXC-348 document backup compression

source/users.rst
[![K8SPXC-349](https://badgen.net/badge/JIRA/K8SPXC-349/green)](https://jira.percona.com/browse/K8SPXC-349)
=> K8SPXC-349 automated system users management

pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-361](https://badgen.net/badge/JIRA/K8SPXC-361/green)](https://jira.percona.com/browse/K8SPXC-361)
=> K8SPXC-361: Check if version in spec is nil

pkg/controller/pxc/version.go, pkg/controller/pxc/vs.go
[![K8SPXC-365](https://badgen.net/badge/JIRA/K8SPXC-365/green)](https://jira.percona.com/browse/K8SPXC-365)
=> K8SPXC-365 fix detection of Proxy image changes

source/haproxy-conf.rst, source/proxysql-conf.rst
[![K8SPXC-342](https://badgen.net/badge/JIRA/K8SPXC-342/green)](https://jira.percona.com/browse/K8SPXC-342)
=> K8SPXC-342 haproxy doc

e2e-tests/functions
[![K8SPXC-366](https://badgen.net/badge/JIRA/K8SPXC-366/green)](https://jira.percona.com/browse/K8SPXC-366)
=> K8SPXC-366 Fix the command which cleans up unused namespaces

build/pxc-entrypoint.sh, deploy/backup/copy-backup.sh
[![K8SPXC-373](https://badgen.net/badge/JIRA/K8SPXC-373/green)](https://jira.percona.com/browse/K8SPXC-373)
=> K8SPXC-373 cleanup tmp files on each Pod start

source/haproxy-conf.rst, source/index.rst, source/operator.rst, source/proxysql-conf.rst
[![K8SPXC-342](https://badgen.net/badge/JIRA/K8SPXC-342/green)](https://jira.percona.com/browse/K8SPXC-342)
=> K8SPXC-342 fix minor HAProxy related formatting issues in docs

e2e-tests/scaling/run
=> K8SPXC-356 Fix scaling test for minikube

e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-150-oc.yml
=> K8SPXC-356 Release adjustment for Openshift

source/eks.rst, source/operator.rst
[![K8SPXC-342](https://badgen.net/badge/JIRA/K8SPXC-342/green)](https://jira.percona.com/browse/K8SPXC-342)
=> K8SPXC-342 minor formatting fix for the options table

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.1.0.rst, source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.2.0.rst, source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.3.0.rst, source/architecture.rst
[![CLOUD-560](https://badgen.net/badge/JIRA/CLOUD-560/green)](https://jira.percona.com/browse/CLOUD-560)
=> CLOUD-560 fix controversial terminology in docs

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.5.0.rst, source/ReleaseNotes/index.rst, source/conf.py
[![RN-1](https://badgen.net/badge/JIRA/RN-1/green)](https://jira.percona.com/browse/RN-1)
=> RN, initial version

source/custom-registry.rst
=> K8 spxc 356 doc update followup for the release

source/update.rst
=> K8SPXC-356 hotfix forURLs in update doc

source/backups.rst, source/conf.py, source/custom-registry.rst, source/debug.rst, source/operator.rst, source/recovery.rst, source/update.rst
[![K8SPXC-376](https://badgen.net/badge/JIRA/K8SPXC-376/green)](https://jira.percona.com/browse/K8SPXC-376)
=> K8SPXC-376 update images names

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.5.0.rst
[![K8SPXC-380](https://badgen.net/badge/JIRA/K8SPXC-380/green)](https://jira.percona.com/browse/K8SPXC-380)
=> K8SPXC-380 fix the installation instructions link jirabot inserts in RN

deploy/cr.yaml
[![K8SPXC-385](https://badgen.net/badge/JIRA/K8SPXC-385/green)](https://jira.percona.com/browse/K8SPXC-385)
=> K8SPXC-385 Add example of 'configuration' for HAProxy

e2e-tests/functions
[![K8SPXC-366](https://badgen.net/badge/JIRA/K8SPXC-366/green)](https://jira.percona.com/browse/K8SPXC-366)
=> K8SPXC-366 Run cleanup of namespaces in background

source/backups.rst
[![K8SPSMDB-229](https://badgen.net/badge/JIRA/K8SPSMDB-229/green)](https://jira.percona.com/browse/K8SPSMDB-229)
=> K8SPSMDB-229 mention secret keys are base64 encoded

e2e-tests/functions, e2e-tests/restore-to-encrypted-cluster/run
[![K8SPXC-366](https://badgen.net/badge/JIRA/K8SPXC-366/green)](https://jira.percona.com/browse/K8SPXC-366)
=> K8SPXC-366 Fix installation of vault

pkg/controller/pxc/controller.go, pkg/controller/pxc/version.go, pkg/controller/pxc/vs.go
[![K8SPXC-404](https://badgen.net/badge/JIRA/K8SPXC-404/green)](https://jira.percona.com/browse/K8SPXC-404)
=> K8SPXC-404: Fix issue with cached version service URL

source/encryption.rst
[![K8SPXC-405](https://badgen.net/badge/JIRA/K8SPXC-405/green)](https://jira.percona.com/browse/K8SPXC-405)
=> K8SPXC-405 fix typo in vault doc

e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-160.yml, e2e-tests/upgrade-consistency/compare/service_some-name-pxc-160.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-160-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-160.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-160-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-160.yml, e2e-tests/upgrade-consistency/run
Missed this after 1.5.0 release.
=> K8SPXC-356 - Update e2e-tests/upgrade-consistency after 1.5.0 release

pkg/controller/pxc/users.go
[![K8SPXC-397](https://badgen.net/badge/JIRA/K8SPXC-397/green)](https://jira.percona.com/browse/K8SPXC-397)
=> K8SPXC-397 Add namespaces to connection strings

deploy/rbac.yaml, e2e-tests/functions, e2e-tests/init-deploy/compare/certificate_no-proxysql-ssl-internal.yml, e2e-tests/init-deploy/compare/certificate_no-proxysql-ssl.yml, e2e-tests/init-deploy/compare/issuer_no-proxysql-pxc-ca.yml, e2e-tests/init-deploy/run
[![K8SPXC-372](https://badgen.net/badge/JIRA/K8SPXC-372/green)](https://jira.percona.com/browse/K8SPXC-372)
since 0.11 version cert-manager has the new API Group
=> K8SPXC-372 use new cert-manager API Group

source/encryption.rst
[![K8SPXC-409](https://badgen.net/badge/JIRA/K8SPXC-409/green)](https://jira.percona.com/browse/K8SPXC-409)
=> K8SPXC-409 mention that root token is not necessary

deploy/cr.yaml
[![K8SPXC-411](https://badgen.net/badge/JIRA/K8SPXC-411/green)](https://jira.percona.com/browse/K8SPXC-411)
Comment the beginning of tls section because all it should be commented
=> Comment tls section

source/api.rst
[![CLOUD-526](https://badgen.net/badge/JIRA/CLOUD-526/green)](https://jira.percona.com/browse/CLOUD-526)
=> try to fix width

build/pxc-configure-pxc.sh, pkg/apis/pxc/v1/pxc_types.go, pkg/pxc/backup/restore.go
[![K8SPXC-438](https://badgen.net/badge/JIRA/K8SPXC-438/green)](https://jira.percona.com/browse/K8SPXC-438)
=> K8SPXC-438 add possibility to use 32 symbols for cluster name

Jenkinsfile, e2e-tests/demand-backup/conf/client.yml, e2e-tests/functions, e2e-tests/one-pod/conf/client.yml, e2e-tests/restore-to-encrypted-cluster/conf/client.yml, e2e-tests/scheduled-backup/compare/cronjob_each-min-aws-s3-oc.yml, e2e-tests/scheduled-backup/compare/cronjob_each-min-aws-s3.yml, e2e-tests/scheduled-backup/compare/cronjob_each-min-gcp-cs-oc.yml, e2e-tests/scheduled-backup/compare/cronjob_each-min-gcp-cs.yml, e2e-tests/scheduled-backup/compare/cronjob_each-min-minio-oc.yml, e2e-tests/scheduled-backup/compare/cronjob_each-min-minio.yml, e2e-tests/scheduled-backup/compare/cronjob_each-min-pvc-oc.yml, e2e-tests/scheduled-backup/compare/cronjob_each-min-pvc.yml, e2e-tests/scheduled-backup/run, e2e-tests/security-context/compare/cronjob_each-hour-pvc.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-pvc.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-s3.yml, e2e-tests/security-context/compare/pod_restore-src-restore-pvc-sec-context-oc.yml, e2e-tests/security-context/compare/pod_restore-src-restore-pvc-sec-context.yml, e2e-tests/security-context/run, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/backup.go, pkg/pxc/backup/names.go, pkg/pxc/backup/scheduled.go
[![K8SPXC-370](https://badgen.net/badge/JIRA/K8SPXC-370/green)](https://jira.percona.com/browse/K8SPXC-370)
* fix 'scheduled-backup' test
* start to use new helm repo for minio charts
=> K8SPXC-370 Fix 'scheduled-backup' test

deploy/cr.yaml
[![K8SPXC-443](https://badgen.net/badge/JIRA/K8SPXC-443/green)](https://jira.percona.com/browse/K8SPXC-443)
Update version service URL in deploy/cr.yaml
=> K8SPXC-443: Fix version service URL

e2e-tests/demand-backup/conf/restore-on-demand-backup-pvc-bsource.yaml
[![K8SPXC-370](https://badgen.net/badge/JIRA/K8SPXC-370/green)](https://jira.percona.com/browse/K8SPXC-370)
=> K8SPXC-370 Fix 'demand-backup' test

e2e-tests/demand-backup-encrypted-with-tls/conf/client.yml, e2e-tests/functions
[![K8SPXC-448](https://badgen.net/badge/JIRA/K8SPXC-448/green)](https://jira.percona.com/browse/K8SPXC-448)
=> K8SPXC-448: fix demand-backup-encrypted-with-tls test

pkg/controller/pxc/controller.go, pkg/controller/pxc/upgrade.go
[![K8SPXC-450](https://badgen.net/badge/JIRA/K8SPXC-450/green)](https://jira.percona.com/browse/K8SPXC-450)
=> K8SPXC-450 remove unneeded annotations from HAproxy pods

build/pxc-configure-pxc.sh, build/pxc-entrypoint.sh
[![K8SPXC-435](https://badgen.net/badge/JIRA/K8SPXC-435/green)](https://jira.percona.com/browse/K8SPXC-435)
=> K8SPXC-435 Do not show any passwords in log

build/Dockerfile, build/pxc-entrypoint.sh, build/pxc-init-entrypoint.sh, build/unsafe-bootstrap.sh
[![K8SPXC-423](https://badgen.net/badge/JIRA/K8SPXC-423/green)](https://jira.percona.com/browse/K8SPXC-423)
=> K8SPXC-423 Use 'peer-list' for pxc from init container

pkg/controller/pxc/controller.go, pkg/controller/pxc/upgrade.go
[![K8SPXC-454](https://badgen.net/badge/JIRA/K8SPXC-454/green)](https://jira.percona.com/browse/K8SPXC-454)
Check if certificates exist before deploying pxc cluster
=> K8SPXC-454: add certificate checks

source/recovery.rst
[![K8SPXC-440](https://badgen.net/badge/JIRA/K8SPXC-440/green)](https://jira.percona.com/browse/K8SPXC-440)
=> K8SPXC-440 improve recovery documentation

source/recovery.rst
[![K8SPXC-440](https://badgen.net/badge/JIRA/K8SPXC-440/green)](https://jira.percona.com/browse/K8SPXC-440)
=> K8SPXC-440 add minor syntax fixes

source/operator.rst, source/update.rst
[![K8SPXC-398](https://badgen.net/badge/JIRA/K8SPXC-398/green)](https://jira.percona.com/browse/K8SPXC-398)
=> K8SPXC-398 document crVersion key and its usage with upgrades

source/gke.rst, source/kubernetes.rst, source/minikube.rst, source/openshift.rst, source/users.rst
[![K8SPXC-307](https://badgen.net/badge/JIRA/K8SPXC-307/green)](https://jira.percona.com/browse/K8SPXC-307)
=> K8SPXC-307 use percona-client 8.0 version in docs

deploy/cr.yaml, pkg/controller/pxc/vs.go
[![K8SPXC-456](https://badgen.net/badge/JIRA/K8SPXC-456/green)](https://jira.percona.com/browse/K8SPXC-456)
=> K8SPXC-456: trim "/versions" in versionservice url

pkg/controller/pxc/controller.go, pkg/controller/pxc/tls.go, pkg/controller/pxc/upgrade.go
[![K8SPXC-457](https://badgen.net/badge/JIRA/K8SPXC-457/green)](https://jira.percona.com/browse/K8SPXC-457)
Test are falling because they can't find required secrets
=> K8SPXC-457: Wait for certmanager certificate issue

build/pxc-configure-pxc.sh
[![K8SPXC-420](https://badgen.net/badge/JIRA/K8SPXC-420/green)](https://jira.percona.com/browse/K8SPXC-420)
=> K8SPXC-383 fix revDNS warning

e2e-tests/haproxy/compare/statefulset_haproxy-haproxy.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-haproxy.yml, e2e-tests/self-healing/compare/proxy-vars-80.sql, e2e-tests/self-healing/compare/proxy-vars.sql, pkg/pxc/app/statefulset/haproxy.go
[![K8SPXC-462](https://badgen.net/badge/JIRA/K8SPXC-462/green)](https://jira.percona.com/browse/K8SPXC-462)
=> K8SPXC-462 add readiness probe for HAproxy

pkg/controller/pxc/controller.go
[![K8SPXC-469](https://badgen.net/badge/JIRA/K8SPXC-469/green)](https://jira.percona.com/browse/K8SPXC-469)
=> K8SPXC-469 Fix typo

source/backups.rst
[![K8SPXC-429](https://badgen.net/badge/JIRA/K8SPXC-429/green)](https://jira.percona.com/browse/K8SPXC-429)
=> K8SPXC-429 document restoring backup on different cluster

source/cluster-wide.rst, source/index.rst
[![K8SPXC-394](https://badgen.net/badge/JIRA/K8SPXC-394/green)](https://jira.percona.com/browse/K8SPXC-394)
=> K8SPXC-394 document cluster wide operation

cmd/peer-list/main.go, deploy/crd.yaml
[![K8SPXC-473](https://badgen.net/badge/JIRA/K8SPXC-473/green)](https://jira.percona.com/browse/K8SPXC-473)
Change stored version in `crd.yaml` to the actual one
=> K8SPXC-473: make current version as stored

deploy/bundle.yaml
=> K8SPXC-471 - Regenerate bundle after K8SPXC-473 fix

source/backups.rst
[![K8SPXC-429](https://badgen.net/badge/JIRA/K8SPXC-429/green)](https://jira.percona.com/browse/K8SPXC-429)
=> remove erroneously placed enabled option from yaml file example

source/helm.rst, source/index.rst
[![K8SPXC-343](https://badgen.net/badge/JIRA/K8SPXC-343/green)](https://jira.percona.com/browse/K8SPXC-343)
=> K8SPXC-343 documenting helm chart following the PSMDB Operator doc

source/haproxy-conf.rst, source/operator.rst
[![K8SPXC-416](https://badgen.net/badge/JIRA/K8SPXC-416/green)](https://jira.percona.com/browse/K8SPXC-416)
=> K8SPXC-416 describe proxy protocol in docs

source/cluster-wide.rst
[![K8SPXC-394](https://badgen.net/badge/JIRA/K8SPXC-394/green)](https://jira.percona.com/browse/K8SPXC-394)
=> add label to facilitate external refs in docs

e2e-tests/affinity/compare/statefulset_custom-pxc-oc.yml, e2e-tests/affinity/compare/statefulset_hostname-pxc-oc.yml, e2e-tests/affinity/compare/statefulset_region-pxc-oc.yml, e2e-tests/affinity/compare/statefulset_zone-pxc-oc.yml, e2e-tests/init-deploy/compare/statefulset_no-proxysql-pxc-oc.yml, e2e-tests/init-deploy/compare/statefulset_some-name-pxc-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-pxc-oc.yml, e2e-tests/security-context/compare/pod_restore-src-restore-pvc-sec-context-4-oc.yml, e2e-tests/storage/compare/statefulset_emptydir-pxc-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-160-oc.yml
=> K8SPXC-471 Fix Openshift container limits

build/readiness-check.sh
[![K8SPXC-481](https://badgen.net/badge/JIRA/K8SPXC-481/green)](https://jira.percona.com/browse/K8SPXC-481)
=> K8SPXC-481 improve readiness check for recovery process

e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-150-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-150.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-160-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-160.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-150-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-150.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-160-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-160.yml, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/pxc/app/statefulset/haproxy.go
[![K8SPXC-479](https://badgen.net/badge/JIRA/K8SPXC-479/green)](https://jira.percona.com/browse/K8SPXC-479)
=> K8SPXC-479 fix update issue

source/update.rst
Add patching haproxy image and fix crVersion patching (it was not working for some reason).
=> Fix patch command on upgrade page

source/cluster-wide.rst
[![K8SPXC-394](https://badgen.net/badge/JIRA/K8SPXC-394/green)](https://jira.percona.com/browse/K8SPXC-394)
=> K8SPXC-394 remove editing of cw-bundle.yaml from docs

source/backups.rst
[![K8SPXC-306](https://badgen.net/badge/JIRA/K8SPXC-306/green)](https://jira.percona.com/browse/K8SPXC-306)
=> K8SPXC-306 better explanation of S3 and PV backups

source/images.rst, source/recovery.rst
=> K8SPXC-471 update image hashes, recovery steps

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.6.0.rst, source/ReleaseNotes/index.rst, source/conf.py
[![RN-1](https://badgen.net/badge/JIRA/RN-1/green)](https://jira.percona.com/browse/RN-1)
=> PXC Operator 1.6.0 Release Notes

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.6.0.rst, source/haproxy-conf.rst
=> K8SPXC-471 update formatting & labels

e2e-tests/upgrade-consistency/run
=> K8SPXC-471 Replace branch with tag

pkg/controller/pxc/upgrade.go
[![K8SPXC-253](https://badgen.net/badge/JIRA/K8SPXC-253/green)](https://jira.percona.com/browse/K8SPXC-253)
=> K8SPXC-253 roll out pxc annotation updates

deploy/cr.yaml, e2e-tests/demand-backup/conf/demand-backup.yml, e2e-tests/demand-backup/conf/on-demand-backup-aws-s3.yml, e2e-tests/demand-backup/conf/on-demand-backup-gcp-cs.yml, e2e-tests/demand-backup/conf/on-demand-backup-minio.yml, e2e-tests/demand-backup/conf/on-demand-backup-pvc-bsource.yml, e2e-tests/demand-backup/conf/on-demand-backup-pvc.yml, e2e-tests/demand-backup/conf/restore-on-demand-backup-aws-s3.yaml, e2e-tests/demand-backup/conf/restore-on-demand-backup-gcp-cs.yaml, e2e-tests/demand-backup/conf/restore-on-demand-backup-minio.yaml, e2e-tests/demand-backup/conf/restore-on-demand-backup-pvc-bsource.yaml, e2e-tests/demand-backup/conf/restore-on-demand-backup-pvc.yaml, e2e-tests/demand-backup/run, e2e-tests/functions
[![K8SPXC-491](https://badgen.net/badge/JIRA/K8SPXC-491/green)](https://jira.percona.com/browse/K8SPXC-491)
=> K8SPXC-491 add XtraBackup compression for PXC 5.7

e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-170.yml, e2e-tests/upgrade-consistency/compare/service_some-name-pxc-170.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-170-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-170.yml
=> Update upgrade-consistency diff files after 1.6.0 release

deploy/cr.yaml
[![K8SPXC-500](https://badgen.net/badge/JIRA/K8SPXC-500/green)](https://jira.percona.com/browse/K8SPXC-500)
=> K8SPXC-500 use default service account for backups

deploy/cr.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/pxc/service.go
[![K8SPXC-389](https://badgen.net/badge/JIRA/K8SPXC-389/green)](https://jira.percona.com/browse/K8SPXC-389)
=> K8SPXC-389 add possibility to set service type for replicas service

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.6.0.rst
[![K8SPXC-491](https://badgen.net/badge/JIRA/K8SPXC-491/green)](https://jira.percona.com/browse/K8SPXC-491)
=> K8SPXC-491 mention limitation with compressed backups

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go
[![K8SPXC-503](https://badgen.net/badge/JIRA/K8SPXC-503/green)](https://jira.percona.com/browse/K8SPXC-503)
=> K8SPXC-503 Added init container image to spec

source/encryption.rst
[![K8SPXC-516](https://badgen.net/badge/JIRA/K8SPXC-516/green)](https://jira.percona.com/browse/K8SPXC-516)
=> K8SPXC-516 mention Vault is needed for default PXC encrytption

pkg/controller/pxc/version.go
[![K8SPXC-517](https://badgen.net/badge/JIRA/K8SPXC-517/green)](https://jira.percona.com/browse/K8SPXC-517)
=> K8SPXC-517 fix crash on missing backup section

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.6.0.rst, source/haproxy-conf.rst
[![K8SPXC-416](https://badgen.net/badge/JIRA/K8SPXC-416/green)](https://jira.percona.com/browse/K8SPXC-416)
=> K8SPXC-416 mention Proxy potocol needs compatible PXC version

pkg/controller/pxc/controller.go
[![K8SPXC-502](https://badgen.net/badge/JIRA/K8SPXC-502/green)](https://jira.percona.com/browse/K8SPXC-502)
=> K8SPXC-502 add annotations only if ssl hash is not empty

deploy/bundle.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
[![K8SPXC-343](https://badgen.net/badge/JIRA/K8SPXC-343/green)](https://jira.percona.com/browse/K8SPXC-343)
=> K8SPXC-343 unify and beautify operator deployment

e2e-tests/operator-self-healing/conf/pumba.yml, e2e-tests/upgrade/run, pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-510](https://badgen.net/badge/JIRA/K8SPXC-510/green)](https://jira.percona.com/browse/K8SPXC-510)
=> K8SPXC-510 Use ENV variables for images

Jenkinsfile, e2e-tests/affinity/run, e2e-tests/demand-backup-encrypted-with-tls/run, e2e-tests/functions, e2e-tests/restore-to-encrypted-cluster/run, e2e-tests/scheduled-backup/run, e2e-tests/upgrade/run
[![K8SPXC-524](https://badgen.net/badge/JIRA/K8SPXC-524/green)](https://jira.percona.com/browse/K8SPXC-524)
=> K8SPXC-524 cleanup cluster wide operator correctly after the test

source/debug.rst
[![K8SPXC-445](https://badgen.net/badge/JIRA/K8SPXC-445/green)](https://jira.percona.com/browse/K8SPXC-445)
=> K8SPXC-445 mention debug images are for PXC only

pkg/controller/pxc/controller.go, pkg/controller/pxc/upgrade.go, pkg/pxc/statefulset.go
[![K8SPXC-523](https://badgen.net/badge/JIRA/K8SPXC-523/green)](https://jira.percona.com/browse/K8SPXC-523)
=> K8SPXC-523 Fix annotations merge

source/faq.rst, source/index.rst
[![K8SPXC-504](https://badgen.net/badge/JIRA/K8SPXC-504/green)](https://jira.percona.com/browse/K8SPXC-504)
=> K8SPXC-504 create faq

deploy/secrets.yaml
[![K8SPXC-551](https://badgen.net/badge/JIRA/K8SPXC-551/green)](https://jira.percona.com/browse/K8SPXC-551)
Since some users struggle to operate with base64 tool
we are switching to plaintext mode
=> K8SPXC-551 Use plaintext user secret

e2e-tests/conf/some-name.yml, e2e-tests/functions, e2e-tests/init-deploy/compare/statefulset_some-name-pxc.yml, e2e-tests/init-deploy/run, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-170.yml, e2e-tests/users/run, pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-485](https://badgen.net/badge/JIRA/K8SPXC-485/green)](https://jira.percona.com/browse/K8SPXC-485)
K8SPXC-531 - fix operator-self-healing test
=> K8SPXC-485 Add test for logcollector

source/kubernetes.rst, source/openshift.rst, source/users.rst
[![K8SPXC-551](https://badgen.net/badge/JIRA/K8SPXC-551/green)](https://jira.percona.com/browse/K8SPXC-551)
Since we've switched to stringData secret format, related docs
should be updated.
=> K8SPXC-551 Doc update for secret update

e2e-tests/functions
[![CLOUD-596](https://badgen.net/badge/JIRA/CLOUD-596/green)](https://jira.percona.com/browse/CLOUD-596)
=> CLOUD-596 Use the same minio version as psmdb

pkg/controller/pxc/backup.go, pkg/controller/pxc/controller.go
[![K8SPXC-546](https://badgen.net/badge/JIRA/K8SPXC-546/green)](https://jira.percona.com/browse/K8SPXC-546)
Update configmap only if it's changed to reduce number of unneeded updates
=> K8SPXC-546: reduce number of configmaps update

source/recovery.rst
[![K8SPXC-563](https://badgen.net/badge/JIRA/K8SPXC-563/green)](https://jira.percona.com/browse/K8SPXC-563)
=> K8SPXC-563 update recovery doc

pkg/controller/pxc/version.go
[![K8SPXC-521](https://badgen.net/badge/JIRA/K8SPXC-521/green)](https://jira.percona.com/browse/K8SPXC-521)
=> K8SPXC-521: Delete job if cluster was not found

pkg/controller/pxc/controller.go, pkg/controller/pxc/version.go
[![K8SPXC-526](https://badgen.net/badge/JIRA/K8SPXC-526/green)](https://jira.percona.com/browse/K8SPXC-526)
This PS also should fix this bug
https://jira.percona.com/browse/K8SPXC-520
=> K8SPXC-526: Make smart update work with multiple clusters

e2e-tests/haproxy/compare/statefulset_haproxy-haproxy.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-haproxy.yml, e2e-tests/security-context/compare/job.batch_restore-job-restore-s3-sec-context.yml, e2e-tests/upgrade-haproxy/compare/statefulset_upgrade-haproxy-haproxy.yml, pkg/pxc/app/statefulset/haproxy.go
[![K8SPXC-544](https://badgen.net/badge/JIRA/K8SPXC-544/green)](https://jira.percona.com/browse/K8SPXC-544)
=> K8SPXC-544 add liveness probe for haproxy

build/pxc-entrypoint.sh
[![K8SPXC-566](https://badgen.net/badge/JIRA/K8SPXC-566/green)](https://jira.percona.com/browse/K8SPXC-566)
=> K8SPXC-566 fix grep patern

deploy/csv/redhat/1.6.0/manifests/percona-xtradb-cluster-operator.v1.6.0.clusterserviceversion.yaml, deploy/csv/redhat/1.6.0/tests/scorecard/config.yaml, deploy/csv/redhat/bundle-1.6.0.Dockerfile
[![K8SPXC-510](https://badgen.net/badge/JIRA/K8SPXC-510/green)](https://jira.percona.com/browse/K8SPXC-510)
=> K8SPXC-510 ENV variables for offline operator

e2e-tests/functions, e2e-tests/limits/compare/statefulset_no-limits-proxysql-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-proxysql-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-170-oc.yml, e2e-tests/upgrade-haproxy/compare/statefulset_upgrade-haproxy-pxc-oc.yml
[![K8SPXC-586](https://badgen.net/badge/JIRA/K8SPXC-586/green)](https://jira.percona.com/browse/K8SPXC-586) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Some new functionality requires compare file updates
=> K8SPXC-586 File updates

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.3.0.rst, source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.4.0.rst, source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.5.0.rst, source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.6.0.rst
[![CLOUD-562](https://badgen.net/badge/JIRA/CLOUD-562/green)](https://jira.percona.com/browse/CLOUD-562)
=> CLOUD-562 add links to autogenerated RN to genindex

e2e-tests/monitoring-2-0/run, e2e-tests/upgrade-proxysql/compare/statefulset_upgrade-proxysql-pxc-oc.yml
[![K8SPXC-586](https://badgen.net/badge/JIRA/K8SPXC-586/green)](https://jira.percona.com/browse/K8SPXC-586) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
- Monitoring 2.0 test was adapted for openshift and latest PMM server
- Upgrade proxysql test was updated with missing file for openshift
=> K8SPXC-586 Some tests fixes

cmd/pitr/collector/collector.go, cmd/pitr/recoverer/recoverer.go, pkg/pxc/app/deployment/binlog-collector.go
[![K8SPXC-572](https://badgen.net/badge/JIRA/K8SPXC-572/green)](https://jira.percona.com/browse/K8SPXC-572) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-572 Add default aws endpoints

Jenkinsfile, cmd/pitr/collector/collector.go, pkg/pxc/app/deployment/binlog-collector.go
[![K8SPXC-582](https://badgen.net/badge/JIRA/K8SPXC-582/green)](https://jira.percona.com/browse/K8SPXC-582) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-582 Mount password into pitr pod

deploy/backup/restore.yaml, deploy/cr.yaml
[![K8SPXC-133](https://badgen.net/badge/JIRA/K8SPXC-133/green)](https://jira.percona.com/browse/K8SPXC-133) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-133 - Add template for PITR backup/restore

source/System-Requirements.rst, source/TLS.rst, source/api.rst, source/architecture.rst, source/backups.rst, source/encryption.rst, source/faq.rst, source/haproxy-conf.rst, source/kubernetes.rst, source/minikube.rst, source/openshift.rst, source/operator.rst, source/options.rst, source/pause.rst, source/proxysql-conf.rst, source/recovery.rst, source/update.rst, source/users.rst
[![CLOUD-577](https://badgen.net/badge/JIRA/CLOUD-577/green)](https://jira.percona.com/browse/CLOUD-577) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-577 remove pxc abbreviations from docs

e2e-tests/upgrade-proxysql/compare/statefulset_upgrade-proxysql-proxysql-oc.yml
[![K8SPXC-587](https://badgen.net/badge/JIRA/K8SPXC-587/green)](https://jira.percona.com/browse/K8SPXC-587) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-587 Add file missing for openshift

pkg/pxc/app/config/autotune.go
[![K8SPXC-490](https://badgen.net/badge/JIRA/K8SPXC-490/green)](https://jira.percona.com/browse/K8SPXC-490) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-490 - improve error message when not enough mem

deploy/cr.yaml, e2e-tests/validation-hook/conf/cr-with-haproxy-and-proxysql.yaml, e2e-tests/validation-hook/conf/cr-with-no-storage.yaml, e2e-tests/validation-hook/conf/cr-with-too-long-name.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/webhook/hook.go
[![K8SPXC-595](https://badgen.net/badge/JIRA/K8SPXC-595/green)](https://jira.percona.com/browse/K8SPXC-595) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Change disableHookValidation field in cr
=> K8SPXC-595: Change disableHookValidation field in cr

e2e-tests/monitoring-2-0/run
[![CLOUD-605](https://badgen.net/badge/JIRA/CLOUD-605/green)](https://jira.percona.com/browse/CLOUD-605) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Victoria metrics persistance added
=> CLOUD-605 PMM server chart version upgrade

cmd/pitr/recoverer/recoverer.go
[![K8SPXC-572](https://badgen.net/badge/JIRA/K8SPXC-572/green)](https://jira.percona.com/browse/K8SPXC-572) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-572 Add defaults to recover

e2e-tests/self-healing/compare/proxy-vars-80.sql, e2e-tests/self-healing/compare/proxy-vars.sql, pkg/webhook/hook.go
[![K8SPXC-604](https://badgen.net/badge/JIRA/K8SPXC-604/green)](https://jira.percona.com/browse/K8SPXC-604) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Set operator deployment as webhook owner to make it automatically deleted when operator is removed
=> K8SPXC-604: add owner references to webhook

source/operator.rst
[![K8SPXC-299](https://badgen.net/badge/JIRA/K8SPXC-299/green)](https://jira.percona.com/browse/K8SPXC-299)
=> K8SPXC-299 clarify unsafe configurations

source/index.rst, source/monitoring.rst
[![K8SPXC-497](https://badgen.net/badge/JIRA/K8SPXC-497/green)](https://jira.percona.com/browse/K8SPXC-497) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-497 add PMM doc

build/pxc-configure-pxc.sh
[![K8SPXC-607](https://badgen.net/badge/JIRA/K8SPXC-607/green)](https://jira.percona.com/browse/K8SPXC-607) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-607 enable libcoredumper for PXCO

e2e-tests/self-healing/compare/proxy-vars-80.sql, e2e-tests/self-healing/compare/proxy-vars.sql
This reverts commit 55b5b230a3bd97bd180227331da524d4bbb4243a.
=> Revert "rollback proxysql"

source/operator.rst
[![K8SPXC-567](https://badgen.net/badge/JIRA/K8SPXC-567/green)](https://jira.percona.com/browse/K8SPXC-567) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-567 remove forceUnsafeBootstrap option from docs

source/debug.rst, source/operator.rst
[![K8SPXC-485](https://badgen.net/badge/JIRA/K8SPXC-485/green)](https://jira.percona.com/browse/K8SPXC-485) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-485 document log collector

cmd/pitr/pxc/pxc.go
[![K8SPXC-610](https://badgen.net/badge/JIRA/K8SPXC-610/green)](https://jira.percona.com/browse/K8SPXC-610) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-610 Change host selection

e2e-tests/conf/sysbench-tpcc.yaml
[![K8SPXC-460](https://badgen.net/badge/JIRA/K8SPXC-460/green)](https://jira.percona.com/browse/K8SPXC-460) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-460 add TPCC-like workload pod

e2e-tests/monitoring-2-0/run
[![K8SPXC-608](https://badgen.net/badge/JIRA/K8SPXC-608/green)](https://jira.percona.com/browse/K8SPXC-608) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
In cluster wide mode, there was an error which didn't allow
pmm to start up
=> K8SPXC-608 Fixing cluster wide openshift configuration

source/faq.rst
[![K8SPXC-518](https://badgen.net/badge/JIRA/K8SPXC-518/green)](https://jira.percona.com/browse/K8SPXC-518) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-518 document core dumps

pkg/controller/pxc/upgrade.go
[![K8SPXC-545](https://badgen.net/badge/JIRA/K8SPXC-545/green)](https://jira.percona.com/browse/K8SPXC-545) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-545: Update imagePullSecrets

pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-558](https://badgen.net/badge/JIRA/K8SPXC-558/green)](https://jira.percona.com/browse/K8SPXC-558) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-558: Add log message about safe configuration

source/helm.rst
[![CLOUD-604](https://badgen.net/badge/JIRA/CLOUD-604/green)](https://jira.percona.com/browse/CLOUD-604) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Cloud 604 remove helm2 from docs

source/operator.rst, source/recovery.rst
[![K8SPXC-567](https://badgen.net/badge/JIRA/K8SPXC-567/green)](https://jira.percona.com/browse/K8SPXC-567) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-567 update crash recovery doc and add relevant option

source/backups.rst
[![K8SPXC-530](https://badgen.net/badge/JIRA/K8SPXC-530/green)](https://jira.percona.com/browse/K8SPXC-530) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-530 mention PITR and backup compression can't be used together

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.7.0.rst, source/backups.rst, source/faq.rst, source/haproxy-conf.rst, source/images.rst, source/operator.rst, source/proxysql-conf.rst, source/update.rst
[![RN-1](https://badgen.net/badge/JIRA/RN-1/green)](https://jira.percona.com/browse/RN-1) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Release 1.7.0 addons

go.mod, pkg/controller/pxc/controller.go, pkg/controller/pxc/full_crash_recovery.go, pkg/controller/pxc/upgrade.go, pkg/controller/pxc/version.go
[![K8SPXC-519](https://badgen.net/badge/JIRA/K8SPXC-519/green)](https://jira.percona.com/browse/K8SPXC-519) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Add cluster name and namespace to log messages
Refactor errors
=> K8SPXC-519: operator logs improvements

source/monitoring.rst
- `admin` is the default user for pmm v2
- pmmserver is the correct secret that we need to set in k8s Secret.
=> minor fix in the monitoring doc

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/controller/pxc/upgrade.go, pkg/controller/pxc/version.go, pkg/controller/pxcbackup/controller.go, pkg/controller/pxcrestore/controller.go
Fix logging issues, because project is not building
=> fix logging

build/liveness-check.sh, build/readiness-check.sh
[![K8SPXC-596](https://badgen.net/badge/JIRA/K8SPXC-596/green)](https://jira.percona.com/browse/K8SPXC-596) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-596 improve mysql connection timeouts for liveness/readiness checks

build/pxc-entrypoint.sh
[![K8SPXC-637](https://badgen.net/badge/JIRA/K8SPXC-637/green)](https://jira.percona.com/browse/K8SPXC-637) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-637 improve crash recovery message

source/backups.rst
[![K8SPXC-636](https://badgen.net/badge/JIRA/K8SPXC-636/green)](https://jira.percona.com/browse/K8SPXC-636) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-636 fix wrong line removal

source/operator.rst
[![K8SPXC-640](https://badgen.net/badge/JIRA/K8SPXC-640/green)](https://jira.percona.com/browse/K8SPXC-640) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-640 wrong doc

build/liveness-check.sh
[![K8SPXC-643](https://badgen.net/badge/JIRA/K8SPXC-643/green)](https://jira.percona.com/browse/K8SPXC-643) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* detect split-brain conditions and restart the node to
perform auto recovery
=> K8SPXC-643 restart node if it has non-Primary state

source/TLS.rst
[![K8SPXC-655](https://badgen.net/badge/JIRA/K8SPXC-655/green)](https://jira.percona.com/browse/K8SPXC-655) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-655 fix typo in TLS doc, PXC version

cmd/pitr/collector/collector.go
[![K8SPXC-631](https://badgen.net/badge/JIRA/K8SPXC-631/green)](https://jira.percona.com/browse/K8SPXC-631) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-631 Add errors handling to collector

build/liveness-check.sh, build/readiness-check.sh, e2e-tests/big-data/conf/backup.yml
[![K8SPXC-654](https://badgen.net/badge/JIRA/K8SPXC-654/green)](https://jira.percona.com/browse/K8SPXC-654) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* start using admin port for liveness/readiness probs
to be able to connect to DB in case of 'Too many connections'
issue
=> K8SPXC-654 use admin port for liveness/readiness probs

e2e-tests/big-data/run, e2e-tests/demand-backup-encrypted-with-tls/run, e2e-tests/demand-backup/run, e2e-tests/functions, e2e-tests/one-pod/run, e2e-tests/pitr/run, e2e-tests/restore-to-encrypted-cluster/run, e2e-tests/scheduled-backup/run, e2e-tests/security-context/run
=> K8SPXC-622 add possibility of skipping backups to aws/gcp S3 storage

CONTRIBUTING.md, code-of-conduct.md
=> K8SPXC-622 add contributing guide

CONTRIBUTING.md
=> K8SPXC-622 minor polish in contributing guide

Jenkinsfile, e2e-tests/license/compare/go-licenses, e2e-tests/license/compare/license-detector
[![CLOUD-615](https://badgen.net/badge/JIRA/CLOUD-615/green)](https://jira.percona.com/browse/CLOUD-615) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-615 rework license check

.github/linters/go.mod, .github/workflows/reviewdog.yml, .reviewdog.yml, build/Dockerfile
[![CLOUD-616](https://badgen.net/badge/JIRA/CLOUD-616/green)](https://jira.percona.com/browse/CLOUD-616) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
check code automatically with the following linters:
* golangci-lint
* go-consistent
* gofmt
* shfmt
* shellcheck
* misspell
* alex (insensitive, inconsiderate wording)
=> CLOUD-616 run linters automatically on each PR

e2e-tests/functions
=> K8SPXC-622 set 'SKIP_BACKUPS_TO_AWS_GCP=1' by default

e2e-tests/README.md
=> K8SPXC-622 update doc on tests

pkg/controller/pxc/controller.go, pkg/controller/pxc/upgrade.go
[![K8SPXC-619](https://badgen.net/badge/JIRA/K8SPXC-619/green)](https://jira.percona.com/browse/K8SPXC-619) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-619 Add tolerations to PXC pod

.github/workflows/reviewdog.yml, .reviewdog.yml, e2e-tests/users/run, pkg/controller/pxc/users.go
[![K8SPXC-641](https://badgen.net/badge/JIRA/K8SPXC-641/green)](https://jira.percona.com/browse/K8SPXC-641) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=>  K8SPXC-641 Update proxy users on each node

.github/workflows/reviewdog.yml, build/Dockerfile, cmd/manager/main.go, e2e-tests/build, e2e-tests/functions, e2e-tests/security-context/compare/cronjob_adc5a-each-hour-pvc.yml, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/pxc/statefulset.go
[![K8SPXC-576](https://badgen.net/badge/JIRA/K8SPXC-576/green)](https://jira.percona.com/browse/K8SPXC-576) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-576: Fix custom labels

build/pxc-configure-pxc.sh
[![K8SPXC-573](https://badgen.net/badge/JIRA/K8SPXC-573/green)](https://jira.percona.com/browse/K8SPXC-573) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-573 escaped special symbols for 'XTRABACKUP_PASSWORD'

pkg/controller/pxcbackup/controller.go
[![K8SPXC-675](https://badgen.net/badge/JIRA/K8SPXC-675/green)](https://jira.percona.com/browse/K8SPXC-675) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-675: Fix returning of nil error

pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-681](https://badgen.net/badge/JIRA/K8SPXC-681/green)](https://jira.percona.com/browse/K8SPXC-681) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-681 Add validation for backup.pitr.storageName field

cmd/pitr/storage/storage.go
[![K8SPXC-684](https://badgen.net/badge/JIRA/K8SPXC-684/green)](https://jira.percona.com/browse/K8SPXC-684) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-684 Trim '/' from endpoint URL

source/faq.rst
[![K8SPXC-693](https://badgen.net/badge/JIRA/K8SPXC-693/green)](https://jira.percona.com/browse/K8SPXC-693) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-693 custom sidecar containers

Jenkinsfile, e2e-tests/functions, e2e-tests/haproxy/conf/container-rc.yaml, e2e-tests/haproxy/run
[![K8SPXC-699](https://badgen.net/badge/JIRA/K8SPXC-699/green)](https://jira.percona.com/browse/K8SPXC-699) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-699 fix container runtime

source/backups.rst
[![K8SPXC-624](https://badgen.net/badge/JIRA/K8SPXC-624/green)](https://jira.percona.com/browse/K8SPXC-624) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-624 mention tthat purging binlogs before backup breaks PITR

source/backups.rst
[![K8SPXC-695](https://badgen.net/badge/JIRA/K8SPXC-695/green)](https://jira.percona.com/browse/K8SPXC-695) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-695 PITR improvements

source/faq.rst
[![K8SPXC-574](https://badgen.net/badge/JIRA/K8SPXC-574/green)](https://jira.percona.com/browse/K8SPXC-574) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-574 add haproxy vs proxysql to faq

source/update.rst
[![K8SPXC-696](https://badgen.net/badge/JIRA/K8SPXC-696/green)](https://jira.percona.com/browse/K8SPXC-696) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-696 smart update updates

source/scaling.rst
[![K8SPXC-692](https://badgen.net/badge/JIRA/K8SPXC-692/green)](https://jira.percona.com/browse/K8SPXC-692) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-692 document horizontal scaling

deploy/cr.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/controller/pxc/upgrade.go, pkg/pxc/app/statefulset/haproxy.go, pkg/pxc/app/statefulset/node.go, pkg/pxc/app/statefulset/proxysql.go
[![K8SPXC-688](https://badgen.net/badge/JIRA/K8SPXC-688/green)](https://jira.percona.com/browse/K8SPXC-688) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-688 Add possibility of defining env variables via CR

e2e-tests/self-healing/compare/proxy-vars-80.sql, pkg/controller/pxc/controller.go
[![K8SPXC-585](https://badgen.net/badge/JIRA/K8SPXC-585/green)](https://jira.percona.com/browse/K8SPXC-585) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-585 Move users logic after delete

deploy/backup/backup.yaml, pkg/controller/pxcbackup/controller.go
[![K8SPSMDB-431](https://badgen.net/badge/JIRA/K8SPSMDB-431/green)](https://jira.percona.com/browse/K8SPSMDB-431) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-431: Add finalizer to on-demand backup spec

e2e-tests/limits/compare/statefulset_no-limits-pxc-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-increased.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc.yml, pkg/controller/pxc/controller.go, pkg/pxc/app/statefulset/init.go
[![K8SPXC-656](https://badgen.net/badge/JIRA/K8SPXC-656/green)](https://jira.percona.com/browse/K8SPXC-656) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-656 Use PXC ImagePullPolicy for init containers

pkg/controller/pxcbackup/controller.go
[![K8SPXC-710](https://badgen.net/badge/JIRA/K8SPXC-710/green)](https://jira.percona.com/browse/K8SPXC-710) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Remove trailing slash in backup endpoint

pkg/controller/pxc/upgrade.go
[![K8SPXC-642](https://badgen.net/badge/JIRA/K8SPXC-642/green)](https://jira.percona.com/browse/K8SPXC-642) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-642: Update labels in sts template

Jenkinsfile, e2e-tests/self-healing/compare/proxy-vars-80.sql
[![K8SPXC-630](https://badgen.net/badge/JIRA/K8SPXC-630/green)](https://jira.percona.com/browse/K8SPXC-630) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-630 improve testing infra

ADOPTERS.md, adopters/example/README.md, adopters/users/spron-in/README.md
[![K8SPXC-722](https://badgen.net/badge/JIRA/K8SPXC-722/green)](https://jira.percona.com/browse/K8SPXC-722) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-722 init adopters commit

deploy/backup/backup.yaml
[![K8SPXC-726](https://badgen.net/badge/JIRA/K8SPXC-726/green)](https://jira.percona.com/browse/K8SPXC-726) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Comment delete-s3-backup finalizer because K8SPXC-726

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.8.0.rst, source/TLS.rst, source/api.rst, source/monitoring.rst, source/operator.rst
[![K8SPXC-674](https://badgen.net/badge/JIRA/K8SPXC-674/green)](https://jira.percona.com/browse/K8SPXC-674) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-674 minor release-related updates

pkg/pxc/app/pmm.go, pkg/pxc/app/statefulset/haproxy.go
[![K8SPXC-673](https://badgen.net/badge/JIRA/K8SPXC-673/green)](https://jira.percona.com/browse/K8SPXC-673) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-673: Add PMM client sidecar to HAProxy statefulset

pkg/controller/pxcbackup/controller.go
[![K8SPXC-726](https://badgen.net/badge/JIRA/K8SPXC-726/green)](https://jira.percona.com/browse/K8SPXC-726) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-726: Extra checks for backup finalizer

pkg/controller/pxc/controller.go
[![K8SPXC-511](https://badgen.net/badge/JIRA/K8SPXC-511/green)](https://jira.percona.com/browse/K8SPXC-511) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-511: Delete secrets on PVC finalizer

source/System-Requirements.rst, source/conf.py, source/gke.rst
[![K8PXC-736](https://badgen.net/badge/JIRA/K8PXC-736/green)](https://jira.percona.com/browse/K8PXC-736) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8PXC-736 automate gke versions update in docs

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/controller/pxc/upgrade.go, pkg/pxc/app/statefulset/haproxy.go, pkg/pxc/app/statefulset/node.go, pkg/pxc/app/statefulset/proxysql.go, pkg/pxc/statefulset.go
[![K8SPXC-657](https://badgen.net/badge/JIRA/K8SPXC-657/green)](https://jira.percona.com/browse/K8SPXC-657) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-657
Modified volume mounting to be able to set custom configuration for mysqld, HAProxy, and ProxySQL by creating Secret objects
=> K8SPXC-657 feature: Store custom configuration in Secrets

source/index.rst
[![CLOUD-623](https://badgen.net/badge/JIRA/CLOUD-623/green)](https://jira.percona.com/browse/CLOUD-623) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-623 add PXC and PXCO intro and link to the index page

Jenkinsfile
[![K8SPXC-630](https://badgen.net/badge/JIRA/K8SPXC-630/green)](https://jira.percona.com/browse/K8SPXC-630) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-630 fix cluster deletion

docs/architecture/README.md, docs/architecture/decisions/0001-record-architecture-decisions.md, docs/architecture/decisions/index.md, docs/architecture/decisions/template.md
[![CLOUD-622](https://badgen.net/badge/JIRA/CLOUD-622/green)](https://jira.percona.com/browse/CLOUD-622) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-622 add examples of architecture decision records

.github/workflows/reviewdog.yml, deploy/backup/copy-backup.sh
[![K8SPXC-697](https://badgen.net/badge/JIRA/K8SPXC-697/green)](https://jira.percona.com/browse/K8SPXC-697) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-697 fix tabulation

build/pxc-entrypoint.sh
[![K8SPXC-757](https://badgen.net/badge/JIRA/K8SPXC-757/green)](https://jira.percona.com/browse/K8SPXC-757) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-757 prevent mysql update in case of manual recovery process

deploy/csv/redhat/1.8.0/manifests/percona-xtradb-cluster-operator.v1.8.0.clusterserviceversion.yaml, deploy/csv/redhat/1.8.0/manifests/perconaxtradbbackups.pxc.percona.com.crd.yaml, deploy/csv/redhat/1.8.0/manifests/perconaxtradbclusterbackups.pxc.percona.com.crd.yaml, deploy/csv/redhat/1.8.0/manifests/perconaxtradbclusterrestores.pxc.percona.com.crd.yaml, deploy/csv/redhat/1.8.0/manifests/perconaxtradbclusters.pxc.percona.com.crd.yaml, deploy/csv/redhat/1.8.0/metadata/annotations.yaml, deploy/csv/redhat/1.8.0/tests/scorecard/config.yaml, deploy/csv/redhat/bundle-1.8.0.Dockerfile
[![K8SPXC-674](https://badgen.net/badge/JIRA/K8SPXC-674/green)](https://jira.percona.com/browse/K8SPXC-674) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-674 RedHat certification files

source/operator.rst
[![K8SPXC-740](https://badgen.net/badge/JIRA/K8SPXC-740/green)](https://jira.percona.com/browse/K8SPXC-740) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-740 mention cluster name limitations

e2e-tests/haproxy/compare/service_haproxy-proxysql.yml, e2e-tests/init-deploy/compare/service_some-name-proxysql.yml, e2e-tests/proxysql-sidecar-res-limits/compare/service_side-car-proxysql.yml, e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-100.yml, e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-110.yml, e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-120.yml, e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-130.yml, e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-140.yml, e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-150.yml, e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-160.yml, e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-170.yml, e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-180.yml, e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-190.yml, pkg/controller/pxc/controller.go, pkg/pxc/pdb.go
[![K8SPXC-554](https://badgen.net/badge/JIRA/K8SPXC-554/green)](https://jira.percona.com/browse/K8SPXC-554) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-554: improve object updates

pkg/pxc/app/config/autotune.go
[![K8SPXC-682](https://badgen.net/badge/JIRA/K8SPXC-682/green)](https://jira.percona.com/browse/K8SPXC-682) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-682: Adjust innodb_buffer_pool_chunk_size to respect memory limit

pkg/controller/pxc/controller.go
[![K8SPXC-765](https://badgen.net/badge/JIRA/K8SPXC-765/green)](https://jira.percona.com/browse/K8SPXC-765) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-765
=> K8SPXC-765: add ConfigMaps deletion for custom configurations

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/status.go, pkg/controller/pxc/status_test.go, pkg/pxc/app/statefulset/haproxy.go, pkg/pxc/app/statefulset/node.go, pkg/pxc/app/statefulset/proxysql.go
[![K8SPXC-336](https://badgen.net/badge/JIRA/K8SPXC-336/green)](https://jira.percona.com/browse/K8SPXC-336) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-336: Refactor status handling

pkg/controller/pxcbackup/controller.go
[![K8SPXC-767](https://badgen.net/badge/JIRA/K8SPXC-767/green)](https://jira.percona.com/browse/K8SPXC-767) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
The test was falling because of wrong error handling inside backups reconcile function. It also lead to the wrong behavior of controller function. Now it looks better, and works better =)
=> K8SPXC-767: fix one pod test

e2e-tests/functions, e2e-tests/operator-self-healing-chaos/run, e2e-tests/self-healing-advanced-chaos/run, e2e-tests/self-healing-chaos/run
[![CLOUD-625](https://badgen.net/badge/JIRA/CLOUD-625/green)](https://jira.percona.com/browse/CLOUD-625) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-625 - Update for chaos-mesh tests for non-cluster wide run

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/status.go
[![K8SPXC-731](https://badgen.net/badge/JIRA/K8SPXC-731/green)](https://jira.percona.com/browse/K8SPXC-731) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-731: Add progress visibility to CR

source/operator.rst
[![K8SPXC-740](https://badgen.net/badge/JIRA/K8SPXC-740/green)](https://jira.percona.com/browse/K8SPXC-740) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-740 addon for cluster name limitations

source/recovery.rst
[![K8SPXC-757](https://badgen.net/badge/JIRA/K8SPXC-757/green)](https://jira.percona.com/browse/K8SPXC-757) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-757 fix recovery documentation

build/pxc-entrypoint.sh
[![K8SPXC-775](https://badgen.net/badge/JIRA/K8SPXC-775/green)](https://jira.percona.com/browse/K8SPXC-775) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-775 check custom mysqld config

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/controller/pxc/status.go, pkg/controller/pxc/status_test.go, pkg/controller/pxc/upgrade.go
[![K8SPXC-730](https://badgen.net/badge/JIRA/K8SPXC-730/green)](https://jira.percona.com/browse/K8SPXC-730) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This commit introduces two new statuses:
1. Stopping (cluster is being paused or deleted)
2. Paused (cluster is paused *completely*)
=> K8SPXC-730: Rework statuses for the Custom Resource

deploy/cr.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/controller/pxc/replication.go, pkg/controller/pxc/upgrade.go
[![K8SPXC-308](https://badgen.net/badge/JIRA/K8SPXC-308/green)](https://jira.percona.com/browse/K8SPXC-308) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-308: add service per pod functionality

e2e-tests/monitoring-2-0/run
[![K8SPXC-673](https://badgen.net/badge/JIRA/K8SPXC-673/green)](https://jira.percona.com/browse/K8SPXC-673) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-673: Check haproxy metrics in monitoring-2-0

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxcbackup/controller.go
[![K8SPXC-764](https://badgen.net/badge/JIRA/K8SPXC-764/green)](https://jira.percona.com/browse/K8SPXC-764) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-764: Allow backups even if just a single node is available

build/liveness-check.sh, build/pxc-entrypoint.sh, build/readiness-check.sh
[![K8SPXC-791](https://badgen.net/badge/JIRA/K8SPXC-791/green)](https://jira.percona.com/browse/K8SPXC-791) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-791 allow "sleep infinity" on non-debug images

pkg/controller/pxc/upgrade.go
[![K8SPXC-787](https://badgen.net/badge/JIRA/K8SPXC-787/green)](https://jira.percona.com/browse/K8SPXC-787) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Now, we fetch new sfs revision before doing smart upgrade, because before we can stuck with old revision, while pod already got new one
=> K8SPXC-787: fix smart upgrade

deploy/bundle.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml
[![K8SPXC-798](https://badgen.net/badge/JIRA/K8SPXC-798/green)](https://jira.percona.com/browse/K8SPXC-798) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-798 fix typo

pkg/controller/pxcbackup/controller.go, vendor/k8s.io/apimachinery/pkg/util/rand/rand.go, vendor/k8s.io/client-go/testing/actions.go, vendor/k8s.io/client-go/testing/fake.go, vendor/k8s.io/client-go/testing/fixture.go, vendor/k8s.io/client-go/util/retry/OWNERS, vendor/k8s.io/client-go/util/retry/util.go, vendor/modules.txt, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go, vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
[![K8SPXC-800](https://badgen.net/badge/JIRA/K8SPXC-800/green)](https://jira.percona.com/browse/K8SPXC-800) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Add retry to s3 backup deletion. If it fails, we just delete k8s object and inform user that we can't delete backup from s3
=> K8SPXC-800: fix stale backup due to finalizer

e2e-tests/functions
=> K8SPXC-808 - Fix cleanup of previous chaos-mesh installation

deploy/bundle.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml
[![K8SPXC-798](https://badgen.net/badge/JIRA/K8SPXC-798/green)](https://jira.percona.com/browse/K8SPXC-798) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-811 fix haproxy status

source/operator.rst
[![K8SPXC-740](https://badgen.net/badge/JIRA/K8SPXC-740/green)](https://jira.percona.com/browse/K8SPXC-740) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-740 cluster name limitations wording fix

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/status.go
[![K8SPXC-815](https://badgen.net/badge/JIRA/K8SPXC-815/green)](https://jira.percona.com/browse/K8SPXC-815) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-815: Fix status ready count on downscale

source/operator.rst
[![K8SPXC-569](https://badgen.net/badge/JIRA/K8SPXC-569/green)](https://jira.percona.com/browse/K8SPXC-569) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-569 update unsafe configuration option

e2e-tests/monitoring-2-0/run
=> K8SPXC-808 - Update PMM version in monitoring test to 2.18

e2e-tests/self-healing-chaos/compare/proxy-vars-80.sql, e2e-tests/self-healing-chaos/compare/proxy-vars.sql, e2e-tests/self-healing/compare/proxy-vars-80.sql, e2e-tests/self-healing/compare/proxy-vars.sql
=> K8SPXC-808 - Fix self-healing tests for ProxySQL version

e2e-tests/one-pod/compare/statefulset_one-pod-pxc-oc.yml, e2e-tests/one-pod/compare/statefulset_one-pod-pxc-secret-oc.yml, e2e-tests/upgrade-proxysql/compare/statefulset_upgrade-proxysql-pxc-oc.yml
=> K8SPXC-808 - Fix one-pod and upgrade-proxysql for openshift

source/assets/code/kubectl-get-pods-response.txt, source/cluster-wide.rst, source/gke.rst, source/kubernetes.rst, source/minikube.rst, source/openshift.rst
[![K8SPXC-826](https://badgen.net/badge/JIRA/K8SPXC-826/green)](https://jira.percona.com/browse/K8SPXC-826) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-826 - standardize pods response

source/openshift.rst
[![CLOUD-635](https://badgen.net/badge/JIRA/CLOUD-635/green)](https://jira.percona.com/browse/CLOUD-635) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-635 - Update openshift.rst to mention certification

pkg/controller/pxcrestore/restore.go
[![K8SPXC-813](https://badgen.net/badge/JIRA/K8SPXC-813/green)](https://jira.percona.com/browse/K8SPXC-813) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-813: Handle failed restore jobs

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/controller/pxc/upgrade.go, pkg/pxc/app/statefulset/haproxy.go, pkg/pxc/app/statefulset/node.go, pkg/pxc/app/statefulset/proxysql.go, pkg/pxc/statefulset.go
[![K8SPXC-821](https://badgen.net/badge/JIRA/K8SPXC-821/green)](https://jira.percona.com/browse/K8SPXC-821) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-821
=> K8SPXC-821: fix proxysql volume mount condition

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/status.go
[![K8SPXC-815](https://badgen.net/badge/JIRA/K8SPXC-815/green)](https://jira.percona.com/browse/K8SPXC-815) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-815: Fix component size and ready on downscale

source/backups.rst
[![K8SPXC-799](https://badgen.net/badge/JIRA/K8SPXC-799/green)](https://jira.percona.com/browse/K8SPXC-799) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-799 mention backup finalizer

deploy/cr.yaml
=> K8SPXC-808 - Fix indentation for replication channels in cr.yaml

deploy/bundle.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
=> K8SPXC-808 - Update versions for release 1.9.0

e2e-tests/affinity/compare/statefulset_hostname-pxc-oc.yml, e2e-tests/affinity/compare/statefulset_zone-pxc-oc.yml, e2e-tests/init-deploy/compare/statefulset_some-name-pxc-oc.yml
=> K8SPXC-808 - Update diff files in e2e tests for OpenShift

pkg/controller/pxc/replication.go
[![K8SPXC-832](https://badgen.net/badge/JIRA/K8SPXC-832/green)](https://jira.percona.com/browse/K8SPXC-832) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-832: proper new replica pod info message

source/haproxy-conf.rst, source/options.rst, source/proxysql-conf.rst
[![K8SPXC-718](https://badgen.net/badge/JIRA/K8SPXC-718/green)](https://jira.percona.com/browse/K8SPXC-718) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-718 add information about storing configuration in secrets

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.9.0.rst, source/ReleaseNotes/index.rst, source/conf.py
=> K8SPXC-808 the operator 1.9.0 release notes

pkg/controller/pxc/vs.go
Replace stale version with the current CR version
=> fix version service current cr version

source/assets/code/kubectl-get-minimal-response.txt, source/assets/code/mysql-welcome-response.txt, source/minikube.rst
[![CLOUD-637](https://badgen.net/badge/JIRA/CLOUD-637/green)](https://jira.percona.com/browse/CLOUD-637) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
introduce cr-minimal.yaml
change the doc
=> CLOUD-637 - doc minikube minimize

pkg/controller/pxc/controller.go, pkg/controller/pxc/upgrade.go
[![K8SPXC-818](https://badgen.net/badge/JIRA/K8SPXC-818/green)](https://jira.percona.com/browse/K8SPXC-818) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-818
=> K8SPXC-818: fix custom config hash annotations

deploy/cr-minimal.yaml
[![CLOUD-637](https://badgen.net/badge/JIRA/CLOUD-637/green)](https://jira.percona.com/browse/CLOUD-637) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
introduce cr-minimal
=> CLOUD-637 - introduce cr-minimal

pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-850](https://badgen.net/badge/JIRA/K8SPXC-850/green)](https://jira.percona.com/browse/K8SPXC-850) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Old way was not working because of how go working with arrays in range loop
=> K8SPXC-850: fix setting array defaults

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
Pulling code from main branch should pull latest code which relies on :main container images tags and latest CR.
=> main tags for main branch

build/liveness-check.sh, build/readiness-check.sh
[![K8SPXC-816](https://badgen.net/badge/JIRA/K8SPXC-816/green)](https://jira.percona.com/browse/K8SPXC-816) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
use 127.0.0.1 explicitly
=> K8SPXC-816 fix sporadic issues with resolver

clientcmd/clientcmd.go, deploy/cr.yaml, pkg/controller/pxc/controller.go, pkg/controller/pxc/replication.go, pkg/controller/pxc/status_test.go, pkg/controller/pxc/users.go, pkg/pxc/queries/queries.go
[![K8SPXC-851](https://badgen.net/badge/JIRA/K8SPXC-851/green)](https://jira.percona.com/browse/K8SPXC-851) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Update password for replication channel if replication password changed
=> K8SPXC-851: handle replication password change

pkg/controller/pxcbackup/controller.go
[![K8SPXC-796](https://badgen.net/badge/JIRA/K8SPXC-796/green)](https://jira.percona.com/browse/K8SPXC-796) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-796: S3 backup deletion doesn't delete Pods

e2e-tests/validation-hook/conf/cr-simple.yaml, e2e-tests/validation-hook/run, pkg/webhook/hook.go
[![K8SPXC-762](https://badgen.net/badge/JIRA/K8SPXC-762/green)](https://jira.percona.com/browse/K8SPXC-762) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> [K8SPXC-762] Validating webhook not accepting scale operation

e2e-tests/functions, e2e-tests/one-pod/run
[![K8SPXC-876](https://badgen.net/badge/JIRA/K8SPXC-876/green)](https://jira.percona.com/browse/K8SPXC-876) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
this will fix tests on EKS for previous operator version
=> K8SPXC-876: fix tests for EKS 1.21

pkg/webhook/hook.go
[![K8SPXC-883](https://badgen.net/badge/JIRA/K8SPXC-883/green)](https://jira.percona.com/browse/K8SPXC-883) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-883
=> K8SPXC-883 fix deprecated API admissionregistration.k8s.io/v1beta1

source/custom-registry.rst, source/operator.rst
[![K8SPXC-860](https://badgen.net/badge/JIRA/K8SPXC-860/green)](https://jira.percona.com/browse/K8SPXC-860) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-860 initimage option

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml, e2e-tests/monitoring-2-0/run
=> K8SPXC-895 - Update versions for PXCO 1.10.0 release

e2e-tests/functions, e2e-tests/init-deploy/compare/service_some-name-proxysql-unready-oc-k122.yml, e2e-tests/init-deploy/compare/service_some-name-proxysql-unready-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-proxysql-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-proxysql-oc.yml, e2e-tests/security-context/compare/pod_restore-src-restore-pvc-sec-context-4-oc.yml
=> K8SPXC-895 - Fixes for OpenShift tests

deploy/cr.yaml
[![K8SPXC-900](https://badgen.net/badge/JIRA/K8SPXC-900/green)](https://jira.percona.com/browse/K8SPXC-900) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* update CR
=> K8SPXC-900 disable syncing of mysql and admin variables

e2e-tests/functions
=> K8SPXC-895 - Fix vault start in tests for older kubernetes

source/update.rst
[![K8SPXC-880](https://badgen.net/badge/JIRA/K8SPXC-880/green)](https://jira.percona.com/browse/K8SPXC-880) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-880 mention labels not updated at upgrade

e2e-tests/functions, e2e-tests/init-deploy/compare/service_some-name-proxysql-unready-eks-k121.yml, e2e-tests/init-deploy/compare/service_some-name-proxysql-unready-eks.yml
=> K8SPXC-895 - Fix init-deploy test on EKS

source/minikube.rst
[![K8SPXC-892](https://badgen.net/badge/JIRA/K8SPXC-892/green)](https://jira.percona.com/browse/K8SPXC-892) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-892 fix docs with cr-minimal release tag

source/glossary.options.rst, source/operator.rst
[![K8SPXC-789](https://badgen.net/badge/JIRA/K8SPXC-789/green)](https://jira.percona.com/browse/K8SPXC-789) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-789 add replication retry options

build/Dockerfile, build/get-pxc-state, build/pxc-entrypoint.sh, build/pxc-init-entrypoint.sh
[![K8SPXC-904](https://badgen.net/badge/JIRA/K8SPXC-904/green)](https://jira.percona.com/browse/K8SPXC-904) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* move get-pxc-state to operator image not to depend on
pxc releases
=> K8SPXC-904 use admin port in get-pxc-state

source/storage.rst
[![K8SPXC-865](https://badgen.net/badge/JIRA/K8SPXC-865/green)](https://jira.percona.com/browse/K8SPXC-865) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-865 document OpenEBS storage

e2e-tests/functions, e2e-tests/upgrade-consistency/run
=> K8SPXC-895 - Fix upgrade tests on EKS/OpenShift and Kubernetes 1.21+

source/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.10.0.rst, source/glossary.options.rst
=> K8SPXC-895 fixes for RN

pkg/controller/pxc/replication.go, pkg/controller/pxc/upgrade.go, pkg/controller/pxc/users.go, pkg/controller/pxc/version.go, pkg/pxc/queries/queries.go, pkg/pxc/users/users.go
[![K8SPXC-908](https://badgen.net/badge/JIRA/K8SPXC-908/green)](https://jira.percona.com/browse/K8SPXC-908) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-908 add mysql timeouts

pkg/controller/pxc/controller.go, pkg/controller/pxc/version.go, pkg/controller/pxcrestore/controller.go
[![CLOUD-654](https://badgen.net/badge/JIRA/CLOUD-654/green)](https://jira.percona.com/browse/CLOUD-654) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-654 - don't set defaults in CR

deploy/bundle.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
[![K8SPXC-901](https://badgen.net/badge/JIRA/K8SPXC-901/green)](https://jira.percona.com/browse/K8SPXC-901) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-901
Add default resources to `operator.yaml`
=> K8SPXC-901: Add default resource limits for Operator's pod containers

deploy/bundle.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
[![K8SPXC-911](https://badgen.net/badge/JIRA/K8SPXC-911/green)](https://jira.percona.com/browse/K8SPXC-911) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-911 - increase memory limits for operator pod

pkg/pxc/queries/queries.go, pkg/pxc/users/users.go
[![K8SPXC-910](https://badgen.net/badge/JIRA/K8SPXC-910/green)](https://jira.percona.com/browse/K8SPXC-910) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-910 specify database name by default

e2e-tests/conf/chaos-network-loss.yml, e2e-tests/conf/chaos-pod-failure.yml, e2e-tests/conf/chaos-pod-kill.yml, e2e-tests/functions, e2e-tests/operator-self-healing-chaos/conf/operator-chaos.yml, e2e-tests/operator-self-healing-chaos/run, e2e-tests/self-healing-advanced-chaos/run, e2e-tests/self-healing-chaos/run
[![CLOUD-656](https://badgen.net/badge/JIRA/CLOUD-656/green)](https://jira.percona.com/browse/CLOUD-656) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-656 - Add support for chaos-mesh 2.0.4 and kubernetes 1.22

deploy/cr.yaml
[![K8SPXC-738](https://badgen.net/badge/JIRA/K8SPXC-738/green)](https://jira.percona.com/browse/K8SPXC-738) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-738
=> K8SPXC-738: Add `serviceLabels` example in `cr.yaml`

source/operator.rst
[![K8SPX-780](https://badgen.net/badge/JIRA/K8SPX-780/green)](https://jira.percona.com/browse/K8SPX-780) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPX-780 document issuerConf custom resource subsection

deploy/cr.yaml, e2e-tests/security-context/compare/job.batch_restore-job-restore-s3-sec-context-k122.yml, e2e-tests/security-context/compare/job.batch_restore-job-restore-s3-sec-context.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-pvc-k122.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-pvc.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-s3-k122.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-s3.yml, e2e-tests/self-healing-chaos/compare/proxy-vars-80.sql, pkg/apis/pxc/v1/pxc_types.go, pkg/pxc/backup/job.go, pkg/pxc/backup/restore.go
[![K8SPXC-758](https://badgen.net/badge/JIRA/K8SPXC-758/green)](https://jira.percona.com/browse/K8SPXC-758) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-758
Add `verifyTLS` variable to `backup.storages`
=> K8SPXC-758: Allow skipping TLS verification for backup storage

deploy/cr.yaml
We have a question on our forum regarding  it. So we need to add it to our `deploy/cr.yaml` to avoid such kind of questions in the future.
=> Add example of resources for PITR

pkg/apis/pxc/v1/zz_generated.deepcopy.go
[![K8SPXC-758](https://badgen.net/badge/JIRA/K8SPXC-758/green)](https://jira.percona.com/browse/K8SPXC-758) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-758
=> K8SPXC-758 fix: `operator-sdk generate k8s`

e2e-tests/README.md, e2e-tests/build
[![CLOUD-674](https://badgen.net/badge/JIRA/CLOUD-674/green)](https://jira.percona.com/browse/CLOUD-674) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-674 add info about build platform

source/index.rst
[![CLOUD-676](https://badgen.net/badge/JIRA/CLOUD-676/green)](https://jira.percona.com/browse/CLOUD-676) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-676 move helm doc to quickstart section

Jenkinsfile, e2e-tests/functions, e2e-tests/tls-issue-cert-manager/run
[![CLOUD-660](https://badgen.net/badge/JIRA/CLOUD-660/green)](https://jira.percona.com/browse/CLOUD-660) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-660 public access to failed tests

e2e-tests/functions, e2e-tests/upgrade-haproxy/conf/on-demand-backup-minio.yml, e2e-tests/upgrade-haproxy/conf/restore-on-demand-backup-minio.yaml, e2e-tests/upgrade-haproxy/run
[![CLOUD-650](https://badgen.net/badge/JIRA/CLOUD-650/green)](https://jira.percona.com/browse/CLOUD-650) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-650 - Add backup/restore step to upgrade-haproxy test

source/TLS.rst
[![K8SPXC-939](https://badgen.net/badge/JIRA/K8SPXC-939/green)](https://jira.percona.com/browse/K8SPXC-939) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-939 update cert-manager version

ADOPTERS.md, CONTRIBUTING.md, README.md, e2e-tests/README.md
[![CLOUD-677](https://badgen.net/badge/JIRA/CLOUD-677/green)](https://jira.percona.com/browse/CLOUD-677) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Correct the naming
Add help
Simplify quick installation
=> CLOUD-677 Update README.md, other quick fixes

source/operator.rst
[![K8SPXC-970](https://badgen.net/badge/JIRA/K8SPXC-970/green)](https://jira.percona.com/browse/K8SPXC-970) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-970 fix wrong link

Jenkinsfile
[![CLOUD-695](https://badgen.net/badge/JIRA/CLOUD-695/green)](https://jira.percona.com/browse/CLOUD-695) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-695_jenkinsfile_improvements add finally to log push

e2e-tests/self-healing-chaos/compare/proxy-vars-80.sql, e2e-tests/self-healing/compare/proxy-vars-80.sql
[![K8SPXC-1003](https://badgen.net/badge/JIRA/K8SPXC-1003/green)](https://jira.percona.com/browse/K8SPXC-1003) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1003 fix self-healing and self-healing-chaos tests

e2e-tests/auto-tuning/conf/auto-tuning1.yml, e2e-tests/auto-tuning/conf/auto-tuning2.yml, e2e-tests/auto-tuning/conf/auto-tuning3.yml, e2e-tests/auto-tuning/run
[![K8SPXC-995](https://badgen.net/badge/JIRA/K8SPXC-995/green)](https://jira.percona.com/browse/K8SPXC-995) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-995 fix auto-tuning test

deploy/cr.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/controller/pxc/replication.go, pkg/pxc/service.go
[![K8SPXC-935](https://badgen.net/badge/JIRA/K8SPXC-935/green)](https://jira.percona.com/browse/K8SPXC-935) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-935
=> K8SPXC-935: add possibility to specify nodePort for HAProxy and ProxySQL

deploy/cr.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/controller/pxc/replication.go, pkg/pxc/service.go
[![K8SPXC-935](https://badgen.net/badge/JIRA/K8SPXC-935/green)](https://jira.percona.com/browse/K8SPXC-935) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Reverts percona/percona-xtradb-cluster-operator#1127
=> Revert "K8SPXC-935: add possibility to specify nodePort for HAProxy and ProxySQL"

pkg/controller/pxc/replication.go
[![K8SPXC-935](https://badgen.net/badge/JIRA/K8SPXC-935/green)](https://jira.percona.com/browse/K8SPXC-935) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-935 fix trafficPolicy issue for replica services

ADOPTERS.md, CONTRIBUTING.md, README.md
[![CLOUD-691](https://badgen.net/badge/JIRA/CLOUD-691/green)](https://jira.percona.com/browse/CLOUD-691) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-691 rename the operator in README and other md docs

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
[![K8SPXC-917](https://badgen.net/badge/JIRA/K8SPXC-917/green)](https://jira.percona.com/browse/K8SPXC-917) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-917 release 1.11.0 edit versions

deploy/cr.yaml, e2e-tests/default-cr/compare/statefulset_cluster1-pxc-oc.yml, e2e-tests/default-cr/compare/statefulset_cluster1-pxc.yml, e2e-tests/default-cr/run, e2e-tests/proxy-protocol/run
[![K8SPXC-917](https://badgen.net/badge/JIRA/K8SPXC-917/green)](https://jira.percona.com/browse/K8SPXC-917) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-917 release-1.11.0 fix tests for gke

deploy/cr.yaml
[![K8SPXC-916](https://badgen.net/badge/JIRA/K8SPXC-916/green)](https://jira.percona.com/browse/K8SPXC-916) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-916 add missing option examples to cr.yaml

source/cluster-wide.rst, source/index.rst
[![CLOUD-696](https://badgen.net/badge/JIRA/CLOUD-696/green)](https://jira.percona.com/browse/CLOUD-696) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-696 rewrite TOC

source/ReleaseNotes/index.rst, source/TLS.rst, source/api.rst, source/cluster-wide.rst, source/conf.py, source/constraints.rst, source/custom-registry.rst, source/faq.rst, source/gke.rst, source/haproxy-conf.rst, source/helm.rst, source/images.rst, source/index.rst, source/minikube.rst, source/openshift.rst, source/proxysql-conf.rst, source/recovery.rst, source/storage.rst, source/update.rst
[![CLOUD-691](https://badgen.net/badge/JIRA/CLOUD-691/green)](https://jira.percona.com/browse/CLOUD-691) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-691 rename the operator in docs

e2e-tests/init-deploy/compare/service_some-name-proxysql-unready-eks-k122.yml, e2e-tests/self-healing-chaos/compare/proxy-vars.sql
[![K8SPXC-917](https://badgen.net/badge/JIRA/K8SPXC-917/green)](https://jira.percona.com/browse/K8SPXC-917) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-917 Versions upgrade

source/users.rst
[![CLOUD-703](https://badgen.net/badge/JIRA/CLOUD-703/green)](https://jira.percona.com/browse/CLOUD-703) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-703 update info about user secrets and random passwords

source/monitoring.rst, source/users.rst
[![K8SPXC-823](https://badgen.net/badge/JIRA/K8SPXC-823/green)](https://jira.percona.com/browse/K8SPXC-823) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-823 update pmm client auth

source/backups.rst
[![K8SPXC-985](https://badgen.net/badge/JIRA/K8SPXC-985/green)](https://jira.percona.com/browse/K8SPXC-985) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-985 mention pitr has no filtering

go.mod, go.sum, vendor/gopkg.in/yaml.v3/parserc.go, vendor/modules.txt
[![K8SPXC-1057](https://badgen.net/badge/JIRA/K8SPXC-1057/green)](https://jira.percona.com/browse/K8SPXC-1057) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Fix gopkg.in/yaml.v3 

source/backups.rst, source/containers-conf.rst, source/haproxy-conf.rst, source/monitoring.rst, source/options.rst, source/proxysql-conf.rst, source/users.rst
Minor update to fix a patch command for the password.
@fiowro i remember we fixed it some time ago for replication. Could you please check if we have other places?
Otherwise the command does not work.
=> Update monitoring.rst and other docs with non-wrapping base64 encoder

Jenkinsfile
[![K8SPXC-630](https://badgen.net/badge/JIRA/K8SPXC-630/green)](https://jira.percona.com/browse/K8SPXC-630) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-630 update k8s version

pkg/pxc/pdb.go
[![K8SPXC-983](https://badgen.net/badge/JIRA/K8SPXC-983/green)](https://jira.percona.com/browse/K8SPXC-983) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-983 update PodDisruptionBudget to policy/v1

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml
[![PMM-10724](https://badgen.net/badge/JIRA/PMM-10724/green)](https://jira.percona.com/browse/PMM-10724) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This fixes a bug in DBaaS UI when 1.11.1 is installed but PMM thinks that it's 1.11.0 because v1-11-1 does not exist
=> PMM-10724 Added v1-11-1 API version 

.github/CODEOWNERS, Jenkinsfile
[![CLOUD-705](https://badgen.net/badge/JIRA/CLOUD-705/green)](https://jira.percona.com/browse/CLOUD-705) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-705 delete unused clusters 

Jenkinsfile
[![CLOUD-705](https://badgen.net/badge/JIRA/CLOUD-705/green)](https://jira.percona.com/browse/CLOUD-705) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-705 temporarily remove labels

Jenkinsfile
[![K8SPXC-1111](https://badgen.net/badge/JIRA/K8SPXC-1111/green)](https://jira.percona.com/browse/K8SPXC-1111) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1111 - Revert number of clusters and timeout

cmd/pitr/collector/collector.go, cmd/pitr/recoverer/recoverer.go, cmd/pitr/storage/storage.go
[![K8SPXC-1122](https://badgen.net/badge/JIRA/K8SPXC-1122/green)](https://jira.percona.com/browse/K8SPXC-1122) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-1122
=> K8SPXC-1122: fix binlog certificate verification

Jenkinsfile
[![K8SPXC-1111](https://badgen.net/badge/JIRA/K8SPXC-1111/green)](https://jira.percona.com/browse/K8SPXC-1111) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
- fix ugly random workaround for `--cluster-ipv4-cidr` option on cluster creation
- put PR number inside cluster name instead of using labels (it's not just about removing labels for this, I would like to see PR number in the cluster name)
=> K8SPXC-1111 - Fix --cluster-ipv4-cidr option in Jenkinsfile

deploy/bundle.yaml, deploy/cr.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller.go, pkg/controller/pxc/replication.go, pkg/controller/pxc/upgrade.go
[![K8SPXC-1082](https://badgen.net/badge/JIRA/K8SPXC-1082/green)](https://jira.percona.com/browse/K8SPXC-1082) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-1082
=> K8SPXC-1082: add `ignoreAnnotations` and `ignoreLabels` options for services

deploy/cr.yaml
[![K8SPXC-955](https://badgen.net/badge/JIRA/K8SPXC-955/green)](https://jira.percona.com/browse/K8SPXC-955) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-955 improve typo in the loadBalancerSourceRanges cr.yaml key name

e2e-tests/functions
=> K8SPXC-1038 fix demand-backup-cloud test for 5.7

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
=> K8SPXC-1038 - Update versions for release 1.12.0

e2e-tests/self-healing-chaos/compare/proxy-vars.sql
=> Fix proxysql version in self-healing-chaos test for 5.7

e2e-tests/functions, e2e-tests/operator-self-healing-chaos/run, e2e-tests/self-healing-advanced-chaos/run, e2e-tests/self-healing-chaos/run
=> K8SPXC-1038 - Update chaos-mesh version and tests

e2e-tests/functions, e2e-tests/security-context/compare/job.batch_restore-job-restore-pvc-sec-context-k124.yml, e2e-tests/security-context/compare/job.batch_restore-job-restore-s3-sec-context-k124.yml
=> Fix security-context test for kubernetes 1.24

deploy/cr.yaml
[![K8SPXC-1140](https://badgen.net/badge/JIRA/K8SPXC-1140/green)](https://jira.percona.com/browse/K8SPXC-1140) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1140 add fields to CR

config/crd/bases/pxc.percona.com_perconaxtradbclusters.yaml, deploy/bundle.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-1157](https://badgen.net/badge/JIRA/K8SPXC-1157/green)](https://jira.percona.com/browse/K8SPXC-1157) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1157 fix HPA

e2e-tests/operator-self-healing-chaos/run, e2e-tests/self-healing-advanced-chaos/run, e2e-tests/self-healing-chaos/run
=> K8SPXC-1038 - Fix self-healing-chaos test

e2e-tests/self-healing-chaos/compare/proxy-vars-80.sql, e2e-tests/self-healing-chaos/compare/proxy-vars.sql
=> Update proxysql version in self-healing-chaos test

e2e-tests/pitr/run
=> K8SPXC-1038 - Fix pitr test by moving the binlog gap case to the end

deploy/backup/restore.yaml
[![K8SPXC-1120](https://badgen.net/badge/JIRA/K8SPXC-1120/green)](https://jira.percona.com/browse/K8SPXC-1120) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Add example for creating headless PVC restore service

e2e-tests/functions, e2e-tests/haproxy/run, e2e-tests/security-context/compare/job.batch_restore-job-restore-pvc-sec-context-k124-eks.yml, e2e-tests/security-context/compare/job.batch_restore-job-restore-pvc-sec-context-k124-oc.yml, e2e-tests/security-context/compare/job.batch_restore-job-restore-s3-sec-context-k124-eks.yml, e2e-tests/security-context/compare/job.batch_restore-job-restore-s3-sec-context-k124-oc.yml
There are a few modifications to add for successful test completion on target platforms
=> K8SPXC-1038 Tweaks for EKS and Openshift

build/Dockerfile
[![K8SPXC-1189](https://badgen.net/badge/JIRA/K8SPXC-1189/green)](https://jira.percona.com/browse/K8SPXC-1189) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1189 update base image to ubi9

.github/pull_request_template.md
[![CLOUD-748](https://badgen.net/badge/JIRA/CLOUD-748/green)](https://jira.percona.com/browse/CLOUD-748) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-748 - Add checklist for Github PRs

deploy/backup/restore.yaml
[![K8SPXC-1192](https://badgen.net/badge/JIRA/K8SPXC-1192/green)](https://jira.percona.com/browse/K8SPXC-1192) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1192 add destination option

Jenkinsfile, e2e-tests/scheduled-backup/conf/scheduled-backup-azure.yml, e2e-tests/scheduled-backup/conf/scheduled-backup-disable.yml, e2e-tests/scheduled-backup/conf/scheduled-backup-gcs.yml, e2e-tests/scheduled-backup/conf/scheduled-backup-minio.yml, e2e-tests/scheduled-backup/conf/scheduled-backup-pvc.yml, e2e-tests/scheduled-backup/run, pkg/controller/pxc/backup.go
[![K8SPXC-1197](https://badgen.net/badge/JIRA/K8SPXC-1197/green)](https://jira.percona.com/browse/K8SPXC-1197) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
We don't delete backups from Azure storage
**Cause:**
We don't add finalizer to backup object for Azure.
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1197 fix azure backup deletion

cmd/peer-list/main.go
[![K8SPXC-1220](https://badgen.net/badge/JIRA/K8SPXC-1220/green)](https://jira.percona.com/browse/K8SPXC-1220) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Reverts percona/percona-xtradb-cluster-operator#1383
=> Revert "K8SPXC-1220: handle DNS timeouts in peer-list"

config/crd/bases/pxc.percona.com_perconaxtradbclusters.yaml, deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
[![K8SPXC-1165](https://badgen.net/badge/JIRA/K8SPXC-1165/green)](https://jira.percona.com/browse/K8SPXC-1165) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
*Update images and versions for 1.13.0 release*
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1165 - Update images and versions for 1.13.0 release

deploy/cr.yaml
[![K8SPXC-1165](https://badgen.net/badge/JIRA/K8SPXC-1165/green)](https://jira.percona.com/browse/K8SPXC-1165) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Update PMM client version in cr.yaml*
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1165 - Update PMM client version in cr.yaml

pkg/controller/pxcbackup/controller.go
[![K8SPXC-1265](https://badgen.net/badge/JIRA/K8SPXC-1265/green)](https://jira.percona.com/browse/K8SPXC-1265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Backup was marked as Failed after the first failure.
**Solution:**
We're checking `Failed` condition in backup status. Backup will be marked as Failed only if Job is marked as Failed.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1265: Fix marking backup as failed before reaching backoff limit

deploy/cr.yaml
[![K8SPXC-1165](https://badgen.net/badge/JIRA/K8SPXC-1165/green)](https://jira.percona.com/browse/K8SPXC-1165) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Solution:**
*Put correct image into cr.yaml for backups*
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1165 - Fix image for backup for PXC 1.13.0 release

.github/CODEOWNERS
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> Update codeowners for github

e2e-tests/monitoring-2-0/compare/agents-list.json
[![PMM-12778](https://badgen.net/badge/JIRA/PMM-12778/green)](https://jira.percona.com/browse/PMM-12778) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Fix monitoring test
**Cause:**
We can't get info about external_exporter status. 
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> PMM-12778 update agents check

e2e-tests/build
[![K8SPXC-1309](https://badgen.net/badge/JIRA/K8SPXC-1309/green)](https://jira.percona.com/browse/K8SPXC-1309) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1309]: https://perconadev.atlassian.net/browse/K8SPXC-1309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1309 fix multi architecture builds

.github/dependabot.yml
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* we can set day only for weekly interval
[CLOUD-727]: https://perconadev.atlassian.net/browse/CLOUD-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLOUD-727 update schedule section for gomod

deploy/cr.yaml
[![K8SPXC-1334](https://badgen.net/badge/JIRA/K8SPXC-1334/green)](https://jira.percona.com/browse/K8SPXC-1334) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Add lifecycle hooks example
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1334]: https://perconadev.atlassian.net/browse/K8SPXC-1334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1334: Add lifecycle hooks example

deploy/cr.yaml, e2e-tests/haproxy/conf/haproxy.yml, e2e-tests/haproxy/run, e2e-tests/limits/compare/statefulset_no-limits-proxysql-increased-k127-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-proxysql-k127-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-increased-k127-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-k127-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-pxc-increased-oc.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-pxc-k127-oc.yml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1295]: https://perconadev.atlassian.net/browse/K8SPXC-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1295 - Fix tests on OpenShift

e2e-tests/run-pr.csv, e2e-tests/run-release.csv
[![K8SPXC-1341](https://badgen.net/badge/JIRA/K8SPXC-1341/green)](https://jira.percona.com/browse/K8SPXC-1341) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1341 - Add pvc-resize test into release tests

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
---
Update images and versions for 1.14.0 release
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1295]: https://perconadev.atlassian.net/browse/K8SPXC-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1295 Update images and versions for 1.14.0 release

build/pxc-entrypoint.sh
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1295]: https://perconadev.atlassian.net/browse/K8SPXC-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1295 fix db update for PXC 5.7

Makefile
[![CLOUD-833](https://badgen.net/badge/JIRA/CLOUD-833/green)](https://jira.percona.com/browse/CLOUD-833) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-833]: https://perconadev.atlassian.net/browse/CLOUD-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> CLOUD-833 - Update release and after-release Makefile targets

Jenkinsfile
[![CLOUD-851](https://badgen.net/badge/JIRA/CLOUD-851/green)](https://jira.percona.com/browse/CLOUD-851) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-851]: https://perconadev.atlassian.net/browse/CLOUD-851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> CLOUD-851 updating-jq-and-yq-versions

e2e-tests/default-cr/compare/statefulset_cluster1-haproxy-k127.yml, e2e-tests/default-cr/compare/statefulset_cluster1-haproxy.yml, e2e-tests/default-cr/compare/statefulset_minimal-cluster-haproxy-k127.yml, e2e-tests/default-cr/compare/statefulset_minimal-cluster-haproxy.yml, e2e-tests/demand-backup/compare/job_restore-job-on-demand-backup-pvc-bsource-demand-backup-k129.yml, e2e-tests/demand-backup/compare/job_restore-job-on-demand-backup-pvc-demand-backup-k129.yml
[![K8SPXC-1363](https://badgen.net/badge/JIRA/K8SPXC-1363/green)](https://jira.percona.com/browse/K8SPXC-1363) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1363]: https://perconadev.atlassian.net/browse/K8SPXC-1363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1363 fix tests

deploy/cr-minimal.yaml, deploy/cr.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1363 Update images and versions for 1.15.0 release - 02

deploy/cr.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1363 Update images and versions for 1.15.0 release - 03

build/haproxy_check_pxc.sh
[![K8SPXC-1381](https://badgen.net/badge/JIRA/K8SPXC-1381/green)](https://jira.percona.com/browse/K8SPXC-1381) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1381]: https://perconadev.atlassian.net/browse/K8SPXC-1381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1381 update haproxy_check_pxc.sh script

e2e-tests/demand-backup-cloud/compare/job.batch_restore-job-on-demand-backup-azure-demand-backup-cloud-k129-oc.yml, e2e-tests/demand-backup-cloud/compare/job.batch_restore-job-on-demand-backup-s3-demand-backup-cloud-k129-oc.yml, e2e-tests/demand-backup-cloud/compare/job.batch_xb-on-demand-backup-aws-s3-k129-oc.yml, e2e-tests/demand-backup-cloud/compare/job.batch_xb-on-demand-backup-azure-blob-k129-oc.yml, e2e-tests/demand-backup/compare/job_restore-job-on-demand-backup-minio-demand-backup-k129-oc.yml, e2e-tests/demand-backup/compare/job_restore-job-on-demand-backup-pvc-bsource-demand-backup-k129-oc.yml, e2e-tests/demand-backup/compare/job_restore-job-on-demand-backup-pvc-demand-backup-k129-oc.yml, e2e-tests/demand-backup/compare/job_xb-on-demand-backup-minio-k129-oc.yml, e2e-tests/functions
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1363: Add k129 oc support

Jenkinsfile, config/crd/bases/pxc.percona.com_perconaxtradbclusters.yaml, deploy/bundle.yaml, deploy/cr.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, e2e-tests/pvc-resize/run, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/volumes.go
[![K8SPXC-1476](https://badgen.net/badge/JIRA/K8SPXC-1476/green)](https://jira.percona.com/browse/K8SPXC-1476) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1476]: https://perconadev.atlassian.net/browse/K8SPXC-1476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1476: Disable PVC resize by default

README.md
updating roadmap link in gh after migrating to new projects
=> Update README.md - roadmap link

e2e-tests/security-context/compare/statefulset_sec-context-pxc-changes.yml, e2e-tests/security-context/compare/statefulset_sec-context-pxc.yml
[![K8SPXC-1410](https://badgen.net/badge/JIRA/K8SPXC-1410/green)](https://jira.percona.com/browse/K8SPXC-1410) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1410]: https://perconadev.atlassian.net/browse/K8SPXC-1410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1410 fix security-context test

README.md
[![CLOUD-878](https://badgen.net/badge/JIRA/CLOUD-878/green)](https://jira.percona.com/browse/CLOUD-878) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
minor fixes and links for readme
[CLOUD-878]: https://perconadev.atlassian.net/browse/CLOUD-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CLOUD-878] minor fixes and links from README

deploy/cr.yaml, e2e-tests/release_versions
[![K8SPXC-1446](https://badgen.net/badge/JIRA/K8SPXC-1446/green)](https://jira.percona.com/browse/K8SPXC-1446) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Update PMM version to 2.44.0
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1446]: https://perconadev.atlassian.net/browse/K8SPXC-1446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1446: use PMM 2.44.0

e2e-tests/release_versions
[![K8SPXC-1446](https://badgen.net/badge/JIRA/K8SPXC-1446/green)](https://jira.percona.com/browse/K8SPXC-1446) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1446: fix pxc2.4 to pxc5.7 in backup image

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml, version/version.go
[![K8SPXC-1537](https://badgen.net/badge/JIRA/K8SPXC-1537/green)](https://jira.percona.com/browse/K8SPXC-1537) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
… release
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1537]: https://perconadev.atlassian.net/browse/K8SPXC-1537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> K8SPXC-1537 new version code preparations in main branch for the next release

deploy/backup/backup.yaml
[![K8SPXC-1547](https://badgen.net/badge/JIRA/K8SPXC-1547/green)](https://jira.percona.com/browse/K8SPXC-1547) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1547]: https://perconadev.atlassian.net/browse/K8SPXC-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1547 fix the example of backup object

Jenkinsfile
[![K8SPXC-1570](https://badgen.net/badge/JIRA/K8SPXC-1570/green)](https://jira.percona.com/browse/K8SPXC-1570) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1570]: https://perconadev.atlassian.net/browse/K8SPXC-1570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1570 Jenkinsfile cluster-version set to 1.29 from 1.28

deploy/bundle.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> Update images for custom-206

deploy/bundle.yaml, deploy/cw-bundle.yaml, deploy/cw-rbac.yaml, deploy/rbac.yaml
[![K8SPXC-1152](https://badgen.net/badge/JIRA/K8SPXC-1152/green)](https://jira.percona.com/browse/K8SPXC-1152) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Restore on openshift fails with:
`'failed to validate restore job: failed to validate backup existence:
failed to create pod: pods "restore-src-pvc-202531793346-q6fav-scheduled-backup-verify"
is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource
you can''t set finalizers on: , <nil>'`
**Solution:**
Give the permissions to set finalizers on the object …
=> K8SPXC-1152: add perconaxtradbclusterrestores/finalizers to rbac 

pkg/controller/pxcrestore/controller.go
[![K8SPXC-1376](https://badgen.net/badge/JIRA/K8SPXC-1376/green)](https://jira.percona.com/browse/K8SPXC-1376) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1376]: https://perconadev.atlassian.net/browse/K8SPXC-1376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1376: Fix restores for crVersion 1.17.0
