percona/percona-xtradb-cluster-operator

deploy/cr.yaml, pkg/apis/pxc/v1alpha1/perconaxtradbcluster_types.go
New flag allowUnsafeConfigurations for pxc-spec.
=> CLOUD-83 [PXC] allow unsafe configurations

version/server.go
Currently if running in openshift 4.0+ it assumes the platform is
kubernetes.
=> version/server.go: Detect openshift 4.0+ clusters

pkg/pxc/backup/names.go
Before this commit backup name may be ended up with non-legitimate from the k8s point of view ending (non-alphanumeric char)
=> Fix possible malformed backup name

deploy/backup/copy-backup.sh, deploy/backup/restore-backup.sh
When I use `deploy/backup/restore-backup.sh` to restore data, I got the following error:
```
[root@iZuf60l6m7p7elsxtxv2yuZ ~]# ./restore-backup.sh cron-cluster1-20190424052506-uumyj cluster1
Log: /tmp/tmp.Xk5K8y67Ev/log
base64: invalid option -- 'D'
Try 'base64 --help' for more information.
base64: invalid option -- 'D'
Try 'base64 --help' for more information.
pvc/cluster1-xb-cron-cluster1-20190424052506-uumyjbase64: invalid option -- 'D'
Try 'base64 --help' for more information.
base64: invalid option -- 'D'
Try 'base64 --help' for more information.
All data in 'cluster1' Percona XtraDB Cluster will be deleted during the backup restoration.
Are you sure? [y/N] y
perconaxtradbcluster.pxc.percona.com "cluster1" deleted
Deleting cluster1-pxc-2.[done]
Deleting cluster1-pxc-1.[done]
Deleting …
```
=> [BugFix] Modified base64 option(decode data)

deploy/cr.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxcbackup/controller.go, pkg/pxc/backup/backup.go, pkg/pxc/backup/scheduled.go
Controlling `ServiceAccount` that will be used in the operator is possible by changing `serviceAccountName` form default to specific ServiceAccount. This is very useful in some cases like deploying the operator in general purpose namespace. In that case binding the default service account with the operator role is not a good practice.
Using service account in ScheduledBackup is not possible. It use by the default service account. The scheduled backups need only the following role:
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
name: percona-backup
namespace: monitoring
rules:
- apiGroups:
- pxc.percona.com
resources:
- perconaxtradbclusterbackups
verbs:
...
```
This pull request will add support to set `serviceAccountName` in backup section of …
=> Add backup serviceaccount

Jenkinsfile
* GKE has limit on lenght of cluster name, we need use shorter
names for our clusters
=> JEN-1115 remove branch name from name of cluster

e2e-tests/build
sometimes in tests IMAGE variable is set to released version
avoid situations when image can be rewritten
=> avoid mistake during push

deploy/backup/README.md
To match https://www.percona.com/doc/kubernetes-operator-for-pxc/backups.html
This outdated documentation sent me on a 5 hour wild goose chase trying to get the restore script it references to work, when in fact it's totally wrong. Let's avoid misleading people with out of date documentation.
=> Updates backup restore documentation

pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/status.go
Status would be look like 
`status:
conditions:
- lastTransitionTime: "2020-01-30T17:09:23Z"
status: "True"
type: Initializing
- lastTransitionTime: "2020-01-30T17:11:55Z"
status: "True"
type: Ready
host: cluster1-pxc
observedGeneration: 1
proxysql: {}
pxc:
ready: 3
size: 3
status: ready
state: ready`
=> K8SPXC-40 Handle missing proxysql spec section

pkg/apis/pxc/v1/pxc_types.go
Check if the CR's apiVersion is an empty string. If so, return 'v1' as the new API version.
- emerged from https://jira.percona.com/projects/K8SPXC/issues/K8SPXC-222
=> Catch empty CR apiVersions

pkg/apis/pxc/v1/pxc_types.go
strings.TrimLeft changed to strings.TrimPrefix. 
Please take a look at the strings.TrimLeft documentation.
> // TrimLeft returns a slice of the string s with all leading
> // Unicode code points contained in cutset removed.
> //
> // To remove a prefix, use TrimPrefix instead.
Signed-off-by: heartwilltell <heartwilltell@gmail.com>
=> CLOUD-531 Fix wrong usage of strings.TrimLeft, cutset contains duplicate characters.

pkg/pxc/backup/names.go
Replace commas with periods when generating the "schedule" label for CronJobs.
This extends the usable syntax of backups to include lists of
values like: "0 0 * * 0,1,2,3,4,5" = daily, except saturday.
=> K8SPXC-290 - Extend usable backup schedule syntax

e2e-tests/big-data/run, e2e-tests/functions, e2e-tests/self-healing-advanced/run, e2e-tests/self-healing/run
I have split it into two because some versions of sed don't support "|" operator.
First one works on images from operator dockergub and second one works on images from PXC dockerhub.
Here's a quick test:
```
$ cat test.txt
image: percona/percona-xtradb-cluster-operator:1.4.0-pxc8.0
image: percona/percona-xtradb-cluster-operator:1.4.0-pxc
image: percona/percona-xtradb-cluster:8.0.18-9.3
image: percona/percona-xtradb-cluster:5.7.28-31.41.2
$ cat test.txt | sed -e "s#image:.*-pxc\([0-9]*.[0-9]*\)\{0,1\}\$#image: aaa#"
image: aaa
image: aaa
image: percona/percona-xtradb-cluster:8.0.18-9.3
image: percona/percona-xtradb-cluster:5.7.28-31.41.2
$ cat test.txt | sed -e "s#image:.*\/percona-xtradb-cluster:.*\$#image: aaa#"
image: percona/percona-xtradb-cluster-operator:1.4.0-pxc8.0
image: …
```
=> Fix checks for PXC images in e2e functions and tests

e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-100-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-100.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-110-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-110.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-120-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-120.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-130-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-130.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-140-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-140.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-150.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-100-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-100.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-110-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-110.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-120-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-120.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-130-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-130.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-140-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-140.yml, e2e-tests/upgrade-consistency/run, pkg/controller/pxc/upgrade.go, pkg/pxc/statefulset.go
[![K8SPXC-257](https://badgen.net/badge/JIRA/K8SPXC-257/green)](https://jira.percona.com/browse/K8SPXC-257)
CR has operator version. Operator should be able to act as old version.
Operator should not trigger PXC restart if we update only Operator Pod
without updating operator version in CR.
=> K8SPXC-257 add service account only in 1.5.0

build/pxc-entrypoint.sh
[![K8SPXC-327](https://badgen.net/badge/JIRA/K8SPXC-327/green)](https://jira.percona.com/browse/K8SPXC-327)
can be merged only after https://github.com/percona/percona-xtradb-cluster-operator/pull/449
if PXC Pod was restarted during SST the /var/lib/mysql/sst-xb-tmpdir
directory become preserved. Every new SST failed if directory exists.
```
2020-06-23T20:05:34.526984Z 0 [ERROR] [MY-000000] [WSREP-SST] FATAL: Found existing /var/lib/mysql//sst-xb-tmpdir
2020-06-23T20:05:34.527007Z 0 [ERROR] [MY-000000] [WSREP-SST] Please remove it or specify alternative temporary directory location by setting [sst]/tmpdir
```
SST code - https://github.com/percona/percona-xtradb-cluster/blob/8.0/scripts/wsrep_sst_xtrabackup-v2.sh#L2040
=> K8SPXC-327 crash after interrupted SST

pkg/controller/pxc/controller.go, pkg/controller/pxc/upgrade.go
[![K8SPXC-326](https://badgen.net/badge/JIRA/K8SPXC-326/green)](https://jira.percona.com/browse/K8SPXC-326)
changes in TLS secrets should trigger PXC restart
(trigger changing annotation with a new hash)
even if AllowUnsafeConfig is enabled
=> K8SPXC-326 fix empty hash if AllowUnsafeConfig enabled

e2e-tests/functions
[![CLOUD-556](https://badgen.net/badge/JIRA/CLOUD-556/green)](https://jira.percona.com/browse/CLOUD-556)
Kubernets 1.17 puts some extra fields into Statefulset about
pod volume claim. We do not expect them, thus need to get rid
of them
```
+ diff -u /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/init-deploy/compare/statefulset_some-name-pxc.yml /tmp/tmp.YUAO2Wdrs9/statefulset_some-name-pxc.yml
--- /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/init-deploy/compare/statefulset_some-name-pxc.yml	2020-07-02 06:19:52.000000000 +0000
+++ /tmp/tmp.YUAO2Wdrs9/statefulset_some-name-pxc.yml	2020-07-02 06:29:10.855373281 +0000
@@ -187,7 +187,9 @@
partition: 0
type: RollingUpdate
volumeClaimTemplates:
-  - metadata:
+  - apiVersion: v1
+    kind: …
```
=> CLOUD-556 Remove extra fields

build/Dockerfile, build/pxc-configure-pxc.sh, build/pxc-entrypoint.sh, build/pxc-init-entrypoint.sh
[![K8SPXC-344](https://badgen.net/badge/JIRA/K8SPXC-344/green)](https://jira.percona.com/browse/K8SPXC-344)
after K8SPXC-276 implementation, ProxySQL selects writer in the
following order Pod-0,Pod-2,Pod-1.
in all cases we prefer to avoid selection of current writer as a donor.
=> K8SPXC-344 fix donor priority 

pkg/pxc/backup/names.go, pkg/pxc/backup/scheduled.go
[![K8SPXC-352](https://badgen.net/badge/JIRA/K8SPXC-352/green)](https://jira.percona.com/browse/K8SPXC-352)
unique backup "suffix" is needed for reduce chance of
conflict between different backup CR names which can
be produced in the same second by two backup cronjobs.
unfortunately, "suffix" regenerated on each reconcile loop.
=> K8SPXC-352 dont recreate cronjob on each reconcile loop

pkg/pxc/service.go
[![K8SPXC-353](https://badgen.net/badge/JIRA/K8SPXC-353/green)](https://jira.percona.com/browse/K8SPXC-353)
We have separate service for reading traffic which is automatically distributed between all PXC members.
it also should use default MySQL port for incoming traffic.
=> K8SPXC-353 haproxy-replicas service should forward from 3306 to 3307

pkg/controller/pxc/upgrade.go
[![K8SPXC-294](https://badgen.net/badge/JIRA/K8SPXC-294/green)](https://jira.percona.com/browse/K8SPXC-294)
if user edits cr.Spec.HAProxy.Configuration Operator should catch
changes and fix annotations to trigger HAProxy pods restart
=> K8SPXC-294 HAProxy pods should be restarted on config change

pkg/controller/pxc/status.go
[![K8SPXC-360](https://badgen.net/badge/JIRA/K8SPXC-360/green)](https://jira.percona.com/browse/K8SPXC-360)
HAProxy version received from version service and set only once, we should intentionally save it during status updates later
=> K8SPXC-360: keep HAProxy version during status update

pkg/controller/pxc/version.go
[![K8SPXC-365](https://badgen.net/badge/JIRA/K8SPXC-365/green)](https://jira.percona.com/browse/K8SPXC-365)
we should refetch version information from PXC if the user manually changed the PXC image.
we should take the version from Version Service if SmartUpdate enabled
=> K8SPXC-365 run version detection on image change if SmartUpdate disabled

Jenkinsfile, e2e-tests/functions
[![K8SPXC-366](https://badgen.net/badge/JIRA/K8SPXC-366/green)](https://jira.percona.com/browse/K8SPXC-366)
* if test fails then ns is not deleted automatically that is why
we have the situation that gke cluster has a lot of old pods
in namespaces which were used for failed tests
=> K8SPXC-366 Add possibility to clean up unused ns

e2e-tests/self-healing/compare/proxy-vars.sql
Test was failing because the diff existed.
=> Fix test self-healing compare for proxy-vars for PXC 5.7

pkg/controller/pxcbackup/controller.go
[![K8SPXC-355](https://badgen.net/badge/JIRA/K8SPXC-355/green)](https://jira.percona.com/browse/K8SPXC-355)
S3 backup folder names were getting generated with YYYY-DD-MM date format. Change to use conventional YYYY-MM-DD order.
=> K8SPXC-355 Swap day/month in S3 backup date format

e2e-tests/functions
In EKS restore pod could have definition like this:
```
apiVersion: v1
kind: Pod
metadata:
annotations:
kubernetes.io/psp: eks.privileged
openshift.io/scc: privileged
```
and it was failing like this:
```
+ diff -u /vagrant/production/percona-xtradb-cluster-operator/e2e-tests/security-context/compare/job.batch_sec-context-xb-on-demand-backup-pvc.yml /tmp/tmp.eXeMfonXII/job.batch_sec-context-xb-on-demand-backup-pvc.yml
--- /vagrant/production/percona-xtradb-cluster-operator/e2e-tests/security-context/compare/job.batch_sec-context-xb-on-demand-backup-pvc.yml  2020-06-23 07:27:54.000000000 +0000
+++ /tmp/tmp.eXeMfonXII/job.batch_sec-context-xb-on-demand-backup-pvc.yml 2020-07-20 …
```
=> K8SPXC-356 Fix security-context test on EKS

e2e-tests/functions
[![CLOUD-544](https://badgen.net/badge/JIRA/CLOUD-544/green)](https://jira.percona.com/browse/CLOUD-544)
reason: we should test images which are specified in tests,
not images which are fetched from version service.
=> CLOUD-544 it is needed to disable version service in tests

pkg/controller/pxc/controller.go
[![K8SPXC-390](https://badgen.net/badge/JIRA/K8SPXC-390/green)](https://jira.percona.com/browse/K8SPXC-390)
On Percona's recommendation we're switching our PXC-Operator managed
clusters from proxysql to HAProxy to front our clusters. For the
record we're using version 1.5.0 of the Percoan XtraDB Cluster
Operator.
With an HAProxy spec that matches the example here:
https://github.com/percona/percona-xtradb-cluster-operator/blob/1cc77802b559a4baa947bfa0b377a4d2a0858b31/deploy/cr.yaml#L93-L174
the percona-xtradb-cluster-operator pod fails to start indicating that
the pxc controller can't parse the HAProxy spec
```
...
{"level":"info","ts":1596064927.2384582,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"perconaxtradbclusterrestore-controller","worker …
```
=> K8SPXC-390 - Fix PXC-Operator pod crashing on missing HAProxy PodDisruptionBudget

build/pxc-entrypoint.sh
[![K8SPXC-274](https://badgen.net/badge/JIRA/K8SPXC-274/green)](https://jira.percona.com/browse/K8SPXC-274)
during each Pod start, we store MySQL version into version_info file
after that during the next Pod started we able to compare the current
MySQL version with the version stored in version_info
if version changed we run mysql_upgrade tool, it works fine if any
changes needed. but fails if MySQL changes not needed.
=> K8SPXC-274 force mysql_upgrade if version upgrade is detected

pkg/controller/pxc/tls.go
[![K8SPXC-417](https://badgen.net/badge/JIRA/K8SPXC-417/green)](https://jira.percona.com/browse/K8SPXC-417)
According to docs, we need to use `v1alpha2` version, since we are running on k8s `v1.14`
=> K8SPXC-417: fix certmanager api version

source/System-Requirements.rst
[![K8SPSMDB-234](https://badgen.net/badge/JIRA/K8SPSMDB-234/green)](https://jira.percona.com/browse/K8SPSMDB-234)
Since 1.14 is no longer available in stable channel
versions have to be updated
=> K8SPSMDB-234 GKE version upgrade

build/pxc-configure-pxc.sh
[![K8SPXC-416](https://badgen.net/badge/JIRA/K8SPXC-416/green)](https://jira.percona.com/browse/K8SPXC-416)
=> K8SPXC-416 use admin port for 'pxc-configure-pxc.sh'

build/pxc-configure-pxc.sh
[![K8SPXC-406](https://badgen.net/badge/JIRA/K8SPXC-406/green)](https://jira.percona.com/browse/K8SPXC-406)
This fixes K8SPXC-406 by not deleting the final comma in the line (which is important because if our recommendations for donors fails then we let galera choose any donor). The comma will be removed only in case if it's the only thing in the line for some reason.
Didn't delete adding the HOSTNAME variable in the end because in 3 node cluster on node-2 (highest) the variable would end up empty since it would delete node-0 and node-1.
In current state for K8SPXC-406 node-1 would end up like wsrep_sst_donor=cluster1-pxc-1, (the comma will not be deleted) - which means the node will not be able to do SST to itself so it will try any other node - since in this case we are not sure which …
=> K8SPXC-406 - fix wsrep_sst_donor option

pkg/controller/pxc/tls.go
[![K8SPXC-417](https://badgen.net/badge/JIRA/K8SPXC-417/green)](https://jira.percona.com/browse/K8SPXC-417)
FIxup certmanager api version, since v1alpha3 require k8s v1.15, but our main target is v1.14
=> K8SPXC-417: update certmanager version

cmd/peer-list/main.go
When single pod in cluster restarted, list of peers is not changed
so peer-list not calling onchange script and not updating list of servers in proxysql
during update kubernetes service without endpoints is not resolved, so we have this behaviour:
["cluster1-pxc-0"]
...
resolv error
...
["cluster1-pxc-0"]
We can fix ochange by resetting list when service not resolving.
see https://github.com/Percona-Lab/percona-openshift/pull/68 for more info.
=> Fix updating mysql hosts in proxysql for one node cluster

build/Dockerfile, build/pxc-init-entrypoint.sh
PXC pods container pxc-init is failing like below, but it is already added in the Dockerfile into the same location:
```
++ id -u
++ id -g
+ install -o 99 -g 99 -m 0755 -D /pxc-entrypoint.sh /var/lib/mysql/pxc-entrypoint.sh
++ id -u
++ id -g
+ install -o 99 -g 99 -m 0755 -D /unsafe-bootstrap.sh /var/lib/mysql/unsafe-bootstrap.sh
++ id -u
++ id -g
+ install -o 99 -g 99 -m 0755 -D /pxc-configure-pxc.sh /var/lib/mysql/pxc-configure-pxc.sh
++ id -u
++ id -g
+ install -o 99 -g 99 -m 0755 -D /liveness-check.sh /var/lib/mysql/liveness-check.sh
++ id -u
++ id -g
+ install -o 99 -g 99 -m 0755 -D /readiness-check.sh /var/lib/mysql/readiness-check.sh
++ id -u
++ id -g
+ install -o 99 -g 99 -m 0755 -D /usr/local/bin/peer-list /usr/local/bin/peer-list
install: '/usr/local/bin/peer-list' and …
```
=> Fix install of peer-list

source/custom-registry.rst, source/debug.rst, source/images.rst, source/index.rst
[![K8SPXC-461](https://badgen.net/badge/JIRA/K8SPXC-461/green)](https://jira.percona.com/browse/K8SPXC-461)
Images and digests moved to a separate doc; debug doc now mentions there are debug versions for all images and not only for pxc ones. Also, only current images are listed.
=> K8SPXC-461 rework the doc about certified images

e2e-tests/scheduled-backup/run
The previous implementation didn't take into consideration
the case when master node is the first one in list.
=> K8SPXC-471 Fix node labeling for Openshift

e2e-tests/functions
It had additional field on EKS so diff was failing:
```
apiVersion: v1
kind: Pod
metadata:
annotations:
kubernetes.io/psp: eks.privileged
openshift.io/scc: privileged
```
=> K8SPXC-471 - Fix for running security-context test in EKS

e2e-tests/functions, e2e-tests/monitoring-2-0/run, e2e-tests/monitoring/run, e2e-tests/scheduled-backup/run, e2e-tests/security-context/compare/statefulset_sec-context-proxysql-changes-4-oc.yml, e2e-tests/security-context/run
Since the security-context test has processing diffence for
openshift 3.11 and 4.x we need to know what platform version is
used for test execution.
=> K8SPXC-471 Fix security-context test for openshift

build/pxc-configure-pxc.sh, pkg/apis/pxc/v1/pxc_types.go, pkg/pxc/backup/restore.go
[![K8SPXC-438](https://badgen.net/badge/JIRA/K8SPXC-438/green)](https://jira.percona.com/browse/K8SPXC-438)
Reverts percona/percona-xtradb-cluster-operator#560
=> Revert "K8SPXC-438 add possibility to use 32 symbols for cluster name"

build/pxc-entrypoint.sh
[![K8SPXC-463](https://badgen.net/badge/JIRA/K8SPXC-463/green)](https://jira.percona.com/browse/K8SPXC-463)
* mysqld can crash in L459 in pxc-entrypoint.sh and we will
not have the output of 'wsrep_recovery_verbose' log
=> K8SPXC-463 add additional output of 'wsrep_recovery_verbose' log

pkg/pxc/statefulset.go
[![K8SPXC-487](https://badgen.net/badge/JIRA/K8SPXC-487/green)](https://jira.percona.com/browse/K8SPXC-487)
* stop using 'shareProcessNamespace' because it is not
supported by openshift 3.11
=> K8SPXC-487 Improve haproxy reload

pkg/controller/pxc/upgrade.go
This PR fixes limit logic.
Previous implementation count timeout as 
```pseudocode
for i from 0 to waitLimit {
sleep 1 second
ok = doSomeWork...
if ok {
break
}
}
```
There a 2 problems I see:
1. doSomeWork takes some time, but it does not counted as a time. So if time limit is 5 min this function will take `5 min` + `time to doSomeWork`*`count of iterations`
2. sleep 1 second. It's not proper to send request to PXC every second if previous call was unsuccessful.
In current implementation timeout is fair. In worst case it will take `waitLimit` + 10 sec
=> Improve smart-update limit logic

build/pxc-configure-pxc.sh, e2e-tests/one-pod/conf/one-pod.yml
[![K8SPXC-464](https://badgen.net/badge/JIRA/K8SPXC-464/green)](https://jira.percona.com/browse/K8SPXC-464)
* add usage of 'pc.weight' option to avoid situation
when pxc node becomes non-primary when backup via garbd
fails for one pod installation
=> K8SPXC-464 add 'pc.weight' option

deploy/crd.yaml, e2e-tests/functions, e2e-tests/haproxy/compare/statefulset_haproxy-haproxy.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-haproxy.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-170-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-170.yml, e2e-tests/upgrade-consistency/run, version/version.go
haproxy and monitoring-2.0 are failing with diff issue because of this fix: https://github.com/percona/percona-xtradb-cluster-operator/commit/32e6fa19ded2f2c148cc19a043f3d2e787ecd323
```
+ diff -u /mnt/jenkins/workspace/cloud-pxc-operator_PR-637/e2e-tests/haproxy/compare/statefulset_haproxy-haproxy.yml /tmp/tmp.lQln2oT2QJ/statefulset_haproxy-haproxy.yml
--- /mnt/jenkins/workspace/cloud-pxc-operator_PR-637/e2e-tests/haproxy/compare/statefulset_haproxy-haproxy.yml	2020-10-13 05:27:25.805522784 +0000
+++ /tmp/tmp.lQln2oT2QJ/statefulset_haproxy-haproxy.yml	2020-10-13 05:44:54.405369014 +0000
@@ -109,7 +109,6 @@
securityContext: {}
serviceAccount: default
serviceAccountName: default
-      shareProcessNamespace: true
terminationGracePeriodSeconds: 30
tolerations:
- effect: NoExecute
```
=> Update after PXC 1.6.0 release and prepare for 1.7.0

pkg/controller/pxc/controller.go
[![K8SPXC-503](https://badgen.net/badge/JIRA/K8SPXC-503/green)](https://jira.percona.com/browse/K8SPXC-503)
This should allow us to use initImage option in upgrade testing even before v1.7.0 is released.
=> K8SPXC-503 - remove check for v1.7.0 when applying init image

cmd/manager/main.go
[![K8SPXC-512](https://badgen.net/badge/JIRA/K8SPXC-512/green)](https://jira.percona.com/browse/K8SPXC-512)
JIRA issue reference: https://jira.percona.com/browse/K8SPXC-512
example code can be found here - https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#configuring-cluster-scoped-operators-with-multinamespacedcachebuilder
=> K8SPXC-512 feature Add support for comma separated namespaces in WATCH_NAMESPACE

e2e-tests/functions
All the tests on the master started failing like:
```
++ get_operator_pod
++ kubectl_bin get pods --selector=name=percona-xtradb-cluster-operator -o 'jsonpath={.items[].metadata.name}'
+++ mktemp
++ local LAST_OUT=/tmp/tmp.McVRNLwvIS
+++ mktemp
++ local LAST_ERR=/tmp/tmp.fd9OVyT6Yc
++ local exit_status=0
+++ seq 0 2
++ for i in '$(seq 0 2)'
++ kubectl get pods --selector=name=percona-xtradb-cluster-operator -o 'jsonpath={.items[].metadata.name}'
++ exit_status=1
++ [[ hB != hxB ]]
++ echo '--- 0 stdout'
++ cat - /tmp/tmp.McVRNLwvIS
--- 0 stdout
++ [[ hB != hxB ]]
++ echo '--- 0 stderr'
++ cat - /tmp/tmp.fd9OVyT6Yc
--- 0 stderr
error: error executing jsonpath "{.items[].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for …
```
=> Fix operator pod selector in e2e-tests functions

pkg/controller/pxc/controller.go
[![K8SPXC-503](https://badgen.net/badge/JIRA/K8SPXC-503/green)](https://jira.percona.com/browse/K8SPXC-503)
We have added same here: https://github.com/percona/percona-xtradb-cluster-operator/blob/master/pkg/controller/pxc/controller.go#L276-L278
but from what I see this is ignored on initial deployment, so this is another PR to fix this - that is if I'm not wrong, but it seems to work for me
This one is in `deploy` function and the first one is in `Reconcile`.
=> K8SPXC-503 - read initImage on initial deployment

e2e-tests/functions
We have changed the labels for the operator pod and changed `get_operator_pod` to recognise them, but they don't work for upgrade tests which start from earlier version since they don't have these same labels so the function needs to recognise both `name=percona-xtradb-cluster-operator` and `app.kubernetes.io/name=percona-xtradb-cluster-operator`.
=> Fix get_operator_pod to recognize old and new operator pod labels

e2e-tests/big-data/run, e2e-tests/functions, e2e-tests/init-deploy/run, e2e-tests/proxysql-sidecar-res-limits/run, e2e-tests/security-context/run, e2e-tests/smart-update/run, e2e-tests/tls-issue-cert-manager-ref/run, e2e-tests/tls-issue-cert-manager/run, e2e-tests/users/run
Where we use cert manager we use `secrets_without_tls.yml` and otherwise standard `secrets.yml` are used which include ssl secrets.
=> Cleanup of deploy_cert_manager usage

e2e-tests/functions, e2e-tests/init-deploy/run, e2e-tests/upgrade-haproxy/run, e2e-tests/upgrade-proxysql/run
This is fixing the init-deploy test which was depending on cert-manager before.
Other tests seem to be failing because of the issues which are already reported in jira:
operator-self-healing: https://jira.percona.com/browse/K8SPXC-531
limits and one-pod: https://jira.percona.com/browse/K8SPXC-537
upgrade tests: https://jira.percona.com/browse/K8SPXC-538
=> Fix init-deploy to use cert manager as issuer

Jenkinsfile, e2e-tests/upgrade-haproxy/run, e2e-tests/upgrade-proxysql/run
There are few problems:
1. The 3 hour timeout for test stage doesn't work properly, there are some jenkins bugs around this, probably it's related to 
`waitUntil` and `tryCatch` inside `runTest` function and that's why our test runs never finished.
2. Cleaning up crd in a messy situation when test fails can be problematic, a lot of users faced issues like that in kubernetes.
So this change is putting a 90min timeout for the command which is executing a particular test, which means the whole test run could take longer than 3 hrs, but at least it will not be left hanging forever and the proper cleanup will be done after test run.
Also for 2 upgrade tests seems cleanest and least problematic to just shutdown cluster and start a new one, the whole run will take few minutes longer but at least …
=> Fix timeout in Jenkinsfile and cleanup of upgrade tests

e2e-tests/operator-self-healing/run
If running in non cluster wide it was failing with:
```
kubectl_bin patch clusterrole percona-xtradb-cluster-operator --type=json -p '[{"op":"remove","path":"/rules/1"}]'
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "percona-xtradb-cluster-operator" not found
```
=> Fix operator-self-healing test for non cluster-wide environment

Jenkinsfile, e2e-tests/functions
* use "https://charts.helm.sh/stable" instead
of "https://kubernetes-charts.storage.googleapis.com/"
```
from log (+ helm repo add stable https://kubernetes-charts.storage.googleapis.com/
Error: repo "https://kubernetes-charts.storage.googleapis.com/" is no longer available; try "https://charts.helm.sh/stable" instead)
```
=> Always install the latest stable helm

pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-510](https://badgen.net/badge/JIRA/K8SPXC-510/green)](https://jira.percona.com/browse/K8SPXC-510)
Since RedHat allows us to interact with images in CR
we no longer need reading the corresponding data from ENV
=> K8SPXC-510 Removing obsolete steps

e2e-tests/functions
[![K8SPXC-587](https://badgen.net/badge/JIRA/K8SPXC-587/green)](https://jira.percona.com/browse/K8SPXC-587) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
From time to time CRD from a release tag an CRD from
master branch could not be applied on the same cluster.
Thus we need to check wheather we need to apply older
CRD or not.
=> K8SPXC-587 Intelligent release CRD application

pkg/controller/pxc/status.go
[![K8SPXC-608](https://badgen.net/badge/JIRA/K8SPXC-608/green)](https://jira.percona.com/browse/K8SPXC-608) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
As you may guess from title the operator tries to check
pod logs even for 1.5.0 cr version. It leads to errors since
the corresponding RBAC rule was introduced only since 1.7.0.
As a result cluster status is stucked in initializing state.
`{"level":"error","ts":1610800996.7042642,"logger":"controller_perconaxtradbcluster","msg":"Update status","error":"get pxc status: parse some-name-pxc-2 pod logs: get logs from some-name-pxc-2 pod: get pod logs stream: pods \"some-name-pxc-2\" is forbidden: User \"system:serviceaccount:upgrade-consistency-17013:percona-xtradb-cluster-oper …
=> K8SPXC-608 Allow log check only for 1.7.0 or greater

e2e-tests/functions, e2e-tests/one-pod/run
Update two waits for issues mostly seen in Minikube, but maybe they can be seen in other environments.
1. `one-pod` test was failing because it stops waiting for backup to finish, but the backup finishes a bit later. I have tried with value `90` also, but it doesn't seem to work (at least on minikube).
Since it will wait this long only if the test fails I don't think it's a problem to increase the value.
2. `validation-webhook` test was failing on minikube because the operator gets deployed, but we apply cr before the validation starts running, so this is to make sure that we give it some time for validation webhook to start running after operator pod running.
=> Update waits in e2e functions for Minikube

deploy/cr.yaml
autoRecovery is by default set to `true` so better to have it that way in cr.yaml so it's clear immediately
=> Change autoRecovery option in cr.yaml

e2e-tests/self-healing/compare/proxy-vars.sql
Fix the diff for self-healing test for 5.7:
```
+ diff -u /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/self-healing/compare/proxy-vars.sql /tmp/tmp.NCCAVD6Hzf/proxy-vars1.sql
--- /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/self-healing/compare/proxy-vars.sql	2021-01-21 12:35:23.000000000 +0000
+++ /tmp/tmp.NCCAVD6Hzf/proxy-vars1.sql	2021-01-21 13:05:27.068301607 +0000
@@ -30,7 +30,7 @@
admin-telnet_admin_ifaces	(null)
admin-telnet_stats_ifaces	(null)
admin-vacuum_stats	true
-admin-version	2.0.14-percona-1.1
+admin-version	2.0.15-percona-1.1
admin-web_enabled	false
admin-web_port	6080
mysql-add_ldap_user_comment	
@@ -88,6 +88,7 @@
mysql-max_connections	2048
mysql-max_stmts_cache	10000
mysql-max_stmts_per_connection	20 …
```
=> Fix diff in self-healing test for PXC 5.7

e2e-tests/functions
[![K8SPXC-608](https://badgen.net/badge/JIRA/K8SPXC-608/green)](https://jira.percona.com/browse/K8SPXC-608) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Since 3.11 does not remove namespaces immediately, we need to wait
for namespace removal in order to proceed with further tests
=> K8SPXC-608 Wait for operator namespace deletion on 3.11

cmd/pitr/collector/collector.go, cmd/pitr/main.go
[![K8SPXC-615](https://badgen.net/badge/JIRA/K8SPXC-615/green)](https://jira.percona.com/browse/K8SPXC-615) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
in previus implementation we was blocking on waiting for stderror.
This commit fixes this by providing buffer to stderror instead of
blocking on ioutill.ReadAll, which waits for io.EOF. But this error is
returned only at the end of command execution, which causing buffer grow
and pod eviction from k8s side.
Now, we are using io.Pipe and start writing to s3 immideatly to not
store any info inside pitr.
Plus, increase buffer size to make bigger reads, instead of 1kb chunks
=> K8SPXC-615: fix binlog uploading

cmd/pitr/collector/collector.go, cmd/pitr/recoverer/recoverer.go
[![K8SPXC-621](https://badgen.net/badge/JIRA/K8SPXC-621/green)](https://jira.percona.com/browse/K8SPXC-621) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
pitr: check error buffer before closing pipe
We need this check because if any error occures, mysqlbinlog sends EOF
to file, and we process further as normal situation.
Now, before closing pipe, we check the error buffer, and if any error
happens, we cancel upload to s3 and return error correctly.
We will process the failed binlog on next collector iteration
=> K8SPXC-621: check error buffer before closing pipe

Jenkinsfile, cmd/pitr/recoverer/recoverer.go, cmd/pitr/recoverer/recoverer_test.go, e2e-tests/pitr/conf/pitr.yml
[![K8SPXC-598](https://badgen.net/badge/JIRA/K8SPXC-598/green)](https://jira.percona.com/browse/K8SPXC-598) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
PITR needs information about last GTID stored in backup. This information stored in file which can be compressed by xtrabackup, so this PR add functionality that decompress needed file using xbstream tool. If file was not compressed xbstream just return its content
=> K8SPXC-598 Add support for compressed backups for PITR

Jenkinsfile, cmd/pitr/collector/collector.go, cmd/pitr/pxc/pxc.go, cmd/pitr/recoverer/recoverer.go
[![K8SPXC-627](https://badgen.net/badge/JIRA/K8SPXC-627/green)](https://jira.percona.com/browse/K8SPXC-627) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
When pod from where collector start uploading binlogs is failed collector should connect to pod with the oldest binlogs in cluster. We need to be sure that we didn't have gap between uploaded files
=> K8SPXC-627 Add logic for choosing host with oldest binlogs

deploy/crd.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/status.go
[![K8SPXC-647](https://badgen.net/badge/JIRA/K8SPXC-647/green)](https://jira.percona.com/browse/K8SPXC-647) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
it should be possible to scale up and scale down with the following command
```
kubectl scale --replicas=5 pxc/cluster1
```
also, it should be possible to use HPA with config similar to the next
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
name: cluster1
spec:
minReplicas: 3
maxReplicas: 5
metrics:
- resource:
name: cpu
targetAverageUtilization: 2
type: Resource
scaleTargetRef:
apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
name: cluster1
```
=> K8SPXC-647 allow change replicas count with "kubectl scale" command

Jenkinsfile
[![CLOUD-615](https://badgen.net/badge/JIRA/CLOUD-615/green)](https://jira.percona.com/browse/CLOUD-615) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
each time when we push to commit to PR or rerun tests the new comment is added into the GitHub PR.
As a result, we have tens of huge obsolete messages in each PR.
It is better to automatically clean up obsolete test results before push the newest test results.
=> CLOUD-615 automatically cleanup obsolete tests results in PR

cmd/pitr/pxc/pxc.go, cmd/pitr/recoverer/recoverer.go, cmd/pitr/recoverer/recoverer_test.go
[![K8SPXC-632](https://badgen.net/badge/JIRA/K8SPXC-632/green)](https://jira.percona.com/browse/K8SPXC-632) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Backups information about last GTID can be present like set which larger than GTID set of binlog file. So we can't understand on which binlog file should stop recover process . In this PR we add logic to solve this issue by using GTID_SUBTRACT to detect that backups last-gtid-set contains GTID from binlog
=> K8SPXC-632 Get last gtid from backup last gtid set

deploy/cr.yaml
If I'm not mistaking this is how it looked:
```
pxc:
- sidecars
- runtimeClassName
proxysql:
- sidecarResources
haproxy:
- sidecars
- sidecarResources
- runtimeClassName
```
so this adds:
- runtimeClassName and sidecards to proxysql
- sidecarResources to pxc
=> Consolidate sidecars and runtimeClassName options in cr.yaml

e2e-tests/security-context/compare/cronjob_adc5a-each-hour-pvc.yml, pkg/controller/pxc/controller.go, pkg/pxc/service.go
[![K8SPXC-614](https://badgen.net/badge/JIRA/K8SPXC-614/green)](https://jira.percona.com/browse/K8SPXC-614) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This PR fixes `createOrUpdate` func
Previously `DeepCopyObject` was used. Somewhy after we get deep copy of object and use it as an input of `client.Get` it returns us equal object. This is why I create new empty object and use it as an input of `client.Get`
=> K8SPXC-614: Fix updateOrCreate function

e2e-tests/pitr/conf/restore-on-pitr-minio.yaml
There seems to be some misalignment and as per the docs `backupName` and `backupSource` should not be used together.
Which also brings the question should we add a check and throw an error if both are specified at the same time in restore.
=> Fix restore-on-pitr-minio.yaml config in PITR e2e test

deploy/backup/copy-backup.sh
* I think namespace parameter is more often used by people than having it in a context
* This change has backwards compatibility to not use namespace as parameter if that's preferable by user
* Additionally, the script was tested in Mac OS so it covers more users
* Restore option tested from this backup, but using restore.yaml which is personally better than restore-backup.sh so didn't touch it in this PR
Summary: please feel free to decline if the script is not planned to use, doesn't fit into your plan or give me a guide on how to adjust my changes to be ready for merge based on your style, process, requirements, etc.
Thank you
=> add namespace support in copy-backup script

e2e-tests/functions
some tests are failing on 1.20 like:
```
+ diff -u /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/upgrade-consistency/compare/service_some-name-pxc-100.yml /tmp/tmp.lh2mueDKDc/service_some-name-pxc.yml
--- /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/upgrade-consistency/compare/service_some-name-pxc-100.yml	2021-03-30 05:30:02.000000000 +0000
+++ /tmp/tmp.lh2mueDKDc/service_some-name-pxc.yml	2021-03-30 07:28:12.176775782 +0000
@@ -11,6 +11,8 @@
kind: PerconaXtraDBCluster
name: some-name
spec:
+  clusterIPs:
+    - None
ports:
- name: mysql
port: 3306
```
=> Remove clusterIPs from e2e tests diff comparison

pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-568](https://badgen.net/badge/JIRA/K8SPXC-568/green)](https://jira.percona.com/browse/K8SPXC-568) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-568
Modified validation to restrict running more than 5 pods of PXC unless allowUnsafeConfigurations flag is set to true by changing PXC size to 5 if it's higher than that.
=> K8SPXC-568 feature: Restrict running more than 5 pods of PXC if unsafe flag is not set

build/pxc-entrypoint.sh, pkg/pxc/app/statefulset/node.go
[![K8SPXC-734](https://badgen.net/badge/JIRA/K8SPXC-734/green)](https://jira.percona.com/browse/K8SPXC-734) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Make our life easier to run the `kubectl exec` command when recovering manually. No need to config the correct namespace in the current context or manually adding the `-n <namespace>` argument into the recovery command.
Using the downward API to inject the pod namespace as `MY_POD_NAMESPACE` environment variable
=> K8SPXC-734: Include namespace in maual recovery command

cmd/peer-list/main.go
[![K8SPXC-509](https://badgen.net/badge/JIRA/K8SPXC-509/green)](https://jira.percona.com/browse/K8SPXC-509) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
The Docker image percona/percona-xtradb-cluster-operator:$version-haproxy configures the STOPSIGNAL to SIGUSR1 to shutdown HAProxy gracefully. peer-list needs to handle this as well because it is bundled in the same container.
Otherwise peer-list will just ignore the signal which leads to the pod staying in `Terminating` status for quite a while.
Closes [K8SPXC-509](https://jira.percona.com/browse/K8SPXC-509).
(Disclaimer: I'm "new" …
=> K8SPXC-509 Make peer-list handle SIGUSR1

cmd/pitr/recoverer/recoverer.go
[![K8SPXC-727](https://badgen.net/badge/JIRA/K8SPXC-727/green)](https://jira.percona.com/browse/K8SPXC-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Before, if we specify very short upload rate, we will flush binlogs too fast. In this case, we will have 1-2 transactions in each binlog file, which causes errors during restore.
=> K8SPXC-727: improve pitr on frequent uploads

pkg/controller/pxc/controller.go
[![K8SPXC-716](https://badgen.net/badge/JIRA/K8SPXC-716/green)](https://jira.percona.com/browse/K8SPXC-716) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Fix https://jira.percona.com/browse/K8SPXC-716 by ensuring that the sts belongs to the xtradb cluster before deletion. We also double check the uid of the sts in case the controller reads stale sts information
=> fix K8SPXC-716 by checking ownership and uid before deleting sts

e2e-tests/functions, e2e-tests/haproxy/run, e2e-tests/operator-self-healing/run, e2e-tests/self-healing-advanced/run, e2e-tests/self-healing/run
[![CLOUD-625](https://badgen.net/badge/JIRA/CLOUD-625/green)](https://jira.percona.com/browse/CLOUD-625) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-625 gke started to use containerd from 1.19

pkg/webhook/hook.go
[![K8SPXC-784](https://badgen.net/badge/JIRA/K8SPXC-784/green)](https://jira.percona.com/browse/K8SPXC-784) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This is written to match the [helm chart](https://github.com/percona/percona-helm-charts/blob/main/charts/pxc-operator/templates/deployment.yaml#L49-L50)
=> K8SPXC-784: parameterize operator deployment name with env var from helm chart

e2e-tests/haproxy/compare/service_haproxy-proxysql.yml, e2e-tests/init-deploy/compare/service_no-proxysql-pxc.yml, e2e-tests/init-deploy/compare/service_some-name-proxysql-unready.yml, e2e-tests/init-deploy/compare/service_some-name-proxysql.yml, e2e-tests/init-deploy/compare/service_some-name-pxc.yml, e2e-tests/proxysql-sidecar-res-limits/compare/service_side-car-proxysql.yml, e2e-tests/upgrade-consistency/compare/service_some-name-proxysql-190.yml, e2e-tests/upgrade-consistency/compare/service_some-name-pxc-190.yml, pkg/controller/pxc/controller.go, pkg/pxc/service.go
[![K8SPXC-772](https://badgen.net/badge/JIRA/K8SPXC-772/green)](https://jira.percona.com/browse/K8SPXC-772) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This makes it possible to use a label selector to get the component
specific service. This is e.g. needed for a ServiceMonitor.
=> K8SPXC-772: Add labels to service to make them distinguishable

pkg/controller/pxc/upgrade.go
[![K8SPXC-801](https://badgen.net/badge/JIRA/K8SPXC-801/green)](https://jira.percona.com/browse/K8SPXC-801) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
when the pxc sts is update and pxc size scale down concurrent, the operator will block until timeout because the pod will not restart in scaling down
=> K8SPXC-801: fix update and scale down concurrent

e2e-tests/functions
Some tests are failing with:
```
+ diff -u /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/upgrade-consistency/compare/service_some-name-pxc-100.yml /tmp/tmp.OvDghnycxE/service_some-name-pxc.yml
--- /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/upgrade-consistency/compare/service_some-name-pxc-100.yml	2021-07-07 08:56:44.000000000 +0000
+++ /tmp/tmp.OvDghnycxE/service_some-name-pxc.yml	2021-07-07 …
```
=> K8SPXC-808 - Fix diff in tests for Kubernetes 1.21

e2e-tests/functions, e2e-tests/haproxy/compare/pdb_haproxy-haproxy.yml, e2e-tests/haproxy/run, e2e-tests/init-deploy/compare/pdb_some-name-proxysql.yml, e2e-tests/init-deploy/compare/pdb_some-name-pxc.yml
init-deploy diff:
```
+ diff -u /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/init-deploy/compare/pdb_some-name-pxc.yml /tmp/tmp.neI9Mv1Jq5/pdb_some-name-pxc.yml
--- /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/init-deploy/compare/pdb_some-name-pxc.yml	2021-07-13 09:36:04.000000000 +0000
+++ /tmp/tmp.neI9Mv1Jq5/pdb_some-name-pxc.yml	2021-07-13 09:53:50.591878346 +0000
@@ -1,4 +1,4 @@ …
```
=> K8SPXC-808 - Fix init-deploy and haproxy on kubernetes 1.21

e2e-tests/functions, e2e-tests/security-context/compare/pod_restore-src-restore-pvc-sec-context-120.yml, e2e-tests/security-context/run
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection
Not sure if we should remove this mount altogether, but it is part of array so something like `yq d - 'spec.containers[0].volumeMounts[4]' | yq d - 'spec.volumes[4]'` doesn't look to proficient.
Name like `kube-api-access-w2g4v` is also variable so I have made it fixed to `kube-api-access` here.
Diff on GKE …
=> K8SPXC-808 - Fix security-context test for GKE 1.21

e2e-tests/functions, e2e-tests/init-deploy/run, e2e-tests/pitr/run, e2e-tests/self-healing-chaos/compare/proxy-vars.sql, e2e-tests/self-healing/compare/proxy-vars.sql, e2e-tests/users/run
1. `init-deploy` was failing on kubernetes `1.17` because of default container selection in the pod
```
bash-3.2$ kubectl exec some-name-proxysql-0 proxysql -- bash -c 'printf '\''SELECT hostname FROM runtime_mysql_servers WHERE hostgroup_id=11 AND status="ONLINE";\n'\'' | mysql -sN -h127.0.0.1 -P6032 -uproxyadmin -padmin_password'
Defaulting container name to proxysql.
Use 'kubectl describe pod/some-name-proxysql-0 -n …
```
=> K8SPXC-808 - Fix tests on different platforms

e2e-tests/self-healing-chaos/compare/proxy-vars-80.sql, e2e-tests/self-healing-chaos/compare/proxy-vars.sql, e2e-tests/self-healing/compare/proxy-vars-80.sql, e2e-tests/self-healing/compare/proxy-vars.sql
We switched to 2.1.1. now we go back to 2.0.18
=> K8SPXC-808 - Update chaos test for older proxysql version

e2e-tests/functions
`init-deploy` and `proxysql-sidecar-res-limits` are failing on GKE 1.21 like so:
```
+ diff -u /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/init-deploy/compare/service_some-name-proxysql.yml /tmp/tmp.ZiC8sHn1p2/service_some-name-proxysql.yml
--- /mnt/jenkins/workspace/pxc-operator-gke-version/source/e2e-tests/init-deploy/compare/service_some-name-proxysql.yml 2021-08-02 06:29:39.000000000 +0000
+++ …
```
=> K8SPXC-808 - Update functions to filter annotations for GKE in tests

deploy/cr.yaml
[![K8SPXC-868](https://badgen.net/badge/JIRA/K8SPXC-868/green)](https://jira.percona.com/browse/K8SPXC-868) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
1. adds requests/limits to haproxy/proxysql custom sidecar example
2. removes `sidecarResources` from PXC pods since it does nothing there
=> K8SPXC-868 - Fix examples for custom sidecar resources in cr.yaml

pkg/apis/pxc/v1/pxc_types.go, pkg/apis/pxc/v1/zz_generated.deepcopy.go, pkg/controller/pxc/upgrade.go, pkg/pxc/statefulset.go
[![K8SPXC-856](https://badgen.net/badge/JIRA/K8SPXC-856/green)](https://jira.percona.com/browse/K8SPXC-856) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This feature provides support for adding volumes to sidecar containers. Volumes can be added to sidecars using sidecarVolumes and sidecarPVCs on CR as below.
```    
sidecars:
- image: busybox
command: ["/bin/sh"]
args: ["-c", "while true; do trap 'exit 0' SIGINT SIGTERM SIGQUIT SIGKILL; done; "]
name: my-sidecar-1
volumeMounts:
- mountPath: /volume1
name: sidecar-volume-claim
- mountPath: /secret
name: sidecar-secret
- mountPath: …
```
=> K8SPXC-856 feature to add volumes for sidecars

build/pxc-entrypoint.sh
[![K8SPXC-824](https://badgen.net/badge/JIRA/K8SPXC-824/green)](https://jira.percona.com/browse/K8SPXC-824) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Fix for K8SPXC-824: Cluster may get into an unrecoverable state with incomplete full crash
Without this fix, it is possible to get an operator-controlled cluster into a state where some pxc pod other than the first one to start is the most advanced node and is ready for bootstrap, but it's neither bootstrapped nor does it fall under the (automatic) recovery conditions.
To recover from such condition, one must counter-intuitively edit …
=> Fix for K8SPXC-824 Cluster may get into an unrecoverable state

e2e-tests/init-deploy/compare/service_some-name-proxysql-unready.yml, pkg/pxc/service.go
[![K8SPXC-876](https://badgen.net/badge/JIRA/K8SPXC-876/green)](https://jira.percona.com/browse/K8SPXC-876) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-876
"service.alpha.kubernetes.io/tolerate-unready-endpoints" annotation has been
deprecated since Kuberneets 1.8 and the spec.publishNotReadyAddresses
parameter replacing it has been correctly implemented in Kubernetes 1.11
(see kubernetes/kubernetes#63742)
=> K8SPXC-876 use PublishNotReadyAddresses instead of annotation

pkg/controller/pxc/controller.go
[![K8SPXC-845](https://badgen.net/badge/JIRA/K8SPXC-845/green)](https://jira.percona.com/browse/K8SPXC-845) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Before, if we provide a wrong cr and then try to delete the
cluster, we will stuck, because finalizers are processed only
after checking this cr. For now, we check if cluster is deleted
first.
=> K8SPXC-845: do not stuck in case of wrong cr

pkg/controller/pxcbackup/controller.go
[![K8SPXC-842](https://badgen.net/badge/JIRA/K8SPXC-842/green)](https://jira.percona.com/browse/K8SPXC-842) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Before that change, we were undable to delete backup due to path
error. With this fix, we can easily delete backup from user's
folder, not just a bucket
=> K8SPXC-842: delete backup from folder

pkg/controller/pxc/upgrade.go
[![CLOUD-651](https://badgen.net/badge/JIRA/CLOUD-651/green)](https://jira.percona.com/browse/CLOUD-651) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/CLOUD-651
Fix statefulSet change detection logic
=> CLOUD-651 fix: smartupdate starts after pod deletion

e2e-tests/functions
This fixes the issue with demand-backup-encrypted-with-tls test.
Fix is commented here: https://github.com/kubernetes/kubernetes/issues/99504
Issue looked like:
```
$ kubectl get csr vault-csr-14845 -oyaml
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
creationTimestamp: "2021-11-10T10:44:30Z"
name: vault-csr-14845
resourceVersion: "1062060"
uid: c756936c-170f-47fb-9308-a59cea77b97f
spec:
groups:
- …
```
=> K8SPXC-895 - Fix certificate generation for vault server on 1.22

e2e-tests/functions
`kubectl_bin` deletes objects in a loop (3x) if it doesn't exit with `0` and has some sleep between, since we are doing chaos-mesh cleanup after every test this takes some time.
=> Do not use kubectl_bin for chaos-mesh cleanup

e2e-tests/functions, e2e-tests/init-deploy/compare/certificate_no-proxysql-ssl-internal.yml, e2e-tests/tls-issue-cert-manager/conf/some-name-tls-issue-haproxy.yml, e2e-tests/tls-issue-cert-manager/conf/some-name-tls-issue.yml, e2e-tests/tls-issue-cert-manager/run, pkg/controller/pxc/tls.go
[![K8SPXC-899](https://badgen.net/badge/JIRA/K8SPXC-899/green)](https://jira.percona.com/browse/K8SPXC-899) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-899
Also add pxc domain name from CN to the ssl-internal certificate, because running with `--ssl-mode=VERIFY_IDENTITY` doesn't work without it
=> K8SPXC-899: Add HAProxy domain names to ssl-internal certificate

e2e-tests/default-cr/run, e2e-tests/demand-backup-encrypted-with-tls/run, e2e-tests/functions, e2e-tests/monitoring-2-0/run, e2e-tests/restore-to-encrypted-cluster/run, e2e-tests/self-healing-chaos/compare/proxy-vars-80.sql, e2e-tests/self-healing/compare/proxy-vars-80.sql
`--purge` option doesn't exist any more for helm del and delete was renamed to uninstall so better to use it (https://helm.sh/docs/helm/helm_delete/).
Put a timeout to chaos-mesh delete and do not try to remove it on every namespace removal (there's a bug with stall when networkchaos crd is tried to delete).
=> Rename helm delete to uninstall and put timeout to chaos-mesh delete

e2e-tests/functions, e2e-tests/self-healing-chaos/compare/proxy-vars-80.sql, e2e-tests/self-healing/compare/proxy-vars-80.sql
[![K8SPXC-917](https://badgen.net/badge/JIRA/K8SPXC-917/green)](https://jira.percona.com/browse/K8SPXC-917) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Diff in scaling test on minikube:
```
+ diff -u /mnt/jenkins/workspace/pxc-operator-minikube/source/e2e-tests/scaling/compare/pvc_datadir-scaling-pxc-3.yml /tmp/tmp.XwV2SDSmFM/pvc_datadir-scaling-pxc-3.yml
--- /mnt/jenkins/workspace/pxc-operator-minikube/source/e2e-tests/scaling/compare/pvc_datadir-scaling-pxc-3.yml	2022-01-24 08:17:50.000000000 +0000
+++ /tmp/tmp.XwV2SDSmFM/pvc_datadir-scaling-pxc-3.yml	2022-01-24 08:48:39.478565785 …
```
=> K8SPXC-917 - Update self-healing tests for new PXC version

pkg/controller/pxc/users.go
when sync user, we should add query rule to proxysql too, otherwise the new user not auto Read/Write split
=> sync query rule when sync user

cmd/pitr/recoverer/recoverer.go
[![K8SPXC-985](https://badgen.net/badge/JIRA/K8SPXC-985/green)](https://jira.percona.com/browse/K8SPXC-985) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
We were trying to filter binlogs while applying to make storing binlogs
from multiple clusters in the same bucket possible. The filter is
implemented with the assumption that we can't have a different GTID from
the source cluster that we created the full backup from. This was wrong.
There are multiple ways that can lead GTID to change and making the
cluster that collects binlogs a replica of another is one of them.
We'll recommend …
=> K8SPXC-985: Remove binlog filter

deploy/backup/backup.yaml
[![K8SPXC-1056](https://badgen.net/badge/JIRA/K8SPXC-1056/green)](https://jira.percona.com/browse/K8SPXC-1056) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
In the example we have `fs-pvc` as storage for backup, but enable `delete-s3-backup` finalizer.
=> K8SPXC-1056 - Comment delete-s3-backup finalizer in the example backup.yaml

Jenkinsfile, deploy/bundle.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, e2e-tests/README.md, e2e-tests/default-cr/run, e2e-tests/functions, e2e-tests/manifest, e2e-tests/operator-self-healing-chaos/run, e2e-tests/self-healing-advanced-chaos/run, e2e-tests/self-healing-chaos/compare/proxy-vars-80.sql, e2e-tests/self-healing-chaos/run, e2e-tests/self-healing/compare/proxy-vars-80.sql, e2e-tests/smart-update/run, e2e-tests/validation-hook/run
[![CLOUD-666](https://badgen.net/badge/JIRA/CLOUD-666/green)](https://jira.percona.com/browse/CLOUD-666) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This should replace `yq v3` (which is not supported any more and doesn't have builds in some platforms) with `yq v4` for our E2E tests.
=> CLOUD-666 - Replace yq v3 with yq v4 for e2e tests

build/liveness-check.sh, build/readiness-check.sh
[![K8SPXC-1138](https://badgen.net/badge/JIRA/K8SPXC-1138/green)](https://jira.percona.com/browse/K8SPXC-1138) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* we need to use argument for a timeout command in
readiness/liveness scripts a little bit less to avoid
killing them by k8s
=> K8SPXC-1138 decrease the value for timeout in readiness/liveness

pkg/controller/pxc/controller.go, pkg/pxc/service.go
[![K8SPXC-1137](https://badgen.net/badge/JIRA/K8SPXC-1137/green)](https://jira.percona.com/browse/K8SPXC-1137) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-1137
PXC and HAProxy services were updated using `createOrUpdate` method, but not ProxySQL service
This PR removes redundant `createService` calls and removes this method
=> K8SPXC-1137: fix ProxySQL service update

cmd/pitr/collector/collector.go, cmd/pitr/main.go, cmd/pitr/pxc/pxc.go, cmd/pitr/recoverer/recoverer.go, cmd/pitr/storage/storage.go, e2e-tests/pitr/conf/pitr.yml, pkg/apis/pxc/v1/pxc_prestore_types.go, pkg/controller/pxcrestore/restore.go, pkg/pxc/app/deployment/binlog-collector.go, pkg/pxc/backup/restore.go
[![K8SPXC-1005](https://badgen.net/badge/JIRA/K8SPXC-1005/green)](https://jira.percona.com/browse/K8SPXC-1005) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-1005
Changes in `cmd/pitr`:
- Added `ctx` which can be cancelled via SIGTERM
- Use `ctx` in all functions instead of `context.TODO()`
- Added azure client which implements `Storage` interface
- Added azure env vars to `recoverer` and `collector` configs
- Added `STORAGE_TYPE` env var to determine which storage type is used
It's possible to specify binlog storage path in `container` field like …
=> K8SPXC-1005: add pitr support for azure backups

cmd/pitr/collector/collector.go, cmd/pitr/recoverer/recoverer.go
https://jira.percona.com/browse/K8SPXC-1005
PITR was failing when azure binlog storage's `container`  field contained only the container name, without subdirs
=> K8SPXC-1005: fix azure binlog storage

e2e-tests/functions, e2e-tests/users/conf/some-name.yml, e2e-tests/users/run, go.mod, go.sum, pkg/controller/pxc/controller.go, pkg/controller/pxc/users.go, pkg/controller/pxc/users_without_dp.go, pkg/controller/pxc/version.go, pkg/pxc/users/users.go
[![K8SPXC-1113](https://badgen.net/badge/JIRA/K8SPXC-1113/green)](https://jira.percona.com/browse/K8SPXC-1113) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* Support dual password
* Update internal secrets then check pass propagation and old pass discarding.
* Dual pass logic for all the users.
* Check if pass is propagated for components in parallel.
* Fix parallel pass propagation check.
* WIP - implemente propagation with annotation.
* Add isOldPassword discarded func.
* Check if pass is discarded.
* Fix sql scan issue.
* Use sql nullable string
* Log pxc ready.
* Fix …
=> K8SPXC-1113: dual passwords (#1268)

cmd/pitr/storage/storage.go, pkg/controller/pxcbackup/controller.go
[![K8SPXC-1005](https://badgen.net/badge/JIRA/K8SPXC-1005/green)](https://jira.percona.com/browse/K8SPXC-1005) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-1005
There was a problem while deleting the `#innodb_redo` folder in azure backup. The `azblob` package has problems with deleting blobs that contain special characters. This issue is mentioned here: https://github.com/Azure/azure-sdk-for-go/issues/19475.
We should url escape the blob names during the delete request.
Also, in this PR, we keep finalizers in backup, if they were failed
=> K8SPXC-1005: fix azure backup deletion

e2e-tests/proxy-protocol/run
- Master nodes do not except incoming pods, so need to filter them out
- Top nodes in list are more utilized then others. It's better to pick nodes in reverse order
- client ip is public on openshift. Needs to be reflected
=> Few tweaks for proxy protocol test on openshift

Jenkinsfile
[![K8SPXC-1111](https://badgen.net/badge/JIRA/K8SPXC-1111/green)](https://jira.percona.com/browse/K8SPXC-1111) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
1. If your commit is tagged with release tag the test run will fail with message below because it includes dots:
> ```ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Invalid value for field "cluster.name": "jen-pxc-1313-v1.12.0-9-gf50f655f-10-cluster1". Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,38}[a-z0-9])?)' (only lowercase alphanumerics and '-' allowed, must start with a letter and end with an …
```
=> K8SPXC-1111 - Fix jenkins stage names and obtaining git short commit

pkg/pxc/queries/queries.go, pkg/pxc/users/users.go
[![K8SPXC-1179](https://badgen.net/badge/JIRA/K8SPXC-1179/green)](https://jira.percona.com/browse/K8SPXC-1179) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* by default operator does not use tls connection to database
even if you create the user with 'REQUIRE SSL' it will not
work because tls is disabled by defult. In order to fix it
"tls: preferred" is set.
=> K8SPXC-1179 add possibility of using tls connections to mysql

deploy/backup/restore.yaml
[![K8SPXC-1192](https://badgen.net/badge/JIRA/K8SPXC-1192/green)](https://jira.percona.com/browse/K8SPXC-1192) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
restore.yaml file does not have all needed options
**Solution:**
Add spec.backupSource section into restore.yaml file
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1192 add missing options into restore.yaml file

cmd/manager/main.go, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/backup.go, pkg/controller/pxc/controller.go, pkg/controller/pxc/full_crash_recovery.go, pkg/controller/pxc/replication.go, pkg/controller/pxc/secrets.go, pkg/controller/pxc/upgrade.go, pkg/controller/pxc/users.go, pkg/controller/pxc/users_without_dp.go, pkg/controller/pxc/version.go, pkg/controller/pxcbackup/controller.go, pkg/pxc/statefulset.go
[![K8SPXC-1198](https://badgen.net/badge/JIRA/K8SPXC-1198/green)](https://jira.percona.com/browse/K8SPXC-1198) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
In a couple of places, we use formatted log messages, breaking the whole structured logging thing we have.
**Cause:**
Misuse of our logging lib.
**Solution:**
Replace formatted messages with constant messages and proper use of KV pairs for the dynamic part of a log.
**CHECKLIST**
---
**Jira**
**Tests**
=>  K8SPXC-1198: Remove formatted strings from log messages

Jenkinsfile
[![K8SPXC-1207](https://badgen.net/badge/JIRA/K8SPXC-1207/green)](https://jira.percona.com/browse/K8SPXC-1207) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*In some pipelines we push "passed" file in the moment when the test passes, in some in the pipeline post action and in some in both places.*
**Solution:**
*Optimally we should create "passed" file in the moment when the test passes and there's no need to redo it in the pipeline post action.*
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1207 - Remove setTestsResults() from Jenkinsfile

Jenkinsfile
[![CLOUD-761](https://badgen.net/badge/JIRA/CLOUD-761/green)](https://jira.percona.com/browse/CLOUD-761) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Currently for PXC we don't generate JUnit test report and there are list of test durations is also missing.*
**Solution:**
*Add Jenkins test report and durations and fix parallel test pipeline cancelation https://jira.percona.com/browse/CLOUD-775*
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-761 - Add test report and duration in Jenkins test runs

pkg/controller/pxc/controller.go
[![K8SPXC-1149](https://badgen.net/badge/JIRA/K8SPXC-1149/green)](https://jira.percona.com/browse/K8SPXC-1149) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-1149
---
**Problem:**
*When `.spec.secretsName` is not specified in the cr `delete-pxc-pvc` doesn't delete the secret*
**Cause:**
*The operator runs finalizers without setting it's internal cr defaults*
**Solution:**
*The operator should set it's internal cr defaults before running the finalizers*
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1149: `delete-pxc-pvc` doesn't delete default secrets

pkg/controller/pxc/upgrade.go
[![K8SPXC-1163](https://badgen.net/badge/JIRA/K8SPXC-1163/green)](https://jira.percona.com/browse/K8SPXC-1163) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-1163
---
**Problem:**
*When pxc pod stuck in some error state during the cr update, operator is unable to execute finalizers*
**Cause:**
*When PXC statefulset is updated, operator updates PXC pods one by one using `applyNWait` method. This method waits pod to be restarted and can wait up to 2 hours until it's ready. In this period of time, we can't delete the cr if finalizers …
=> K8SPXC-1163: fix cluster deletion in init state

e2e-tests/init-deploy/compare/certificate_no-proxysql-ssl-internal.yml, e2e-tests/init-deploy/compare/certificate_no-proxysql-ssl.yml, e2e-tests/tls-issue-cert-manager-ref/compare/certificate_some-name-tls-issueref-ssl.yml, e2e-tests/tls-issue-cert-manager/compare/certificate_some-name-tls-issue-ssl.yml, pkg/controller/pxc/tls.go
[![K8SPXC-1193](https://badgen.net/badge/JIRA/K8SPXC-1193/green)](https://jira.percona.com/browse/K8SPXC-1193) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-1193
---
**Problem:**
*Server certificates issued by cert-manager contain `isCA: true`*
**Solution:**
*Remove `isCA: true` from server certificates*
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1193: remove `isCA: true` from certificates

build/pxc-entrypoint.sh, e2e-tests/pitr/run, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/replication.go, pkg/controller/pxc/secrets.go, pkg/controller/pxc/upgrade.go, pkg/controller/pxc/users.go, pkg/controller/pxc/users_without_dp.go, pkg/controller/pxc/version.go, pkg/pxc/app/deployment/binlog-collector.go, pkg/pxc/app/pmm.go, pkg/pxc/app/statefulset/haproxy.go, pkg/pxc/app/statefulset/node.go, pkg/pxc/app/statefulset/proxysql.go, pkg/pxc/backup/job.go, pkg/pxc/backup/restore.go, pkg/pxc/users/users.go
[![K8SPXC-1225](https://badgen.net/badge/JIRA/K8SPXC-1225/green)](https://jira.percona.com/browse/K8SPXC-1225) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
The operator does not handle password expiration for system users it creates, so when a user sets `default_password_lifetime` the cluster will break.
**Solution:**
Create system users with `PASSWORD EXPIRE NEVER` policy. Also, when the operator is upgraded, we will update existing sys users with the same expiration policy. Users are updated only once by using annotations on our …
=>  K8SPXC-1225: System users with PASSWORD EXPIRE NEVER policy

e2e-tests/functions, e2e-tests/proxysql-sidecar-res-limits/run, pkg/controller/pxc/status.go, pkg/controller/pxc/status_test.go, pkg/pxc/app/statefulset/proxysql.go
[![K8SPXC-1247](https://badgen.net/badge/JIRA/K8SPXC-1247/green)](https://jira.percona.com/browse/K8SPXC-1247) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-1247
---
**Problem:**
*Cluster with `.spec.proxysql.serviceType: LoadBalancer` cannot get ready.*
**Cause:**
*Operator used unready service for `.status.host` field.*
**Solution:**
*Operator should use exposed service for `.status.host` field.*
To be able to catch this error in tests, the check for ready cluster status was added to `spinup_pxc` function
**CHECKLIST**
--- …
=> K8SPXC-1247: don't use unready proxysql svc for `.status.host`

e2e-tests/conf/some-name.yml, e2e-tests/functions, e2e-tests/pitr-gap-errors/run, e2e-tests/pitr/run
[![K8SPXC-1165](https://badgen.net/badge/JIRA/K8SPXC-1165/green)](https://jira.percona.com/browse/K8SPXC-1165) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
1. Cert-manager requires some additional privileges on different openshift versions and for us it failed on 4.10.
More info: https://cert-manager.io/docs/release-notes/release-notes-1.10/
https://docs.openshift.com/container-platform/4.10/security/seccomp-profiles.html#configuring-default-seccomp-profile_configuring-seccomp-profiles
2. Test cluster some-name specifies 1 proxysql pod, but it always …
=> K8SPXC-1165 - Fix cert-manager installation on OpenShift 4.10

.github/dependabot.yml
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-727 set day and time for dependabot

cmd/pitr/pxc/pxc.go
[![K8SPXC-1293](https://badgen.net/badge/JIRA/K8SPXC-1293/green)](https://jira.percona.com/browse/K8SPXC-1293) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
If proxy_protocol enabled (esp. with `proxy_protocol_networks="*"`), pitr collector fails to connect to MySQL and just hangs.
**Solution:**
Using admin port for connections fixes the problem.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1293: Use admin port in PiTR collector/recoverer

cmd/pitr/recoverer/recoverer.go
[![K8SPXC-1293](https://badgen.net/badge/JIRA/K8SPXC-1293/green)](https://jira.percona.com/browse/K8SPXC-1293) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Binlog recoverer stuck if proxy protocol enabled.
**Solution:**
Use admin port.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1293: Fix binlog replay if proxy protocol enabled

cmd/pitr/collector/collector.go, cmd/pitr/recoverer/recoverer.go
[![K8SPXC-1293](https://badgen.net/badge/JIRA/K8SPXC-1293/green)](https://jira.percona.com/browse/K8SPXC-1293) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
mysqlbinlog hangs and collector deadlocks.
**Cause:**
In case proxy protocol enabled mysqlbinlog fails to connect to DB using port 3306. Collector creates a named piped with read only mode but it hangs forever because no one writes to it.
**Solution:**
mysqlbinlog needs to use port 33062.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1293: Fix hanging mysqlbinlog in case proxy protocol enabled

Jenkinsfile
[![CLOUD-814](https://badgen.net/badge/JIRA/CLOUD-814/green)](https://jira.percona.com/browse/CLOUD-814) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Move from Kubernetes Platfrom v 1.14 to v 1.25 for all operator test cases

cmd/pitr/collector/collector.go, cmd/pitr/main.go, config/crd/bases/pxc.percona.com_perconaxtradbclusters.yaml, deploy/bundle.yaml, deploy/cr.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/pxc/app/deployment/binlog-collector.go
[![K8SPXC-1294](https://badgen.net/badge/JIRA/K8SPXC-1294/green)](https://jira.percona.com/browse/K8SPXC-1294) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Collector can hung indefinitely if there's a problem with network.
**Solution:**
Configure timeout for processing each binlog, if timeout exceeds crash the container.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1294: Crash collector container if binlog is not processed before timeout

cmd/manager/main.go, pkg/controller/pxcrestore/controller.go
[![K8SPXC-1151](https://badgen.net/badge/JIRA/K8SPXC-1151/green)](https://jira.percona.com/browse/K8SPXC-1151) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Restore status is "Point-in-time recovering" even though PiTR is finished.
**Solution:**
Set status to "Starting cluster" after PiTR is finished.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1151: Fix status after PiTR finished

pkg/controller/pxc/backup.go
[![K8SPXC-1333](https://badgen.net/badge/JIRA/K8SPXC-1333/green)](https://jira.percona.com/browse/K8SPXC-1333) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
#1544 
**Cause:**
When operator runs in cluster wide mode, it mixes up scheduled backups if cluster names are the same in multiple namespaces because it only uses cluster name as the prefix.
**Solution:**
Include namespace to scheduled backup prefix.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1333: Include namespace to scheduled backup prefix

e2e-tests/limits/compare/statefulset_no-limits-proxysql-increased-k127.yml, e2e-tests/limits/compare/statefulset_no-limits-proxysql-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-proxysql-increased.yml, e2e-tests/limits/compare/statefulset_no-limits-proxysql-k127.yml, e2e-tests/limits/compare/statefulset_no-limits-proxysql-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-proxysql.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-increased-k127.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-increased.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-k127.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-pxc.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-haproxy-k127.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-haproxy.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-pxc-k127.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-pxc-oc.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-pxc.yml, pkg/pxc/app/statefulset/haproxy.go, pkg/pxc/app/statefulset/node.go, pkg/pxc/app/statefulset/proxysql.go
[![K8SPXC-1329](https://badgen.net/badge/JIRA/K8SPXC-1329/green)](https://jira.percona.com/browse/K8SPXC-1329) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPXC-1329
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1329]: https://perconadev.atlassian.net/browse/K8SPXC-1329?atlOrigin=eyJpIjoiNWRk …
=> K8SPXC-1329: add `PMM_AGENT_PATHS_TEMPDIR` to pmm-agent sidecar

pkg/controller/pxc/controller.go, pkg/controller/pxc/controller_test.go
[![K8SPXC-1269](https://badgen.net/badge/JIRA/K8SPXC-1269/green)](https://jira.percona.com/browse/K8SPXC-1269) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
switching from haproxy to proxysql was broken for 5.7
**Cause:**
**Solution:**
added possibility to switch from haproxy to proxysql in 5.7
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1269]: …
=> K8SPXC-1269 add possibility to switch from haproxy to proxysql in 5.7

build/pxc-entrypoint.sh
[![K8SPXC-1268](https://badgen.net/badge/JIRA/K8SPXC-1268/green)](https://jira.percona.com/browse/K8SPXC-1268) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
pxc-container restarted immediately if /var/lib/mysql/sleep-forever file is removed
**Cause:**
sst deletes sleep-forever file
**Solution:**
do not delete sleep-forever-file.
**CHECKLIST**
---
**Jira**
**Tests** …
=> K8SPXC-1268 avoid sleep-forever deletion under sst

Makefile, pkg/apis/pxc/v1/pxc_types.go, pkg/controller/pxc/controller_test.go, pkg/pxc/app/statefulset/node.go, pkg/pxc/users/users.go
[![K8SPXC-1345](https://badgen.net/badge/JIRA/K8SPXC-1345/green)](https://jira.percona.com/browse/K8SPXC-1345) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Regression in customizing probes.
**Solution:**
Fix.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1345]: https://perconadev.atlassian.net/browse/K8SPXC-1345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1345: Fix overriding container probes

cmd/manager/main.go
---
**Problem:**
We accidentally changed leader election ID and it conflicts with PSMDB operator.
**Solution:**
Fix.
**CHECKLIST**
---
**Jira**
**Tests**
=> Fix leader election ID

.github/workflows/reviewdog.yml, pkg/controller/pxc/volumes.go
[![K8SPXC-1341](https://badgen.net/badge/JIRA/K8SPXC-1341/green)](https://jira.percona.com/browse/K8SPXC-1341) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
If there are some PVCs which are not used by any pod (for example after scale down) operator waits for them to resize but k8s doesn't resize them because they're unused.
**Solution:**
Only resize used PVCs.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1341]: https://perconadev.atlassian.net/browse/K8SPXC-1341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
=> K8SPXC-1341: Fix resizing PVCs if some are not used by pods

.github/workflows/reviewdog.yml, .github/workflows/test.yml, e2e-tests/demand-backup-cloud/compare/job.batch_restore-job-on-demand-backup-azure-demand-backup-cloud-k129.yml, e2e-tests/demand-backup-cloud/compare/job.batch_restore-job-on-demand-backup-s3-demand-backup-cloud-k129.yml, e2e-tests/demand-backup-cloud/compare/job.batch_xb-on-demand-backup-aws-s3-k129.yml, e2e-tests/demand-backup-cloud/compare/job.batch_xb-on-demand-backup-azure-blob-k129.yml, e2e-tests/demand-backup/compare/job_restore-job-on-demand-backup-minio-demand-backup-k129.yml, e2e-tests/demand-backup/compare/job_xb-on-demand-backup-minio-k129.yml, e2e-tests/functions, e2e-tests/security-context/compare/job.batch_restore-job-restore-pvc-sec-context-k129.yml, e2e-tests/security-context/compare/job.batch_restore-job-restore-s3-sec-context-k129.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-pvc-k129.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-s3-k129.yml
---
Kubernetes 1.29 has some new fields in Job object:
```
kind: Job
spec:
manualSelector: false
podReplacementPolicy: TerminatingOrFailed
```
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1295]: https://perconadev.atlassian.net/browse/K8SPXC-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1295 - Fix tests for Kubernetes 1.29

e2e-tests/pvc-resize/run
---
**Problem:**
pvc resizing is not supported for EKS v 1.29
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1295]: https://perconadev.atlassian.net/browse/K8SPXC-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
=> K8SPXC-1295 Skip test for EKS in pvc-resize script

e2e-tests/monitoring-2-0/compare/statefulset_monitoring-pxc-no-prefix-k127-oc.yml
TC `monitoring-2-0` was failing because file `e2e-tests/monitoring-2-0/compare/statefulset_monitoring-pxc-no-prefix-k127.yml` contains "`fsGroup: 1001`", so we have to create file `statefulset_monitoring-pxc-no-prefix-k127-oc.yml` where this line will be removed
---
**Problem:**
**Cause:**
**Solution:** …
=> K8SPXC-1295 Add file statefulset_monitoring-pxc-no-prefix-k127-oc.yml

deploy/cr.yaml
---
It's a leftover and deprecated options which are now used under `pxc.expose.labels` and `pxc.expose.annotations`
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1295]: https://perconadev.atlassian.net/browse/K8SPXC-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1295 - Remove serviceAnnotations/serviceLabels from cr.yaml

build/pxc-entrypoint.sh, e2e-tests/functions, e2e-tests/run-pr.csv, e2e-tests/smart-update1/run, e2e-tests/smart-update2/run, e2e-tests/upgrade-haproxy/run, e2e-tests/upgrade-proxysql/run
---
**Problem:**
*1. If there's an issue with the cluster the smart-update tests can run until Jenkins kills it.
2. version_info file gets deleted on SST so we don't run mysql_upgrade on upgrade when we start new mysql version*
**Solution:**
*1. Add max wait time for `smart-update`,`upgrade-haproxy` and `upgrade-proxysql` tests and in `wait_cluster_consistency` function
2. Put `version_info` file into …
=> K8SPXC-1295 - Add max wait in upgrade tests and add version_info file into exclude list for SST

Makefile, deploy/cr-minimal.yaml, deploy/cr.yaml
[![CLOUD-833](https://badgen.net/badge/JIRA/CLOUD-833/green)](https://jira.percona.com/browse/CLOUD-833) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Manual steps need to be taken to prepare release branch and also to prepare main branch after release branch is merged.
**Solution:**
With this manifests will be prepared but also next version and main images set in cr.yaml. What we need to still do manually is set specific database/backup and other images before the release since each product has it's own.
Prepare release example:
`make release …
=> CLOUD-833 - Add release and after-release targets to Makefile

e2e-tests/demand-backup/run
[![K8SPXC-1384](https://badgen.net/badge/JIRA/K8SPXC-1384/green)](https://jira.percona.com/browse/K8SPXC-1384) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*We check if the backup doesn't exists, but we look for it in the wrong folder.*
**Cause:**
*We added prefix/folder to test bucket, but didn't update the test correctly.*
**Solution:**
*Update test to check correct path.*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1384]: https://perconadev.atlassian.net/browse/K8SPXC-1384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> K8SPXC-1384 - Fix checking backup deletion in demand-backup test

.github/workflows/reviewdog.yml
[![CLOUD-849](https://badgen.net/badge/JIRA/CLOUD-849/green)](https://jira.percona.com/browse/CLOUD-849) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
On release branches we don't use main images so the reviewdog for manifests is failing and we need to ignore it.
**Solution:**
If a branch is named `release-` then we will use the exact version and instead of `perconalab` use `percona` repository. The check will only be done for operator image and bundles, not for other images since we cannot know all the versions.
**CHECKLIST**
---
**Jira** …
=> CLOUD-849 - Fix reviewdog for manifests on release branches

pkg/controller/pxc/controller.go
[![K8SPXC-1330](https://badgen.net/badge/JIRA/K8SPXC-1330/green)](https://jira.percona.com/browse/K8SPXC-1330) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Log left from development.
**Cause:**
It happens y'know.
**Solution:**
Remove.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1330]: https://perconadev.atlassian.net/browse/K8SPXC-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1330: Remove debug log

build/Dockerfile, build/backup-init-entrypoint.sh, e2e-tests/demand-backup-cloud/compare/job.batch_xb-on-demand-backup-aws-s3-k129.yml, e2e-tests/demand-backup-cloud/compare/job.batch_xb-on-demand-backup-aws-s3-oc.yml, e2e-tests/demand-backup-cloud/compare/job.batch_xb-on-demand-backup-aws-s3.yml, e2e-tests/demand-backup-cloud/compare/job.batch_xb-on-demand-backup-azure-blob-k129.yml, e2e-tests/demand-backup-cloud/compare/job.batch_xb-on-demand-backup-azure-blob-oc.yml, e2e-tests/demand-backup-cloud/compare/job.batch_xb-on-demand-backup-azure-blob.yml, e2e-tests/demand-backup/compare/job_xb-on-demand-backup-minio-k129.yml, e2e-tests/demand-backup/compare/job_xb-on-demand-backup-minio-oc.yml, e2e-tests/demand-backup/compare/job_xb-on-demand-backup-minio.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-pvc-k129.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-pvc.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-s3-k129.yml, e2e-tests/security-context/compare/job.batch_xb-on-demand-backup-s3.yml, pkg/pxc/app/statefulset/init.go, pkg/pxc/backup/job.go, pkg/pxc/backup/restore.go
[![K8SPXC-1337](https://badgen.net/badge/JIRA/K8SPXC-1337/green)](https://jira.percona.com/browse/K8SPXC-1337) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPXC-1337
---
This PR makes the operator inject `peer-list` binary in the backup job to the` /opt/percona` directory.
It will work only with images from this PR: https://github.com/percona/percona-docker/pull/990
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1337]: https://perconadev.atlassian.net/browse/K8SPXC-1337?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> K8SPXC-1337: add initContainer to backup job

deploy/cr-minimal.yaml
[![K8SPXC-1358](https://badgen.net/badge/JIRA/K8SPXC-1358/green)](https://jira.percona.com/browse/K8SPXC-1358) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
TLS is enabled in cr-minimal.yaml.
**Cause:**
Before, if cr.yaml doesn't have `spec.tls` section, TLS was disabled. Now the default is enabled.
**Solution:**
Disable TLS explicitly.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1358]: https://perconadev.atlassian.net/browse/K8SPXC-1358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
=> K8SPXC-1358: Disable TLS in cr-minimal.yaml

e2e-tests/pvc-resize/conf/some-name-eks.yml, e2e-tests/pvc-resize/conf/some-name.yml, e2e-tests/pvc-resize/run, pkg/controller/pxc/volumes.go
[![K8SPXC-1428](https://badgen.net/badge/JIRA/K8SPXC-1428/green)](https://jira.percona.com/browse/K8SPXC-1428) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem**:
We weren't properly converting GB to GiB.
**Solution**:
Convert properly.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1428]: https://perconadev.atlassian.net/browse/K8SPXC-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1428: Fix converting to volume size to GiB

pkg/controller/pxc/controller.go, pkg/controller/pxc/replication.go, pkg/controller/pxc/status.go, pkg/controller/pxc/status_test.go, pkg/controller/pxc/upgrade.go
[![K8SPXC-1429](https://badgen.net/badge/JIRA/K8SPXC-1429/green)](https://jira.percona.com/browse/K8SPXC-1429) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPXC-1429
---
This PR removes unnecessary error logs generated during the cluster deletion. Specifically, it removes the following error logs:
- `get pxc status: get statefulset: StatefulSet.apps \"cluster1-pxc\" not found`
- `Warning: Reconciler returned both a non-zero result and a non-nil error`
- `Operation cannot be fulfilled on perconaxtradbclusters.pxc.percona.com …
=> K8SPXC-1429: reduce error logs on cluster deletion

pkg/pxc/backup/pitr.go
[![K8SPXC-1441](https://badgen.net/badge/JIRA/K8SPXC-1441/green)](https://jira.percona.com/browse/K8SPXC-1441) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Crash if operator can't find latest timestamp for PiTR.
**Solution:**
Add a sanity check.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1441]: https://perconadev.atlassian.net/browse/K8SPXC-1441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1441: Fix crash if operator can't find latest PiTR timeline

build/proxysql-entrypoint.sh
[![K8SPXC-1259](https://badgen.net/badge/JIRA/K8SPXC-1259/green)](https://jira.percona.com/browse/K8SPXC-1259) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
proxysql-admin.cnf is not copied to the right location and because of that, we get `Permission denied` error in the proxysql entrypoint script.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1259]: https://perconadev.atlassian.net/browse/K8SPXC-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1259: Copy proxysql-admin.cnf to correct location

e2e-tests/demand-backup/run, e2e-tests/scheduled-backup/run
[![K8SPXC-1363](https://badgen.net/badge/JIRA/K8SPXC-1363/green)](https://jira.percona.com/browse/K8SPXC-1363) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
demand-backup and scheduled backup tests failed. 
**Cause:**
demand-backup: xbstream parallel option value is dynamically calculated based on available  resources. So depending on platform may differ. We had static value in `grep` for it.
scheduled-backup: to check whether the second backup was removed based on the 'spec.backup.schedule.keep' we have waited fixed 110 sec. Sometimes this time …
=> K8SPXC-1363: fix scheduled-backup and demand-backup tests

pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-1454](https://badgen.net/badge/JIRA/K8SPXC-1454/green)](https://jira.percona.com/browse/K8SPXC-1454) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPXC-1454
---
**Problem:**
*After upgrading from 1.14.0, operator starts creating TLS certificates and using them, if `.spec.allowUnsafeConfigurations: true`.*
**Cause:**
*After https://github.com/percona/percona-xtradb-cluster-operator/pull/1744, operator started using TLS certificates when both `.spec.tls.enabled` and `.spec.unsafe.tls` are set to `true`. When …
=> K8SPXC-1454: disable tls by default if `.spec.allowUnsafeConfigurations: true`

Jenkinsfile
---
**Problem:**
1.27 is removed from GKE.
**Solution:**
Use 1.28.
**CHECKLIST**
---
**Jira**
**Tests**
=> Use GKE 1.28 on Jenkins

e2e-tests/run-distro.csv
---
**Problem:**
run-distro.csv is used for integration testing before PXC distro components release. PMM is not a part of PXC distro and this test is flaky so may result in not related failures.
**Cause:**
---
**Solution:**
Remove this test from suite .
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-868: Remove monitoring-2.0 from pxc distro tests

pkg/controller/pxc/volumes.go
[![K8SPXC-1451](https://badgen.net/badge/JIRA/K8SPXC-1451/green)](https://jira.percona.com/browse/K8SPXC-1451) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPXC-1451
---
**Problem:**
*Starting from 1.14.0 PVC resize is enabled by default, but it should be disabled. https://github.com/percona/percona-xtradb-cluster-operator/pull/1824 disables the PVC resize by default, but only from versions `1.16.0`*
**Solution:**
*We should disable PVC resize on any version by removing version check.*
**CHECKLIST**
---
**Jira**
**Tests** …
=> K8SPXC-1451: remove comparing version

e2e-tests/demand-backup/run, pkg/controller/pxcbackup/controller.go, pkg/naming/labels.go
[![K8SPXC-1378](https://badgen.net/badge/JIRA/K8SPXC-1378/green)](https://jira.percona.com/browse/K8SPXC-1378) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPXC-1378
---
**Problem:**
*A regression was introduced in https://github.com/percona/percona-xtradb-cluster-operator/pull/1823, causing `.spec.backup.allowParallel` to stop functioning correctly.*
**Cause:**
*PR #1823 added new labels to the `pxc-backup` resource but did not update the `isOtherBackupRunning` method. As a result, this method still looks for `pxc-backup` …
=> K8SPXC-1378: fix `.spec.backup.allowParallel`

e2e-tests/functions
[![K8SPXC-1446](https://badgen.net/badge/JIRA/K8SPXC-1446/green)](https://jira.percona.com/browse/K8SPXC-1446) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
In pitr test a check whether all the proxy pods were removed during restore was added. `until` in `wait_for_delete` function "hangs" for 2+ mins while checking `pod/pitr-proxysql-0` deletion.  During this time the restore finishes and  when `pod/pitr-proxysql-1` is checked, the restore is finished and all the pods are up and running again.
**Cause:**
kubectl_bin usage instead of kubectl …
=> K8SPXC-1446: use kubectl in wait_for_delete function

e2e-tests/pvc-resize/run, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-1141-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-proxysql-1151-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-1141-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-pxc-1151-oc.yml
[![K8SPXC-1446](https://badgen.net/badge/JIRA/K8SPXC-1446/green)](https://jira.percona.com/browse/K8SPXC-1446) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
1) pvc-resize fails on eks and openshift. EKS and openshift allow to resize pvc once per 6 hours so we create 2 pxc clusters for pvc-resize test. 1.16.0 disables pvc-resize by default. For test the resize is enabled only for first cluster so resize fails on after the 2nd cluster creation.
2) upgrade-consistency test fails due to generation.
**Solution:**
1) Enable PVC resize on the second …
=> K8SPXC-1446: fix pvc-resize and upgrade-consistency for oc

build/liveness-check.sh, build/readiness-check.sh
[![K8SPXC-1222](https://badgen.net/badge/JIRA/K8SPXC-1222/green)](https://jira.percona.com/browse/K8SPXC-1222) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Version check didn't include 8.4, so I added it. I also added a sanity check for existence of state file.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1222]: https://perconadev.atlassian.net/browse/K8SPXC-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1222: Fix state check in probes for 8.4

cmd/mysql-state-monitor/main.go
[![K8SPXC-1222](https://badgen.net/badge/JIRA/K8SPXC-1222/green)](https://jira.percona.com/browse/K8SPXC-1222) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
MySQL 8.4 added new status notifications, this PR adds necessary changes to handle them.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1222]: https://perconadev.atlassian.net/browse/K8SPXC-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1222: Handle new statuses added in 8.4

e2e-tests/tls-issue-self/compare/pxc_some-name-enabled.yml, e2e-tests/tls-issue-self/compare/pxc_some-name.yml, e2e-tests/tls-issue-self/run, pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-1411](https://badgen.net/badge/JIRA/K8SPXC-1411/green)](https://jira.percona.com/browse/K8SPXC-1411) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
`cr.TLSEnabled()` checks both `spec.unsafeFlags.tls` and `spec.tls.enabled` and mistakenly used in `CheckNSetDefaults`. We need to use only `spec.tls.enabled` to check if TLS is enabled for safe configuration.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1411]: https://perconadev.atlassian.net/browse/K8SPXC-1411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
=> K8SPXC-1411: Fix disabling TLS without unsafe flag

e2e-tests/custom-users/conf/some-name.yml
[![K8SPXC-1410](https://badgen.net/badge/JIRA/K8SPXC-1410/green)](https://jira.percona.com/browse/K8SPXC-1410) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
PXC pod is killed by OOM killer in custom-users test
**Cause:**
**Solution:**
Increase memory limit in custom-users test
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1410]: https://perconadev.atlassian.net/browse/K8SPXC-1410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> K8SPXC-1410: set memory in custom-users test to 2

build/Dockerfile, build/readiness-check.sh, cmd/mysql-state-monitor/main.go
[![K8SPXC-1222](https://badgen.net/badge/JIRA/K8SPXC-1222/green)](https://jira.percona.com/browse/K8SPXC-1222) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
1. Removed state check from readiness probe
2. Added build info to state monitor
3. Add one missing status
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1222]: https://perconadev.atlassian.net/browse/K8SPXC-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1222: Remove state check from readiness probe

pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-377](https://badgen.net/badge/JIRA/K8SPXC-377/green)](https://jira.percona.com/browse/K8SPXC-377) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
When multiple users with the same name are present, unexpected results occur.
**Solution:**
Validate user for uniqueness. If there are duplicates reject the CR as invalid.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-377]: https://perconadev.atlassian.net/browse/K8SPXC-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-377: Check for custom user names uniqueness.

build/pxc-entrypoint.sh
[![K8SPXC-1222](https://badgen.net/badge/JIRA/K8SPXC-1222/green)](https://jira.percona.com/browse/K8SPXC-1222) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Remove unnecessary code.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1222]: https://perconadev.atlassian.net/browse/K8SPXC-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1222: Remove state check for 5.7

go.mod, go.sum
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-727]: https://perconadev.atlassian.net/browse/CLOUD-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> CLOUD-727 bump golang.org/x/net to 0.33.0

pkg/naming/backup.go
Don't add the storage name twice to the scheduled backup name
Adding a storage name twice might make a job name longer than 63 characters and break backup creation
---
**Problem:**
Scheduled backups are not being created after v1.16.0 in some situations when the storage name is not short.
**Cause:**
After v1.16.0 storage name is added to the scheduled backup name twice, see [PR#1823](https://github.com/percona/percona-xtradb-cluster-operator/pull/1823).
The example of generated `pxc-backup` name before: `cron-dev-1-db-s3-backups-daily-20241220005-372f8`
The example of generated `pxc-backup` name after: `cron-dev-1-dbs3-backups-daily-s3-backups-daily-202412230055-372f8`
**Solution:**
Don't add the backup storage name twice to the scheduled backup name.
**CHECKLIST** …
=> fix: don't add the storage name twice to the scheduled backup name

pkg/controller/pxc/backup.go
Set controller reference for PiTR deployment the same way as it's set for PXC and proxy StatefulSets
This would crate a connection between PiTR deployment and cluster resource.
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1543: set controller reference for binlog-collector deployment

cmd/pitr/collector/collector.go, cmd/pitr/main.go, pkg/pxc/app/deployment/binlog-collector.go
The following metrics have been added:
- `pxc_binlog_collector_success_total`
- `pxc_binlog_collector_failure_total`
- `pxc_binlog_collector_last_processing_timestamp`
- `pxc_binlog_collector_last_upload_timestamp`
- `pxc_binlog_collector_gap_detected_total`
Additionally, a simple /health endpoint has been added
---
**Problem:**
We don't have any prometheus metrics from pitr deployment, so the observability of binlog backups is quite limited.
**Cause:**
No prometheus metrics in binlog-collector application.
**Solution:**
Add prometheus metrics to binlog-collector application.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPXC-1544: Add basic Prometheus metrics for binlog-collector

pkg/apis/pxc/v1/pxc_types.go, pkg/pxc/service.go
[![K8SPXC-1538](https://badgen.net/badge/JIRA/K8SPXC-1538/green)](https://jira.percona.com/browse/K8SPXC-1538) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
We use ha source range for replicas too even if replicas are not exposed.
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1538]: …
=> K8SPXC-1538 fix loadBalancerSourceRanges for replicas

e2e-tests/functions, pkg/pxc/statefulset.go
[![K8SPXC-1466](https://badgen.net/badge/JIRA/K8SPXC-1466/green)](https://jira.percona.com/browse/K8SPXC-1466) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
If don't use -c option we login to random container of the pod.
**Cause:**
**Solution:**
Need to specify annotation with default container. 
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1466]: …
=> K8SPXC-1466 default container annotation

config/crd/bases/pxc.percona.com_perconaxtradbclusterbackups.yaml, config/crd/bases/pxc.percona.com_perconaxtradbclusters.yaml, deploy/backup/backup.yaml, deploy/bundle.yaml, deploy/cr.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, pkg/apis/pxc/v1/pxc_backup_types.go, pkg/apis/pxc/v1/pxc_types.go, pkg/apis/pxc/v1/zz_generated.deepcopy.go, pkg/controller/pxcbackup/controller.go, pkg/controller/pxcbackup/deadline.go, pkg/controller/pxcbackup/deadline_test.go, pkg/controller/pxcbackup/suite_test.go
[![K8SPXC-1366](https://badgen.net/badge/JIRA/K8SPXC-1366/green)](https://jira.percona.com/browse/K8SPXC-1366) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
suspendedDeadlineSeconds allows user to configure maximum duration that
backup job can wait in suspended state. This field is optional and can
be configured in two separate places:
1. PerconaXtraDBClusterBackup.spec.suspendedDeadlineSeconds: Always used if defined.
2. PerconaXtraDBCluster.spec.backup.suspendedDeadlineSeconds: Used only if not defined in PerconaXtraDBClusterBackup.
Suspended deadlines seconds are checked against …
=> K8SPXC-1366: Add suspendedDeadlineSeconds

e2e-tests/demand-backup-flow-control/conf/backup.yml, e2e-tests/demand-backup-flow-control/conf/cr.yml, e2e-tests/demand-backup-flow-control/conf/lease.yaml, e2e-tests/demand-backup-flow-control/run, e2e-tests/demand-backup-parallel/run, e2e-tests/functions, e2e-tests/run-pr.csv, e2e-tests/run-release.csv, pkg/controller/pxc/backup.go, pkg/controller/pxcbackup/controller.go, pkg/k8s/lease.go, pkg/k8s/lease_test.go, pkg/naming/backup.go
[![K8SPXC-1366](https://badgen.net/badge/JIRA/K8SPXC-1366/green)](https://jira.percona.com/browse/K8SPXC-1366) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Locks are not released if reconciliation finishes early, so this issue should also happen with other reconciliation errors.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1366]: https://perconadev.atlassian.net/browse/K8SPXC-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1366: Fix releasing backup lock if backup is failed due to deadlines

cmd/pitr/collector/collector.go
[![K8SPXC-1544](https://badgen.net/badge/JIRA/K8SPXC-1544/green)](https://jira.percona.com/browse/K8SPXC-1544) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Add a new metric to count successfully uploaded binlogs.
```
bash-5.1$ curl --silent localhost:8080/metrics | grep -E '^pxc_binlog'
pxc_binlog_collector_failure_total 0
pxc_binlog_collector_gap_detected_total 0
pxc_binlog_collector_last_processing_timestamp 1.742998486453379e+09
pxc_binlog_collector_last_upload_timestamp 1.7429981182245624e+09
pxc_binlog_collector_success_total 38 …
```
=> K8SPXC-1544: Add prometheus counter for uploaded binlogs

deploy/cr.yaml, pkg/apis/pxc/v1/pxc_types.go
[![K8SPXC-1538](https://badgen.net/badge/JIRA/K8SPXC-1538/green)](https://jira.percona.com/browse/K8SPXC-1538) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
We don't use the field enabled for exposePrimary and it should be deprecated. 
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1538]: https://perconadev.atlassian.net/browse/K8SPXC-1538?atlOrigin=eyJpIjoiNWRkN …
=> K8SPXC-1538 deprecate enabled field for primary

e2e-tests/demand-backup-cloud/run
[![K8SPXC-1475](https://badgen.net/badge/JIRA/K8SPXC-1475/green)](https://jira.percona.com/browse/K8SPXC-1475) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1475]: https://perconadev.atlassian.net/browse/K8SPXC-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1475: change condition for backup pods num

e2e-tests/upgrade-haproxy/compare/statefulset_upgrade-haproxy-haproxy-oc.yml
[![K8SPXC-1535](https://badgen.net/badge/JIRA/K8SPXC-1535/green)](https://jira.percona.com/browse/K8SPXC-1535) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Missing `spec.persistentVolumeClaimRetentionPolicy` in Openshift compare files
**Solution:**
Add field in compare file.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1535]: https://perconadev.atlassian.net/browse/K8SPXC-1535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1535: Fix upgrade-haproxy Openshift e2e-test

e2e-tests/demand-backup-cloud/run
[![K8SPXC-1620](https://badgen.net/badge/JIRA/K8SPXC-1620/green)](https://jira.percona.com/browse/K8SPXC-1620) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1620]: https://perconadev.atlassian.net/browse/K8SPXC-1620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1620: update cleanup test according to retry changes

Jenkinsfile
[![K8SPXC-1553](https://badgen.net/badge/JIRA/K8SPXC-1553/green)](https://jira.percona.com/browse/K8SPXC-1553) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1553]: https://perconadev.atlassian.net/browse/K8SPXC-1553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1553 k8s ver bump to 1.30

config/crd/bases/pxc.percona.com_perconaxtradbclusters.yaml, deploy/bundle.yaml, deploy/cr.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, pkg/apis/pxc/v1/pxc_types.go, pkg/pxc/app/statefulset/haproxy.go, pkg/pxc/app/statefulset/node.go, pkg/pxc/app/statefulset/proxysql.go
[![K8SPXC-1615](https://badgen.net/badge/JIRA/K8SPXC-1615/green)](https://jira.percona.com/browse/K8SPXC-1615) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Add opportunity to add custom pmm name.
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
https://github.com/percona/percona-helm-charts/pull/535
[K8SPXC-1615]: …
=> K8SPXC-1615 add custom name

pkg/controller/pxc/volumes.go
[![K8SPXC-1450](https://badgen.net/badge/JIRA/K8SPXC-1450/green)](https://jira.percona.com/browse/K8SPXC-1450) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPXC-1450
---
**Problem:**
*PVC resizing to smaller sizes is not allowed and results in an error, leaving the cluster in an error state. However, when a quota is reached, the values in the cr are reverted.*
**Solution:**
*The operator should not only return an error but also revert the changes made to the cr.*
**CHECKLIST**
---
**Jira**
**Tests** …
=> K8SPXC-1450: handle error when downsizing pvc

build/backup/lib/pxc/aws.sh
[![K8SPXC-1382](https://badgen.net/badge/JIRA/K8SPXC-1382/green)](https://jira.percona.com/browse/K8SPXC-1382) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1382]: https://perconadev.atlassian.net/browse/K8SPXC-1382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> K8SPXC-1382 set AWS credentials only when provided

pkg/pxc/backup/storage/storage.go
[![K8SPXC-1548](https://badgen.net/badge/JIRA/K8SPXC-1548/green)](https://jira.percona.com/browse/K8SPXC-1548) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Few improvements for logs when deleting backups from storages.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPXC-1548]: https://perconadev.atlassian.net/browse/K8SPXC-1548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPXC-1548: Minor log improvements
